### ISSUE TITLE
Please allow setting APP_ID and API_KEYs from a plugin configurations option.

### ISSUE THREAD

**Issue by emc2spider** [intercom/intercom-cordova#1]
This is more a feature request than an issue, but here it goes...

Currently the APP_ID and API_KEYs are to be set as variables when installing the plugin. However, we're faced with the situation of having two environments configured for the app (testing and production), therefore we have two sets of values for the install variables.

It has proven highly inconvenient to uninstall/install the plugin, or chase around the embedded values on the platform build files every time we need to change the build environment.

Could we have some extra initialisation function for configuring the plugin? or manage it through plugin preferences on the config.xml file?

Just a suggestion, hope you find it useful and worth to include. Other than that the plugin is very useful and easy to use!

Cheers,
EMCC

**Comment by Anu2g** [comment]
+1

**Comment by jtreanor** [comment]
Thanks for the suggestion @emc2spider.

An easier way to change your `APP_ID` or api key is to edit your `AndroidManifest.xml` or your `info.plist`. This will tell Intercom to use the different environment. I am completely open to suggestions on how to do this better

The reason that we require APP_ID the API_KEYs are required at install is because they must be known in [pluginInitialize](https://github.com/intercom/intercom-cordova/blob/master/src/ios/IntercomBridge.m#L19). If we provided a `setApiKey` or similar JavaScript function, it would be called too late.

**Comment by emc2spider** [comment]
@jtreanor sadly changing the AndroidManifest or the info.plist is not working for me as these files get overwritten by the Cordova build process resetting the variables to the install values.

Maybe allowing them to be edited through the config.xml or plugin.xml files? Since any javascript function will not be suitable for initialisation of the plugin.

I'm just throwing here the configuration options I've seen while using other plugins, haven't got to develop a plugin myself. Sorry if I'm suggesting options that make no sense at all =/

**Comment by jtreanor** [comment]
Thanks for the suggestions @emc2spider.

Could you give examples of plugins that use the configuration methods you have suggested? I would love if something like this would work for us.

**Comment by emc2spider** [comment]
@jtreanor I'm currently using https://github.com/apache/cordova-plugin-statusbar and https://github.com/apache/cordova-plugin-splashscreen which use config.xml for setting up the preferences.

They're both elements that need to be loaded very soon upon app execution so I imagine they are good examples for it. Hope it helps!

**Comment by jtreanor** [comment]
Thanks @emc2spider, I appreciate it. I'll look into our options.

**Comment by jtreanor** [comment]
While we haven't solved this issue yet directly, in the meantime you could change the variables by editing `plugins/ios.json`, `plugins/android.json` and `fetch.json`.

**Comment by slorber** [comment]
Also interested in a way to customize the  cordova env, to use dev/prod services

I think this should be provided by Cordova as a generic feature so I opened an issue: https://issues.apache.org/jira/browse/CB-9607

**Comment by jtreanor** [comment]
Thanks for pointed that out @slorber 

Its certainly an improvement, but still not ideal.

**Comment by ArnaudSpanneut** [comment]
Hi all.

I'm also interested by this feature. I think it's much easier to configure preferences in config.xml file.

Cheers.

**Comment by ArnaudSpanneut** [comment]
https://github.com/intercom/intercom-cordova/pull/21

**Comment by jtreanor** [comment]
Thanks @ArnaudSpanneut, that looks great. I will test it out and hopefully we can get it merged soon :smile:

**Comment by emc2spider** [comment]
Thanks @ArnaudSpanneut!! looking forward for this to be resolved :)

**Comment by jtreanor** [comment]
I have made these changes in the just released 1.1.0. The README is updated [here](https://github.com/intercom/intercom-cordova#configuring-intercom).

Thanks to @ArnaudSpanneut for contributing these changes.

Let me know if you have any issues.

**Comment by ArnaudSpanneut** [comment]
@jtreanor Thanks guy :smiley:
