### ISSUE TITLE
IOS UIRemoteNotificationType is deprecated since IOS 8

### ISSUE THREAD

**Issue by fmp777** [intercom/intercom-cordova#102]
> cordova-plugin-intercom/IntercomBridge.m:145:11: 'UIRemoteNotificationType' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.

Its ok for now, but figured you should have it on your roadmap

**Comment by jtreanor** [comment]
Hi @fmp777,

What version of the plugin are you using? We no longer use `UIRemoteNotificationType`.

**Comment by fmp777** [comment]
Oh so sorry, I did update the plugin to latest v3, but it seems it got reverted somewhere along the way.  My apologies!  Thanks guys!

**Comment by jtreanor** [comment]
No problem, happy to help 😄

**Comment by AshishBarde** [comment]
hi I have problem with cordova push notification plugin showing error UIRemoteNotificationType is deprecated.
I am using cordova plugin add https://github.com/phonegap-build/PushPlugin.git

**Comment by AshishBarde** [comment]
please help mi out

**Comment by skylerwshaw** [comment]
@AshishBarde as described above, Intercom does not use `UIRemoteNotificationType` any longer. Please ensure that you are using the latest version.

If you're only using Intercom for push notifications, this plugin is all you need. If you are using multiple push providers, it's obligatory to use this fork of `phonegap-plugin-push`: https://github.com/intercom/phonegap-plugin-push

Please see this documentation page for more details: https://developers.intercom.com/docs/cordova-phonegap-push-notifications

**Comment by AshishBarde** [comment]
can you provide the code link for it what I need to do it.
