### ISSUE TITLE
IOS registerForRemoteNotificationTypes deprecated IOS8

### ISSUE THREAD

**Issue by fmp777** [intercom/intercom-cordova#103]
>cordova-plugin-intercom/IntercomBridge.m:144:22: 'registerForRemoteNotificationTypes:' is deprecated: first deprecated in iOS 8.0 - Use -[UIApplication registerForRemoteNotifications] and UserNotifications Framework's -[UNUserNotificationCenter requestAuthorizationWithOptions:completionHandler:]

**Comment by jtreanor** [comment]
As in #102, this is also already fixed 😄
