### ISSUE TITLE
Is v3.0.14 support the new messager update

### ISSUE THREAD

**Issue by yankopetrov** [intercom/intercom-cordova#104]
I receive a message from intercom team to update my __iOS__ and __Android SKDs__. Is __intercom-cordova__ plugin __v3.0.14__ already have them updated or i have to wait for new update?

__UPDATE__

Here are the links for native SDKs upgrade they sent me:

https://docs.intercom.com/a-guide-to-the-new-intercom-messenger/upgrade-to-the-new-messenger-android

https://docs.intercom.com/a-guide-to-the-new-intercom-messenger/upgrade-to-the-new-messenger-ios

**Comment by bboyle18** [comment]
Hi @yankopetrov 👋 

Yep, 3.0.14 is fully up to date with our latest mobile SDKs. If you just update to this version everything should be 👌 

Cheers

Brian

**Comment by yankopetrov** [comment]
@bboyle18 Thanks!

**Comment by yankopetrov** [comment]
I have a problem with 3.0.13 - 3.0.15.  Android build is success, but when i try to run on device i get a message "Unfortunately, AppName has stopped". I am not sure where the problem is and have to debug.

I tried to downgrade version by version and for now 3.0.12 is working. @bboyle18 is it up to date with the latest mobile SDKs?

**Comment by bboyle18** [comment]
Hi @yankopetrov 👋 

I see you logged this issue [here](https://github.com/intercom/intercom-cordova/issues/109) 👍 
One of our Android engineers is looking at it and will get back to you there.

Cheers

Brian
