### ISSUE TITLE
How do I use this plugin with ionic 2

### ISSUE THREAD

**Issue by iAn-Pinto** [intercom/intercom-cordova#107]
How do I use this plugin with ionic 2

## My System information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.34
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jtreanor** [comment]
Hi @iAn-Pinto,

Because Ionic is built on top of Cordova, you should be able to follow the usage instructions provided for Cordova.

Are you seeing specific issues with it?

**Comment by iAn-Pinto** [comment]
I get the following error: XMLHttpRequest cannot load https://api-iam.intercom.io/ping. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://localhost:8100' is therefore not allowed access. The credentials mode of an XMLHttpRequest is controlled by the withCredentials attribute.

**Comment by jtreanor** [comment]
It looks like you may be using our web Messenger and not the Cordova plugin. Did you install it with `cordova plugin add cordova-plugin-intercom`?
There are usage instructions on the [readme](https://github.com/intercom/intercom-cordova/blob/master/README.md).
