### ISSUE TITLE
Android runtime exception

### ISSUE THREAD

**Issue by yankopetrov** [intercom/intercom-cordova#109]
I tried the latest Intercom for Cordova/PhoneGap version: __3.0.15__, and my application build successful. But when run in on device the application crash with message "Unfortunately, MyApp has stopped."

I am using Android 7.0. 
__Android Support Repository__ and __Google repository__ are up to day.

When i run `adb logcat > logcat.txt` there was __FATAL EXCEPTION: IntentService[Intercom GCM Registration Service]__

### Logcat

```java
11-02 11:35:18.011 28328 28415 E AndroidRuntime: FATAL EXCEPTION: IntentService[Intercom GCM Registration Service]
11-02 11:35:18.011 28328 28415 E AndroidRuntime: Process: com.app.my, PID: 28328
11-02 11:35:18.011 28328 28415 E AndroidRuntime: java.lang.NoSuchMethodError: No static method getNoBackupFilesDir(Landroid/content/Context;)Ljava/io/File; in class Lcom/google/android/gms/common/util/zzx; or its super classes (declaration of 'com.google.android.gms.common.util.zzx' appears in /data/app/com.app.my-1/base.apk)
11-02 11:35:18.011 28328 28415 E AndroidRuntime: 	at com.google.android.gms.iid.zzd.zzkf(Unknown Source)
11-02 11:35:18.011 28328 28415 E AndroidRuntime: 	at com.google.android.gms.iid.zzd.<init>(Unknown Source)
11-02 11:35:18.011 28328 28415 E AndroidRuntime: 	at com.google.android.gms.iid.zzd.<init>(Unknown Source)
11-02 11:35:18.011 28328 28415 E AndroidRuntime: 	at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
11-02 11:35:18.011 28328 28415 E AndroidRuntime: 	at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
11-02 11:35:18.011 28328 28415 E AndroidRuntime: 	at io.intercom.android.sdk.gcm.IntercomGcmRegistrationService.onHandleIntent(IntercomGcmRegistrationService.java:25)
11-02 11:35:18.011 28328 28415 E AndroidRuntime: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
11-02 11:35:18.011 28328 28415 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-02 11:35:18.011 28328 28415 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:158)
11-02 11:35:18.011 28328 28415 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
```
Is it some conflict with my other plugins or only intercom related?

### My plugins list:
- cordova-plugin-whitelist 1
- cordova-plugin-inappbrowser ~1.4.0
- cordova-plugin-geolocation ~2.2.0
- cordova-plugin-calendar ~4.5.1
- cordova-plugin-sim ~1.2.1
- cordova-plugin-network-information ~1.2.1
- cordova-plugin-google-analytics ~1.0.0
- cordova-plugin-intercom ~3.0.15
- cordova-plugin-statusbar ~2.2.0
- cordova-plugin-facebook4 ~1.7.3
- cordova-plugin-device ~1.1.3

For now i just downgrade to __3.0.12__.

**Comment by ronocod** [comment]
3.0.15 and 3.0.12 use the same version of our Android SDK, so the Android code should be identical in each version. I think this issue could be related to your build setup. What device did you see the crash on?

**Comment by yankopetrov** [comment]
Here are my device settings from __cordova-plugin-device__

```
available: true
cordova: "5.1.1"
isVirtual: false
manufacturer: "samsung"
model: "SM-G920F"
platform: "Android"
serial: -
uuid: -
version: "6.0.1"
```

**Comment by ronocod** [comment]
Can you try updating to a newer Cordova version? It should have better support for Android build tools

**Comment by yankopetrov** [comment]
Cordova updated to __v6.4.0__ and still the application crash. Also i tried to update all plugins and platforms and to create new app, but the behavior is the same.

### Steps to simulate:
- cordova create MyApp 
- cd MyApp
- update config.xml (Update intercom KEY)
```
<?xml version='1.0' encoding='utf-8'?>
<widget id="io.cordova.hellocordova" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>HelloCordova</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <preference name="intercom-app-id" value="KEY" />
    <preference name="intercom-ios-api-key" value="ios_sdk-KEY" />
    <preference name="intercom-android-api-key" value="android_sdk-KEY" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <engine name="ios" spec="~4.3.0" />
    <engine name="android" spec="~6.0.0" />
    <plugin name="cordova-plugin-intercom" spec="~3.0.15" />
    <plugin name="cordova-plugin-inappbrowser" spec="~1.5.0" />
    <plugin name="cordova-plugin-geolocation" spec="~2.4.0" />
    <plugin name="cordova-plugin-calendar" spec="~4.5.5" />
    <plugin name="cordova-plugin-sim" spec="~1.3.0" />
    <plugin name="cordova-plugin-network-information" spec="~1.3.0" />
    <plugin name="cordova-plugin-google-analytics" spec="~1.6.0" />
    <plugin name="cordova-plugin-device" spec="~1.1.3" />
</widget>
```
- cordova prepare
- cordova run android --device

**Comment by ronocod** [comment]
Can you try updating Cordova Android to 6.1.0 which was released this week? https://github.com/apache/cordova-android/blob/master/RELEASENOTES.md
Based on your config.xml it looks like you're using 6.0.0

**Comment by yankopetrov** [comment]
`cordova platform add android` install 6.0.0

When i try `cordova platform add android@6.1.0` i get an error
```
Error: Failed to fetch platform android@6.1.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: version not found: cordova-android@6.1.0
```

**Comment by ronocod** [comment]
Ah my mistake, 6.1.0 is in the release notes but doesn't seem to be available yet. I'll investigate this further.

**Comment by yankopetrov** [comment]
When i remove `<preference name="intercom-android-api-key" value="android_sdk-KEY" />` the application start. Of course i can't use intercom without api key, but the application start. I hope this help somehow.

**Comment by ronocod** [comment]
Can you try this with version 3.0.16? It may fix your issue

**Comment by ronocod** [comment]
Can you try this with version 3.0.16? It may fix your issue.

**Comment by yankopetrov** [comment]
Yes, 3.0.16 solve my problem. Thank you.
