### ISSUE TITLE
intercom is not defined Ionic 2

### ISSUE THREAD

**Issue by allanbarbosa** [intercom/intercom-cordova#113]
Hello,

I'm trying to integrate the intercom cordova puglin on my ionic 2 app. When i using the intercom to show de conversation list, the app shows me that intercom variable is not defined.

## Version info
  - Intercom for Cordova/PhoneGap version: 3.0.15

This is the error that show on console: ORIGINAL EXCEPTION: intercom is not defined

On below has a part of the code that i'm using the intercom.

```typescript
import { Component } from '@angular/core';
import { ViewController } from 'ionic-angular';
import { NavController } from "ionic-angular/index";

import { LoginComponente } from "../login/login";

declare var intercom: any;

@Component({
    templateUrl: 'modal-account.html',
})
export class ModalAccount{

    constructor(private viewController: ViewController, private navCtrl: NavController){
    }

    dismiss(data){
        this.viewController.dismiss(data);
    }

    logout(){
        localStorage.clear();
        this.navCtrl.setRoot(LoginComponente);
    }

    helpIntercom(){
        intercom.displayConversationsList();
    }

}
```

Can someone help me? There is something that i'm forget?

**Comment by ronocod** [comment]
Hi, does this work if you remove the `declare var intercom: any;` line?

**Comment by allanbarbosa** [comment]
Hi, No. Does not work. Shows another error. "Cannot find name 'intercom'"

**Comment by ronocod** [comment]
Have you run `ionic plugin add cordova-plugin-intercom`?

**Comment by allanbarbosa** [comment]
Yes. I run.

**Comment by thebasix** [comment]
Any solution?

**Comment by allanbarbosa** [comment]
Oh Yeah.
I was tried to execute on web the intercom, but when i execute on iPhone emulator, it's works.

Thank you so much for you help.

**Comment by thebasix** [comment]
I dont understand what you are saying.

Can you share some code? How do you call Intercom plugin? How do initialize it?

**Comment by allanbarbosa** [comment]
I don't change much of the code on the previous comment. Only change where i was testing the app. I was first testing the app on web view, in this case the error shows up. But when i execute on emulator testing, the intercom execute.

Sorry for my bad english.
