### ISSUE TITLE
Setting an event like onHide?

### ISSUE THREAD

**Issue by oggyindahouse** [intercom/intercom-cordova#116]
Hello,

I have a question regarding methods in Cordova/Phonegap plugin. 

When user closes the messenger by clicking "x", i need to know this. Can I somehow set an event listener like "onHide" ?

**Comment by bboyle18** [comment]
Hi @oggyindahouse 👋 

Thanks for getting in touch.
We don't currently have this feature, but I'll add it as a feature request and we will consider implementing it for a future release, if its possible.

Thanks

Brian
