### ISSUE TITLE
iOS push notification doesn't open conversation list

### ISSUE THREAD

**Issue by steaks** [intercom/intercom-cordova#12]
We notice that tapping the push notification opens the app but doesn't open the conversation list (nor the message composer).  We're able to recreate this consistently.

This works on Android.

Any help would be appreciated.  Thanks!

**Comment by Anu2g** [comment]
+1

**Comment by jtreanor** [comment]
Thanks @steaks and @Anu2g.

After discussion in Intercom, we found that this is an issue with Intercom for iOS. When you have called `intercom.setVisibility(intercom.GONE)` push notifications will not open the conversation.

We will be fixing this in our next release.

**Comment by jtreanor** [comment]
This has been fixed in version 1.0.8. Sorry about the delay on this.
