### ISSUE TITLE
New message not displaying from push notification - Android

### ISSUE THREAD

**Issue by tcpickard94** [intercom/intercom-cordova#120]
## Version info
  - Intercom for Cordova/PhoneGap version: 3.0.18
  - iOS/Android OS version: 5.1.1

I am having this exact issue solely for Android devices https://github.com/intercom/intercom-ios/issues/79

**Comment by ronocod** [comment]
Can you try sending another message to the conversation after you've opened it from the push notification? Knowing what happens then will help debug this.

**Comment by tcpickard94** [comment]
A message from the customer or from the intercom user?

**Comment by tcpickard94** [comment]
Sending another message when the customers intercom screen is open, the screen updates correctly displaying both messages (the one from the push notification that wasn't displaying before and the new message).

**Comment by ronocod** [comment]
We're currently investigating this, I'll post an update here when I know more.

**Comment by ronocod** [comment]
Sorry for the delay with the update here, there's a fix for this in version 3.0.23.

**Comment by tcpickard94** [comment]
No problem. Thank you for your help
