### ISSUE TITLE
How to implement Intercom inside Ionic2 app?

### ISSUE THREAD

**Issue by thebasix** [intercom/intercom-cordova#125]
How do I even start using Intercom inside Ionic2 app?

I installed the plugin and added this code in app.component.ts

```
    platform.ready().then(() => {(
          (<any>window).plugins.intercom.registerIdentifiedUser({userId: "1"});
          (<any>window).plugins.intercom.setLauncherVisibility('VISIBLE');
          (<any>window).plugins.intercom.setInAppMessageVisibility('VISIBLE');
          (<any>window).plugins.intercom.setPreviewPosition((<any>window).plugins.intercom.BOTTOM_RIGHT);
        });
```

Am I suppose to see Intercom bubble? User activity doesnt change inside Intercom dashboard so I would assume none of these works. I would appreciate any help.

**Comment by ronocod** [comment]
We're looking into Ionic 2 integration, we'll post an update here when we have one.

**Comment by bboyle18** [comment]
Hi @thebasix 👋 

Apologies in the delay getting back to you.
We've just release v3.0.23 (https://github.com/intercom/intercom-cordova/releases/tag/3.0.23) which has support for Ionic 2.
Heres how you use it.

After your imports, declare the following variable:
`declare var cordova:any;`

Then add your code as follows:
```
cordova.plugins.intercom.registerIdentifiedUser({userId: "1"});
cordova.plugins.intercom.setLauncherVisibility('VISIBLE');
cordova.plugins.intercom.setInAppMessageVisibility('VISIBLE');
cordova.plugins.intercom.setPreviewPosition(cordova.plugins.intercom.BOTTOM_RIGHT);```

Please let me know how you get on.

Cheers,

Brian

**Comment by duelingbanjos** [comment]
hi there,

I have been looking around for resources on this, is there a pre-built UI available for ionic or is it up to the app designer to create that ? 

Thanks !

**Comment by bboyle18** [comment]
HI @duelingbanjos 
What do you mean by a `pre-built UI`? A UI for Intercom?

Brian
