### ISSUE TITLE
Plugin doesn't support cordova-android version 4.0.0-dev

### ISSUE THREAD

**Issue by Mishit07** [intercom/intercom-cordova#13]
Fetching plugin "https://github.com/intercom/intercom-cordova" via git clone
Installing "cordova-plugin-intercom" for android
Failed to install 'cordova-plugin-intercom':CordovaError: Plugin doesn't support this project's cordova-android version. cordova-android: 4.0.0-dev, failed version requirement: >=4.0.0
    at checkEngines (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:116:29)
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)

**Comment by Mishit07** [comment]
I am trying to install this plugin with ionic framework. I am keeping getting error for cordova-android version mismatch.

**Comment by jtreanor** [comment]
Hi @Mishit07,

The minimum version required for our Android integration is Cordova 4.0.0. Is there a reason why you are using 4.0.0-dev, and not 4.0.0?

**Comment by Mishit07** [comment]
Thanks James. I updated the android platform and its not throwing that error anymore.
Thanks.
