### ISSUE TITLE
Support for Firebase Cloud Messaging (FCM)

### ISSUE THREAD

**Issue by HackMate** [intercom/intercom-cordova#133]
New apps can no longer use [GCM](
https://developers.google.com/cloud-messaging/) for messaging but instead have to use Firebase. The [intercom-android](https://github.com/intercom/intercom-android) API already supports it.

Will support be added to the cordova plugin as well?

**Comment by bboyle18** [comment]
Hi @HackMate 👋 

Thanks for getting in touch.
Adding FCM support for Cordova is on our roadmap, but we don't have a definitive timeline for it yet.

We've noted this as a feature request so please keep an eye on our future releases for Cordova.

Thanks

Brian

**Comment by harpster604** [comment]
@bboyle18 Any updates on this? How are we supposed to support push notifications for a new Ionic/Cordova app at this point? Intercom Engage isn't that useful if our users aren't able to see that they have a new message from the app.

Thanks

**Comment by jtreanor** [comment]
Hi @HackMate,

Just a quick update here. Version [3.1.0](https://github.com/intercom/intercom-cordova/releases/tag/3.1.0) has just been release with FCM support.

To enable FCM, simply copy your `google-services.json` file into the project's root and add this line to your `config.xml`:
```
<preference name="intercom-android-push-type" value="FCM"/>
```
