### ISSUE TITLE
iOS is not opening the conversations 

### ISSUE THREAD

**Issue by emc2spider** [intercom/intercom-cordova#136]
I have noticed on my testing environment that the intercom window is not working, we only show them on specific places of the app when the user taps on a 'Live Chat' button we have available for them which then uses the `intercom.displayMessenger();` function. This seems to be working alright in Android.

## Version info
  - Intercom for Cordova/PhoneGap version: 3.0.24
  - Cordova version: 6.4.0
  - Cordova iOS/Android version: iOS 4.2.1
  - iOS/Android OS version: iOS 10.2
  - iOS/Android Device: iPhone 5

## Expected behavior
User goes to the help page and taps on the 'Live Chat' button => Intercom conversation is shown.

## Actual behavior
User goes to the help page and taps on the 'Live Chat' button => Screen seems to blink a bit sometimes but nothing happens, js console debugging logs show nothing on Safari but I've attached the device logs.

## Steps to reproduce
 1. Load the webview with a 'chat' button
 2. Button action includes `intercom.registerIdentifiedUser();` and `intercom.displayMessenger();` functions.
 3. Tap on the button.
 4. Conversation should open, sadly in my case this is not happening :(

## Logs
(see attached)
[ios_logs.txt](https://github.com/intercom/intercom-cordova/files/719133/ios_logs.txt)

**Comment by bboyle18** [comment]
Hi @emc2spider 👋 

Thanks for getting in touch and thanks for providing a detailed issue report 😄 
Can you please attach a screenshot of what you are seeing when you open Intercom?

Thanks

Brian

**Comment by bboyle18** [comment]
@emc2spider when you say that you are calling `intercom.registerIdentifiedUser();`, is this the exact code you are calling?
This function requires a parameter of a userId of some sort. If you look at our [sample app](https://github.com/intercom/intercom-cordova/tree/master/Example) theres an example of how to use this function `intercom.registerIdentifiedUser({email: emailAddress});` 
https://github.com/intercom/intercom-cordova/blob/master/Example/www/js/index.js#L77

**Comment by emc2spider** [comment]
Hi @bboyle18,

I am aware of the parameters, the actual code looks like this:
```
        intercom.registerIdentifiedUser({
            email: Properties.userGet("email"),
            name: Properties.userGet("nickname"),
            user_type: user_type
        });
```

**Comment by bboyle18** [comment]
Thanks!
Can you provide me with a screenshot of what you see on Intercom when you open it?

Brian

**Comment by emc2spider** [comment]
It doesn't. That's the problem! I can get a screenshot of the working Android version?

**Comment by bboyle18** [comment]
Ok I think I understand now. So calling `Intercom.presentMessenger()` does nothing?

**Comment by emc2spider** [comment]
Well, I was using `intercom.displayConversationsList();` but changed it to `intercom.displayMessenger();` to double check and still nothing happens. `intercom.presentMessenger();` throws a *"... is not a function."* exception.

**Comment by emc2spider** [comment]
Should I be using `intercom` or `Intercom`? I think I've never used it with caps ON, will test now.

**Comment by bboyle18** [comment]
It should be `intercom` that you are using. If you have a look at our sample app and see how we register users and open the messenger from there. https://github.com/intercom/intercom-cordova/tree/master/Example

Brian

**Comment by emc2spider** [comment]
The thing is that it was working before, actually the version we have already on production currently works.
But my testing version is for some reason broken, I noticed yesterday so at least since then. I even uninstalled and reinstalled the plugin to check if it might be a problem with an XCode update or something, but it didn't help.
And since I need to submit an update to my app I don't want to fix a problem at the expense of breaking another thing (a.k.a. live chat through Intercom).

**Comment by bboyle18** [comment]
What version of the Intercom Cordova plugin are you running in production?

**Comment by emc2spider** [comment]
3.0.18 should I roll-back?

**Comment by emc2spider** [comment]
I upgraded it on the reinstall I did this morning, afaicr.

**Comment by bboyle18** [comment]
@emc2spider Yeah it might be worth rolling back to 3.0.18 just to try it.
There hasn't been any changes since then that would impact it, but it would certainly help to rule this out.

Let me know how you get on.
Brian

**Comment by emc2spider** [comment]
Ok, I must be overlooking something very obvious here, but this is not working :( 
I'm going to upgrade everything (Cordova platforms, base plugins, the whole thing) and take it from there. I'm closing this as it will not be relevant anymore. If it comes to it not working again I'll open a new one.

@bboyle18 thank you very much for your time and patience in trying to help me.

E.

**Comment by bboyle18** [comment]
No problem @emc2spider, I hope you get it sorted.
If not, we're here to help 👍

**Comment by emc2spider** [comment]
@bboyle18 one of my colleagues ended up solving it, apparently calling `registerIdentifiedUser` and   `displayMessenger` causes that the second one is not processed properly for whatever reason I didn't quite figure out. We ended up adding a timeout for the second function and it just worked!
