### ISSUE TITLE
Push notification received twice on android

### ISSUE THREAD

**Issue by JumBay** [intercom/intercom-cordova#139]
## Version info
  - Intercom for Cordova/PhoneGap version: **3.0.26**
  - iOS/Android OS version: **7.1.1** and **6.0**
  - iOS/Android Device: **Nexus 5** and **LG G4** 
```
cordova platform ls
Installed platforms:
  android 6.1.2
  ios 4.3.1 
```

## Expected behavior

When I use the plugin [cordova-plugin-firebase](https://github.com/arnesson/cordova-plugin-firebase) with intercom plugin, I receive push notifications twice on Android (when the app is in background).

## Actual behavior
Do not display notification twice

## Steps to reproduce
 1. Create new cordova project: `cordova create test` 
 2. Add android platform: `cordova platform add android`
 3. Install and [configure](https://github.com/arnesson/cordova-plugin-firebase#installation) both plugins: `cordova plugin add cordova-plugin-intercom --save && cordova plugin add cordova-plugin-firebase@0.1.19 --save`
4. Install the app on an android device, run it, close it and send a notification. 2 will show up.

**Comment by DaleCantwell** [comment]
Hi @JumBay, we currently don't support FCM in Cordova. We are looking into solutions to this. Could you confirm for me, is it Intercom push messages you are seeing duplicated or the apps push messages?

**Comment by JumBay** [comment]
Hi @DaleCantwell. 

It's the apps push messages that are showed twice. The intercom notifications work great.

Then I'll use another plugin in the meanwhile. 

Thx

**Comment by DaleCantwell** [comment]
If you remove Intercom from the project are you only seeing one push? Our receiver does not consume non Intercom push messages.

**Comment by JumBay** [comment]
Yes if I remove Intercom from the project with `cordova plugin rm cordova-plugin-intercom` then I'm only seeing one push

**Comment by DaleCantwell** [comment]
Thanks @JumBay do you have screenshot of the two push messages on device? Are they being styled the very same?

**Comment by JumBay** [comment]
Yes they both look like the same as you can see: 
![screenshot_20170201-191319](https://cloud.githubusercontent.com/assets/216573/22519997/e4391ddc-e8b2-11e6-9cd4-45d1ac4d0375.png)

If the app is in foreground, I don't have the issue, the event is fire only once with the notification detail.

**Comment by skylerwshaw** [comment]
Hey @JumBay, we don't currently support using multiple push providers in the Cordova SDK plugin as mentioned in https://github.com/intercom/intercom-cordova/issues/139#issuecomment-276698378. We're definitely looking into supporting this such that push isn't handled by both us and [cordova-plugin-firebase](https://github.com/arnesson/cordova-plugin-firebase). We'll post back here when it's released. 👍

**Comment by harpster604** [comment]
@skylerwshaw was this resolved when using Firebase? I just set up phonegap-plugin-push using firebase on an Ionic app that already had intercom-cordova configured. Now I receive 2 duplicate notifications for any firebase messages but messages sent through intercom only appear correctly (only once).
