### ISSUE TITLE
registerIdentifiedUser and network problems

### ISSUE THREAD

**Issue by PRotig** [intercom/intercom-cordova#141]
Hello guys, I am stuck in the intercom plugin install for my **IONIC v1** app.... it doesn't want to work and I don't understand why. Hoping it is compatible...
I'm having two issues but don't know if it is related so I put the both here to help solving my problems :(

## Version info
My system information: (ionic info)

Cordova CLI: 6.5.0
Gulp version:  CLI version 1.2.2
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
ios-deploy version: 1.8.2 
ios-sim version: 5.0.1 
OS: Mac OS X El Capitan
Node Version: v4.3.1
Xcode version: Xcode 8.2.1 Build version 8C1002

  - cordova-plugin-intercom 3.0.26 "Intercom"
  - iOS/Android OS version: iOs 8.0
  - iOS/Android Device: Iphone 5S

## Expected behavior
At login, the user is identified for intercom (intercom.registerIdentifiedUser({userId: user.id});
The user can enter in/leave the intercom messenger and enter again in it to follow conversations.
The user can talk with one of my operator.

## Actual behavior
**First problem :** 
At login, the command intercom.registerIdentifiedUser({userId: String(user.id)}) shoot a bug and kill the app (cf logs - #First Problem)
**Second problem :**
The user can open intercom messenger (which is by the way so cool, nice and handy...), the user can write a message, and chat with one of my operator but as soon as he quits the messenger and re-open it, the messenger won't work. I suppose a network connection (cf logs - #Second Problem).

## Steps to reproduce
**First Problem**
 1. Launch the app
 2. Login => CRASH 
 
**Second Problem**
 1. Launch the app
 2. Login
 3. Clic the intercom messenger with the command : intercom.displayMessenger()
 4. Chat with an operator
 5. Leave the messenger (or multiple times) => Not working anymore.. Network problems... For info, I removed my content-policy meta.. aswell.

## Logs
**First Problem**
2017-02-13 10:18:51.753 Quatre Epingles[816:349637] -[NSNull stringByTrimmingCharactersInSet:]: unrecognized selector sent to instance 0x19fd1f490
2017-02-13 10:18:51.758 Quatre Epingles[816:349637] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull stringByTrimmingCharactersInSet:]: unrecognized selector sent to instance 0x19fd1f490'
*** First throw call stack:
(0x181d7edb0 0x1813e3f80 0x181d85c4c 0x181d82bec 0x181c80c5c 0x1000f5cd8 0x1001095ec 0x100121df8 0x1001216ec 0x182746658 0x181d35794 0x181d35438 0x181d32b4c 0x181c5cc50 0x183544088 0x186f4a088 0x100045ca4 0x1817fa8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Second Problem**
[Intercom] ERROR - Tried to get conversation detail but there was a network error (401) - Request failed: unauthorized (401)
[Intercom] ERROR - Tried to get conversations for display in the conversations list but there was a network error (401) - Request failed: unauthorized (401)
[Intercom] ERROR - Tried to update user but there was a network error (401) - Request failed: unauthorized (401)

**Comment by bboyle18** [comment]
Hi @PRotig 👋 
Thanks for getting in touch.

**First Problem**
Can you check that `user.id` is not null?

**Second Problem**
This looks like you have not set your API key and your AppId correctly. In our Cordova/Phonegap plugin you set these in your `config.xml`. See [here](https://developers.intercom.com/docs/cordova-phonegap-installation). I'm not 100% sure but I think Ionic 1 uses the same `config.xml`.

Let me know if this fixes your problem.

Thanks

Brian

**Comment by PRotig** [comment]
Hi @bboyle18 , Thanks a lot for this fast answer !

Yes, the user.id is not null, it's an integer. Should I pass the value as a string ?

For the second problem, you **maybe** find the solution :
Previously : `<preference name="intercom-app-id" value="eq2nissz"></preference>`
Now : `<preference name="intercom-app-id" value="eq2nissz" />`

After this little change, I didn't meet the connexion problem anymore (i've just tested it a couple a times)

**But I don't know if my problem are fixed.**

A curious problem I've just discovered concerning the problem I was talking about in xcode : 
The xcode bug happens just when I launch the app thought xcode.. and the registeredUserId is uncommented in my signin function !!!
When I'm unplugged my iphone out my mac, and launch the app, the problem disappears... 
It's a mystery...

Again, I don't know if it is related to the intercom installation.

Thanks a lot for your advices, we so want to use Intercom at Quatre Epingles ...

**Comment by PRotig** [comment]
By the way, do you have any recommendation for the meta content policy strategy ?
Before trying to install Intercom, I had :
`meta(http-equiv="Content-Security-Policy" content="script-src 'self' http://static.hotjar.com/ https://static.hotjar.com/ https://script.hotjar.com/ https://maps.googleapis.com/ https://maps.gstatic.com/ https://mts0.googleapis.com/ https://cdn.branch.io https://api.branch.io http://links.quatreepingles.fr https://www.google-analytics.com/ 'unsafe-inline' 'unsafe-eval'")`

**Comment by skylerwshaw** [comment]
Hi @PRotig, `user_id` must be sent as a string. Here's our documentation demonstrating this:
https://developers.intercom.com/docs/cordova-phonegap-installation#section-register-your-logged-in-users

To address your latest comment, CSP policy in Cordova only applies to plugins that use webviews. The Intercom Cordova plugin does not.
Reference: https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/

Feel free to start a conversation with us from your Intercom dashboard or by emailing team@intercom.com if you have any non-bug configuration questions. Happy to help out!
