### ISSUE TITLE
App crashing with plugin in Ionic

### ISSUE THREAD

**Issue by hackeo1** [intercom/intercom-cordova#142]
## Version info
  - Intercom for Cordova/PhoneGap version: 3.0.26
  - Ionic version: 1.7.16
  - Cordova version: 6.5.0
  - Android Cordova version: 6.1.2 (tested with 5.2.2 as well)
  - iOS/Android OS version: 5.1
  - iOS/Android Device: Nexus 5
  - min target version: 16

## Expected behavior

The app opens with chat plugin.

## Actual behavior

The app crashes while opening. If I uninstall the cordova-plugin-intercom the app opens normally.

I don't have anything related to push notifications.

## Steps to reproduce
 1. install plugin using ionic: ionic plugin add cordova-plugin-intercom --save
 2. add the api keys in the config.xml
    <preference name="intercom-app-id" value="MY_ID" />
    <preference name="intercom-ios-api-key" value="ios_sdk-MY_KEY" />
    <preference name="intercom-android-api-key" value="android_sdk-MY_KEY" />
 3. build the app: ionic build android
 4. install the app in the device
 5. open app
 6. the app crashes and it shows a message saying 'unfortunately, MY_APP_NAME has stopped.' 

## Logs

```
--------- beginning of crash
E/AndroidRuntime( 8769): FATAL EXCEPTION: IntentService[Intercom GCM Registration Service]
E/AndroidRuntime( 8769): Process: app-id, PID: 8769
E/AndroidRuntime( 8769): java.lang.NoSuchMethodError: No static method getNoBackupFilesDir(Landroid/content/Context;)Ljava/io/File; in class Lcom/google/android/gms/common/util/zzw; or its super classes (declaration of 'com.google.android.gms.common.util.zzw' appears in /data/app/app-id-1/base.apk)
E/AndroidRuntime( 8769): 	at com.google.android.gms.iid.zzd.zzkq(Unknown Source)
E/AndroidRuntime( 8769): 	at com.google.android.gms.iid.zzd.<init>(Unknown Source)
E/AndroidRuntime( 8769): 	at com.google.android.gms.iid.zzd.<init>(Unknown Source)
E/AndroidRuntime( 8769): 	at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
E/AndroidRuntime( 8769): 	at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
E/AndroidRuntime( 8769): 	at io.intercom.android.sdk.gcm.IntercomGcmRegistrationService.onHandleIntent(IntercomGcmRegistrationService.java:25)
E/AndroidRuntime( 8769): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/AndroidRuntime( 8769): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 8769): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 8769): 	at android.os.HandlerThread.run(HandlerThread.java:61)
I/OpenGLRenderer( 8769): Initialized EGL, version 1.4
D/OpenGLRenderer( 8769): Enabling debug mode 0
```

## Comments

It seems the same [problem (109)](https://github.com/intercom/intercom-cordova/issues/109).
I delete the android key from the config.xml and it works. but I have the version v3.0.26 and it doesn't work.

**Comment by cg50x** [comment]
I'm seeing the exact same thing. Here's my info:

## Version Info
* Intercom for Cordova/PhoneGap version: 3.0.25
* Cordova version: 6.3.1
* Android Cordova version: 5.2.2
* iOS/Android OS version: 4.4
* iOS/Android Device: Samsung Galaxy S5
* min target version: 19

## Comments
I noticed this problem happened after I upgraded to the following packages:
* Android Support Repository rev. 44
* Google Repository rev. 44

It was working previously when I had these packages:
* Android Support Repository rev. 41
* Google Repository rev. 42

Hope this helps.

**Comment by hackeo1** [comment]
thanks, I'll check in changing the google repository version helps

**Comment by Lindstream** [comment]
Workaround, only use the base sdk - dropping push messages.

In _/src/android/intercom.gradle_ change
`compile 'io.intercom.android:intercom-sdk:3.0.20'`
to:
`compile 'io.intercom.android:intercom-sdk-base:3.+'`

As the IntercomBrigde has an contidional GCM implementation it will just skip setting it up if the lib isn't present. FCM isn't implemented in the cordova plug.

**Comment by jtreanor** [comment]
@Lindstream just a quick update here. Version [3.1.0](https://github.com/intercom/intercom-cordova/releases/tag/3.1.0) has just been released with FCM support.

To enable FCM, simply copy your `google-services.json` file into the project's root and add this line to your `config.xml`:
```
<preference name="intercom-android-push-type" value="FCM"/>
```

Please let us know if this resolves your problem 😄

**Comment by hackeo1** [comment]
I'm not using push notifications, is there any preference to value to do this? @jtreanor

**Comment by jtreanor** [comment]
That's great. Thanks @hackeo1!
