### ISSUE TITLE
Intercom is not defined

### ISSUE THREAD

**Issue by Cleysonlb** [intercom/intercom-cordova#143]
Hey Guys, I have a problem using the intercom in ionic, I followed the steps of the site but without much success, someone has already gone through this or know how to solve ?! Thanks!!

**Comment by bboyle18** [comment]
Hi @Cleysonlb  👋 

Have you [followed the steps](https://github.com/intercom/intercom-cordova#ionic-2) for using the plugin with Ionic?

Cheers

Brian

**Comment by Cleysonlb** [comment]
Hey @bboyle18 thanks!! But, I using IONIC v1, These steps also serve for the V1 of Ionic?

**Comment by bboyle18** [comment]
Hi @Cleysonlb 
Apologies for the delay in getting back to you.
We don't officially support Ionic so we've only tested it with Ionic 2. Is it possible for you to use Ionic 2 instead?

Brian

**Comment by bboyle18** [comment]
Hi @Cleysonlb 👋 
I have tested the Intercom Cordova Plugin with Ionic 1 and it is fully compatible.
Here is an example code snippet of how you use Intercom:
```
.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {
    cordova.plugins.intercom.registerIdentifiedUser({userId: "123456"});
    cordova.plugins.intercom.setLauncherVisibility('VISIBLE');
  });
})
```
Note the need to use `cordova.plugins.intercom`.

Please let me know if this helps.

Brian

**Comment by Cleysonlb** [comment]
Hey @bboyle18 thank you, I was able to use the intercom in my project!! 💃

**Comment by bboyle18** [comment]
@Cleysonlb 🎉  💪
