### ISSUE TITLE
Intercom do not load and do not launch errors... ON ANDROID

### ISSUE THREAD

**Issue by PRotig** [intercom/intercom-cordova#144]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
ionic info

Your system information:

Cordova CLI: 6.5.0
Gulp version:  CLI version 1.2.2
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
ios-deploy version: 1.9.1 
ios-sim version: 5.0.1 
OS: Mac OS X El Capitan
Node Version: v4.3.1
Xcode version: Xcode 8.2.1 Build version 8C1002 
Android Device : One Plus
Gradle Version : v3.4.1
Cordova 6.5.0

## Expected behavior
At startup, the app should log the user 
```
intercom.registerIdentifiedUser({"userId": String(user.id), "email": user.mail});
intercom.registerUnidentifiedUser()
```
The Intercom messenger should be visible.
`intercom.setLauncherVisibility('VISIBLE')`
The intercom messenger should open
`intercom.displayMessenger()`

## Actual behavior
Nothing happens :( on Android. (Work well on ios =)

## Steps to reproduce
 1. Open the app
 2. Login a correct user
 3. Click on a specific button to open the messenger.

**Comment by bboyle18** [comment]
Hi @PRotig 👋 
Thanks for getting in touch.

Are there any errors showing up in the JS console that might indicate theres a problem? 
Can you send us on any logs you have from the console so we can help diagnose it?

Thanks

Brian

**Comment by PRotig** [comment]
Unfortunately, nothing in the js console....
I looking in the android log ("logcat")
I don't know what to do... But I absolutely need to work with android !

**Comment by bboyle18** [comment]
Ok, thanks for checking.
Can you debug your code and check that the `intercom` variable is defined? 

Brian

**Comment by bboyle18** [comment]
@PRotig Can you also tell me if you are using Ionic 1 for this? I can see in your system info your provided your specified `Ionic Framework Version: 1.3.1`

**Comment by PRotig** [comment]
Yes, I am using Ionic 1. Please tell me it is compatible...

**Comment by bboyle18** [comment]
We don't officially support it because we've never tested it with Ionic 1, only Ionic 2.
My understanding is that its working ok for iOS using Ionic 1 but not Android?

**Comment by bboyle18** [comment]
Hi @PRotig 
I tested Intercom with Ionic 1 and it works fine on iOS and Android. 🎉 
If you have it working on iOS it means that your code is probably ok, but you need to check that you have it configured correctly for Android. In your `config.xml` make sure you have added 
```
<platform name="android">
.....
<preference name="intercom-app-id" value="YOUR_APP_ID"/>
<preference name="intercom-android-api-key" value="YOUR_ANDROID_API_KEY"/>
....
</platform>
```

Let me know how you get on.

Cheers

Brian

**Comment by jtreanor** [comment]
Closing since @bboyle18 has clarified ionic 1 compatibility.

@PRotig feel free to re-open if you are still having issues.

**Comment by PRotig** [comment]
Hello Guys, @bboyle18, @jtreanor,
Sorry for the delay, I wasn't available to test your advices/solutions ...
**Unfortunately, it is still not working...**

First of all, the "intercom" variable is well-populated :
`GONE : "GONE"
VISIBLE : "VISIBLE"
displayConversationsList : (success, error)
displayMessageComposer : (success, error)
displayMessageComposerWithInitialMessage : (initialMessage, success, error)
displayMessenger : (success, error) 
hideMessenger : (success, error)
logEvent : (eventName, metaData, success, error)
registerForPush : (success, error)
registerIdentifiedUser : (options, success, error)
registerUnidentifiedUser : (options, success, error)
reset : (success, error)
setInAppMessageVisibility : (visibility, success, error)
setLauncherVisibility : (visibility, success, error)
setSecureMode : (secureHash, secureData, success, error)
unreadConversationCount : (success, error)
updateUser : (attributes, success, error)`

**On Android Studio**, in logs, I have just discovered that when I click on my specific button which open the intercom-messenger, I am receiving : 

`03-13 16:22:56.427 22375-22751/fr.quatreepingles.app D/CordovaBridge: Ignoring exec() from previous page load.
03-13 16:22:56.494 22375-22375/fr.quatreepingles.app E/chromium: [ERROR:xwalk_autofill_client.cc(121)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()
`03-13 16:22:56.496 22375-22375/fr.quatreepingles.app D/cr_Ime: [InputMethodManagerWrapper.java:56] isActive: true
03-13 16:22:56.496 22375-22375/fr.quatreepingles.app D/cr_Ime: [InputMethodManagerWrapper.java:65] hideSoftInputFromWindow`

Maybe, the "EXEC" problem in the solution no ?

It is so frustrating .... :(
I'm crossing my fingers, if in few days, I can't make it working, I will have to decline the intercom solution which I love so much... I'm sure you will understand I won't change ionic 1 to ionic 2 just because I can't make Intercom plugin working :(

**Comment by PRotig** [comment]
Thanks for the re-opening !
Do you have new ideas ?
I think the `CordovaBridge: Ignoring exec()` is a good way to looking into...
Btw, the `XWalkAutofillClient::OnFirstUserGestureObserved()` is so annoying... but I don't think it is coming from the intercom messenger.

**Comment by jtreanor** [comment]
@PRotig Thanks for the suggestions.
We have still not been able to reproduce this yet, but I'll have another look and let you know what I find.

**Comment by jtreanor** [comment]
@PRotig Are you using the latest version of the plugin (3.1.0)?

**Comment by PRotig** [comment]
Nope, the 3.0.26.
Updating and testing. 
Get back to you asap !

**Comment by PRotig** [comment]
Hello guys, 
So... Since the update. Impossible to build anymore :(...

**iOs** 

`ld: library not found for -lPods-Quatre Epingles
clang: error: linker command failed with exit code 1 (use -v to see invocation)`
I am looking into it... 


**Android :** 

`Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexIndexOverflowException: Cannot merge new index 66004 into a non-jumbo instruction!
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexIndexOverflowException: Cannot merge new index 66004 into a non-jumbo instruction!
    	at com.android.dx.merge.InstructionTransformer.jumboCheck(InstructionTransformer.java:109)
    	at com.android.dx.merge.InstructionTransformer.access$800(InstructionTransformer.java:26)
    	at com.android.dx.merge.InstructionTransformer$StringVisitor.visit(InstructionTransformer.java:72)
    	at com.android.dx.io.CodeReader.callVisit(CodeReader.java:114)
    	at com.android.dx.io.CodeReader.visitAll(CodeReader.java:89)
    	at com.android.dx.merge.InstructionTransformer.transform(InstructionTransformer.java:49)
    	at com.android.dx.merge.DexMerger.transformCode(DexMerger.java:842)
    	at com.android.dx.merge.DexMerger.transformMethods(DexMerger.java:813)
    	at com.android.dx.merge.DexMerger.transformClassData(DexMerger.java:786)
    	at com.android.dx.merge.DexMerger.transformClassDef(DexMerger.java:682)
    	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:542)
    	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
    	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
    	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
    	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
    	at com.android.dx.command.dexer.Main.run(Main.java:277)
    	at com.android.dx.command.dexer.Main.main(Main.java:245)
    	at com.android.dx.command.Main.main(Main.java:106)
    
:transformClassesWithDexForArmv7Debug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForArmv7Debug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED`

I am sure we can do it !!

**Comment by ronocod** [comment]
It looks like you've hit the DEX limit on Android, can you try using this plugin? https://www.npmjs.com/package/cordova-plugin-multidex

There's more information about this issue here: https://developer.android.com/studio/build/multidex.html

**Comment by PRotig** [comment]
Updating the intercom plugin to 3.1.0 had me to update for iOs my "pods" and for Android the "multidex" thing..
Ok so now the app is building well on iOs and Android :)
But, still not working on Android :(..........

Any thought .....?

**Comment by jtreanor** [comment]
Thanks for trying that out @PRotig.
I don't have any ideas for you right now but I will look again in the morning.

**Comment by PRotig** [comment]
Hello guys, @bboyle18 @jtreanor 
Nothing new here :( Tried several things but no success...
I'm pretty sure it is coming from the cordova exec() problem..

**Comment by PRotig** [comment]
Hello guys, @bboyle18 @jtreanor 
Any clues ?

**Comment by ronocod** [comment]
It looks like you're using Crosswalk, can you try this with a normal WebView? Searching Google for your log message `Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved ()` brought me to this StackOverflow answer: http://stackoverflow.com/a/41093134

**Comment by PRotig** [comment]
:1st_place_medal: 👍  :1st_place_medal: 
@ronocod @bboyle18 @jtreanor , guys, you are the best ! The problem was coming CROSSWALK....
So cool to have a serious customer service !
Thanks a lot.

**Comment by jtreanor** [comment]
Thats great @PRotig, I'm glad you were able to resolve this 😄
