### ISSUE TITLE
Plugin install error: pod: Command failed with exit code 1

### ISSUE THREAD

**Issue by snaptom** [intercom/intercom-cordova#146]
Hi,

When trying to install the plugin, I get the following error:

```
Failed to install 'cordova-plugin-intercom':Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/tomhp/Developer/snap/devops/demoTools/Health-Sim-App/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

Following this, I cannot compile the app, presumably as cocoapods has failed: 

```
clang: error: no such file or directory: '/Users/tomhp/Developer/snap/devops/demoTools/Health-Sim-App/platforms/ios/Pods/Target Support Files/Pods-HealthSim/Pods-HealthSim-dummy.m'
clang: error: no input files
```

Any help with this would be greatly appreciated.
Thanks a lot,
Tom.

## Version info
cocoapods installed: 1.2.0
Cordova CLI: 6.5.0
cordova-ios: 4.3.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: OS X El Capitan
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by jtreanor** [comment]
Hi @snaptom,

Can you try running `pod repo update` to make sure CocoaPods can find Intercom?

**Comment by snaptom** [comment]
Thanks @jtreanor, that did the trick. Closing.
