### ISSUE TITLE
Intercom do not load and do not launch errors... ON ANDROID

### ISSUE THREAD

**Issue by PRotig** [intercom/intercom-cordova#149]
#144 As you closed the issue, I CAN'T re-open it ....

Hello Guys, @bboyle18, @jtreanor,
Sorry for the delay, I wasn't available to test your advices/solutions ...

**Unfortunately, it is still not working...**

First of all, the "intercom" variable is well-populated :
`{GONE : "GONE" VISIBLE : "VISIBLE" displayConversationsList : (success, error) displayMessageComposer : (success, error) displayMessageComposerWithInitialMessage : (initialMessage, success, error) displayMessenger : (success, error) hideMessenger : (success, error) logEvent : (eventName, metaData, success, error) registerForPush : (success, error) registerIdentifiedUser : (options, success, error) registerUnidentifiedUser : (options, success, error) reset : (success, error) setInAppMessageVisibility : (visibility, success, error) setLauncherVisibility : (visibility, success, error) setSecureMode : (secureHash, secureData, success, error) unreadConversationCount : (success, error) updateUser : (attributes, success, error)}
`
On Android Studio, in logs, I have just discovered that when I click on my specific button which open the intercom-messenger, I am receiving :

```
03-13 16:22:56.427 22375-22751/fr.quatreepingles.app D/CordovaBridge: Ignoring exec() from previous page load. 
03-13 16:22:56.494 22375-22375/fr.quatreepingles.app E/chromium: [ERROR:xwalk_autofill_client.cc(121)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()
03-13 16:22:56.496 22375-22375/fr.quatreepingles.app D/cr_Ime: [InputMethodManagerWrapper.java:56] isActive: true
03-13 16:22:56.496 22375-22375/fr.quatreepingles.app D/cr_Ime: [InputMethodManagerWrapper.java:65] hideSoftInputFromWindow`

```
Maybe, the "EXEC" problem in the solution no ?

It is so frustrating .... :(
I'm crossing my fingers, if in few days, I can't make it working, I will have to decline the intercom solution which I love so much... I'm sure you will understand I won't change ionic 1 to ionic 2 just because I can't make Intercom plugin working :(

**Comment by jtreanor** [comment]
Hi @PRotig,

I have re-opened https://github.com/intercom/intercom-cordova/issues/144 so we can track it in one location.
