### ISSUE TITLE
Using the no_play_services branch from phonegap build

### ISSUE THREAD

**Issue by elliotstokes** [intercom/intercom-cordova#15]
I have finally had chance to look at our intercom integration again and have had success with the no_play_services branch mentioned ins issue #14. I want to build this from pgb. Is this version registered within npm at all?

**Comment by elliotstokes** [comment]
also I guess were going to need to reference your fork of push plugin as well.

**Comment by jtreanor** [comment]
Hi @elliotstokes,

Unfortunately PhoneGap Build currently doesn't work with [Gradle](http://community.phonegap.com/nitobi/topics/phonegap-build-does-not-support-gradle-builds), so you would have to use PhoneGap CLI.

The no_play_services branch is not on npm and we are not likely to put it there soon. You will have to reference git directly for both this and the PushPlugin fork.

**Comment by elliotstokes** [comment]
Ok not to worry. I have moved over to building locally now instead.

**Comment by elliotstokes** [comment]
It might be worth adding to the readme that these branches exist though (assuming they haven't been added already)

**Comment by jtreanor** [comment]
Thanks @elliotstokes, I will certainly be adding instructions to work around these issues.
