### ISSUE TITLE
App crashes on Android 4.4.2 when opening conversation

### ISSUE THREAD

**Issue by FabPey** [intercom/intercom-cordova#150]
## Version info
  - Intercom for Cordova/PhoneGap version: 3.1.0
  - Android OS version: 4.4.2
  - Android Device: HTC One mini 2 (only device we have with 4.4.2)

## Expected behavior
When tapping on a conversation in messenger, that conversation opens

## Actual behavior
App crashes when opening a conversation in Android 4.4.2 (plugin version 3.0.26 works)

## Steps to reproduce
 1. Build app with plugin 3.1.0
 2. Open Intercom Messenger
 3. Tap on a conversation -> App crashes

## Logs
n/a

Thanks

**Comment by jtreanor** [comment]
@FabPey In order to diagnose this issue we will need more details.

Can you provide a crash log for this?

**Comment by FabPey** [comment]
@jtreanor here it is - hope this helps - I see something related to READ_EXTERNAL_STORAGE permission in there and some thumbnail, maybe thats a clue...

03-14 13:07:22.993  7358  7358 E AndroidRuntime: FATAL EXCEPTION: main
03-14 13:07:22.993  7358  7358 E AndroidRuntime: Process: com.xxx.xxxxx, PID: 7358
03-14 13:07:22.993  7358  7358 E AndroidRuntime: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=7358, uid=10180 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1474)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:463)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:476)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:419)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at com.intercom.input.gallery.LocalImagesDataSource.getCount(LocalImagesDataSource.java:78)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at com.intercom.input.gallery.GalleryInputFragment.onViewCreated(GalleryInputFragment.java:226)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1314)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1979)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.view.View.measure(View.java:16736)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5184)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.view.View.measure(View.java:16736)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5184)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.view.View.measure(View.java:16736)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5184)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.view.View.measure(View.java:16736)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.view.View.measure(View.java:16736)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5184)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.view.View.measure(View.java:16736)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5184)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.view.View.measure(View.java:16736)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5184)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.view.View.measure(View.java:16736)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5184)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.view.View.measure(View.java:16736)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5184)
03-14 13:07:22.993  7358  7358 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasur
03-14 13:07:23.003  1038  1379 W ActivityManager:   Force finishing activity com.frs.hwfab/io.intercom.android.sdk.activities.IntercomMessengerActivity
03-14 13:07:23.023  1038  1379 D PMS     : acquireWL(425a68e8): PARTIAL_WAKE_LOCK  ActivityManager-Launch 0x1 1038 1000
03-14 13:07:23.523  1038  1139 W ActivityManager: Activity pause timeout for ActivityRecord{424de5d0 u0 com.frs.hwfab/io.intercom.android.sdk.activities.IntercomMessengerActivity t69 f}
03-14 13:07:24.403  1038  1402 D ActivityManager: getRecentTasks visible task but lastThumbnail is null, TaskRecord{43611dc0 #64 A=com.frs.hwfab U=0 sz=1}
03-14 13:07:24.433  1038  1458 D VibratorService: [VIB] time_out: 14
03-14 13:07:25.523  1205  1205 D WIFI_ICON: WifiActivity: 1
03-14 13:07:25.523  1205  1205 D StatusBar.NetworkController: dumpIcon[(gone) stat_sys_5signal_null|null stat_sys_wifi_signal_in_4 stat_sys_no_sim F]
03-14 13:07:26.533  1038  1376 I ActivityManager: Recipient 7358
03-14 13:07:26.543  1038  1376 I ActivityManager: Process com.xxx.xxxxx (pid 7358) has died.

**Comment by jtreanor** [comment]
This is an issue with 3.1.0 of Intercom's Android Messenger. The `READ_EXTERNAL_STORAGE` permission was previously optional. This will be fixed in the next Android release. See this issue for more info: https://github.com/intercom/intercom-android/issues/318.

However, in the meantime, you can solve your issue by including the permission. This can be done by adding the following to your `config.xml`:

```
<platform name="android">
    ...
    <config-file target="AndroidManifest.xml" parent="/*">
        <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE " />
        ...
    </config-file>
</platform>
```

**Comment by FabPey** [comment]
@jtreanor yep that fixed it - thanks!
