### ISSUE TITLE
App showing twice in recent apps list on Android

### ISSUE THREAD

**Issue by FabPey** [intercom/intercom-cordova#151]
## Version info
  - Intercom for Cordova/PhoneGap version: 3.1.0 (and 3.0.26)
  - Android OS version: 6, 7 (works ok on iOS)

## Expected behavior
App should only shows once in the "recent apps" list, regardless if messenger has been open.

## Actual behavior
Once the intercom messenger has been opened on Android 6 or 7, a second instance of our app appears in the "recent apps" list, with a screenshot of our app rather than the messenger, which means it looks like our app is there twice. One app is the actual app, the other one is the messenger window, which also shows a screenshot of the app, so no way to know which is which...

Note: I wonder if it's got anything to do with the AndroidLaunchMode cordova setting? What is the recommended value? (I think this may impact how the processes are ran) - I have tried no value and "singleTask" to no avail.

## Steps to reproduce
 1. Build app with plugin version 3.1.0 or 3.0.26 (phonegap build)
 2. Open Intercom messenger on Android 6 or 7
 3. Go to "recent apps" list

## Logs

Thanks

**Comment by FabPey** [comment]
Hi guys - quick update - it turns out I had the AndroidLaunchMode preference twice in my config.xml - the one I was changing was having no effect because the second one was being used... I removed 1 and set the remaining one to "singleTask" and the issue seems to have gone away. ("singleTop" also works but "singleInstance" and "standard" cause the issue)

Sorry about that - it may help somebody out there!

**Comment by jtreanor** [comment]
Thanks @FabPey. I'm glad you got this sorted 😄
