### ISSUE TITLE
Can't use attach/paperclip button Android

### ISSUE THREAD

**Issue by christoffer-Van** [intercom/intercom-cordova#158]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Cordova/PhoneGap version: 3.1.1
  - iOS/Android OS version: 6.0.1 and 7.0.1
  - iOS/Android Device: OnePlus X and Google Pixrl

## Expected behavior
Allow to attach documents from device folders

## Actual behavior
Click and nothing happens

## Steps to reproduce
 1. Open intercom
 2. Create new message
 3. Click paperclip in bottom right
 4. Nothing

Note: works for iOS as intended

## Logs

**Comment by jtreanor** [comment]
Hi @christoffer-Van,

You can enable file uploads by adding the following permission to your app:

```
<platform name="android">
    ...
    <config-file target="AndroidManifest.xml" parent="/*">
        <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE " />
        ...
    </config-file>
</platform>
```

We will look into why the paperclip button appears when the permission is not present.

**Comment by christoffer-Van** [comment]
@jtreanor 

So this sort of worked.

Wasn't able to put it in my config file as suggested above - build kept crashing.

Instead I added ```<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />``` to my AndroidManifest.xml and android.json directly inside the android platform folder.

This got it working. Not ideal of course, but it works - minus 1 thing.

So I click the paperclip, asks for permission, accept, click image, send, receive on the intercom dashboard, and it looks correct. All good so far.

However, I can't see the image in the app in the conversation I've sent, just an empty placeholder where it's supposed to be. Click the empty placeholder, get a dialog style fadeout where the image should be displayed, but is not there.

**Comment by jtreanor** [comment]
Thanks for the detail @christoffer-Van.

We'll look into this and update here.

**Comment by jtreanor** [comment]
@christoffer-Van Are you still seeing this issue? 3.1.1 of Intercom for Android included a number of improvements to the attachment feature. If you still have an issue could you send on a screenshot please?

It will still be necessary to add the permission (though I'm unsure why the config.xml change did not work). This is so that Intercom does not force your app to add a permission without your knowledge. If the permission is not present, the button will be hidden. We will update our docs to clarify this.

**Comment by christoffer-Van** [comment]
@jtreanor Looks like it's working as intended now on my end.

Yea, not too sure what the issue with the config.xml that didn't allow me to add the permission that way was, but that's more likely not your problem, but rather ionics or my own build. At least I could work around it.

Thanks for the timely response and fix 👍

**Comment by jtreanor** [comment]
That's great, thanks @christoffer-Van
