### ISSUE TITLE
Intercom Pod 3.1.2 doesnt exist, plugin install failing

### ISSUE THREAD

**Issue by djett41** [intercom/intercom-cordova#159]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Cordova/PhoneGap version: 3.1.1
  - iOS/Android OS version: 10.2
  - iOS/Android Device: NA

## Expected behavior
"cordova plugin add cordova-plugin-intercom" should install correct cocoa pod for intercom
## Actual behavior
Get followign error message.  The pod spec version in the plugin.xml is higher than the highest version in cocoa pods repo.  Either version should be 3.1.1, or the latest pod needs to be released in cocoa pods

Error: pod: Command failed with exit code 1

## Steps to reproduce
 1. cordova plugin rm cordova-plugin-intercom
 2. cordova plugin add cordova-plugin-intercom

## Logs
if I search the repo for Intercom pod "pod search Intercom", the highest it goes to is 3.1.1, but the plugin.xml specifies ~> 3.1.2

pods logs

-> Intercom (3.1.1)
   The Intercom iOS SDK, for integrating Intercom into your iOS application.
   pod 'Intercom', '~> 3.1.1'
   - Homepage: https://github.com/intercom/intercom-ios
   - Source:   https://github.com/intercom/intercom-ios/releases/download/3.1.1/CocoaPods.zip
   - Versions: 3.1.1, 3.1.0, 3.0.25, 3.0.24, 3.0.23, 3.0.22, 3.0.21, 3.0.20, 3.0.19, 3.0.18, 3.0.17, 3.0.16, 3.0.15, 3.0.14, 3.0.13, 3.0.12, 3.0.11, 3.0.10, 3.0.9, 3.0.8, 3.0.7, 3.0.6, 3.0.5,
   3.0.4, 3.0.3, 3.0.2, 3.0.1, 3.0.0, 3.0.0-beta5, 3.0.0-beta4, 3.0.0-beta3, 3.0.0-beta2, 3.0.0-beta1, 2.3.22, 2.3.21, 2.3.20, 2.3.19, 2.3.18, 2.3.17, 2.3.16, 2.3.15, 2.3.14, 2.3.13, 2.3.12,
   2.3.11, 2.3.10, 2.3.9, 2.3.8, 2.3.7, 2.3.6, 2.3.5, 2.3.4, 2.3.3, 2.3.2, 2.3.1, 2.3.0, 2.2.4, 2.2.3, 2.2.2, 2.2.1, 2.2, 2.1.1, 2.1, 2.0.7, 2.0.6, 2.0.5, 2.0.4, 2.0.3, 2.0.2, 2.0.1, 2.0.0 [master
   repo]

**Comment by djett41** [comment]
Not sure if I did something recently to fix this, or if you recently added it, but im now seeing the pod.  

Im new to pods, and was actually trying to debug a different cordova related issue (since our custom cordova plugin uses pods, and push plugin and intercom uses pods, I have to add them all (ours, pushes, intercoms) to my plugins plugin.xml, or else I'll get a Failed to install 'cordova-plugin-intercom':Error: pod: Command failed with exit code 1 error), 

but I did a pod repo update within the time frame, so maybe that's what did it?  Not sure but seems good to go.  the Command failed with exit code 1 error seems to be cordova CLI related or pod related since it happens with any plugin that includes a podspec in the plugin.xml

Thanks!!

-> Intercom (3.1.2)
   The Intercom iOS SDK, for integrating Intercom into your iOS application.
   pod 'Intercom', '~> 3.1.2'
   - Homepage: https://github.com/intercom/intercom-ios
   - Source:   https://github.com/intercom/intercom-ios/releases/download/3.1.2/CocoaPods.zip
   - Versions: 3.1.2, 3.1.1, 3.1.0, 3.0.25, 3.0.24, 3.0.23, 3.0.22, 3.0.21, 3.0.20, 3.0.19, 3.0.18, 3.0.17, 3.0.16, 3.0.15, 3.0.14, 3.0.13, 3.0.12, 3.0.11, 3.0.10, 3.0.9, 3.0.8, 3.0.7, 3.0.6,
   3.0.5, 3.0.4, 3.0.3, 3.0.2, 3.0.1, 3.0.0, 3.0.0-beta5, 3.0.0-beta4, 3.0.0-beta3, 3.0.0-beta2, 3.0.0-beta1, 2.3.22, 2.3.21, 2.3.20, 2.3.19, 2.3.18, 2.3.17, 2.3.16, 2.3.15, 2.3.14, 2.3.13,
   2.3.12, 2.3.11, 2.3.10, 2.3.9, 2.3.8, 2.3.7, 2.3.6, 2.3.5, 2.3.4, 2.3.3, 2.3.2, 2.3.1, 2.3.0, 2.2.4, 2.2.3, 2.2.2, 2.2.1, 2.2, 2.1.1, 2.1, 2.0.7, 2.0.6, 2.0.5, 2.0.4, 2.0.3, 2.0.2, 2.0.1, 2.0.0
   [master repo]

**Comment by jtreanor** [comment]
Hi @djett41,

I'm unsure what the issue was here. I have just confirmed that the pod was successfully deployed yeserday (see [here]()https://github.com/CocoaPods/Specs/commit/b5029449642b5101c1c16389fe9c4e9f77fd8495).

My best guess is that the CocoaPods specs repo was having issues.

Glad you got sorted in the end.
