### ISSUE TITLE
Intercom Plugin Fail on Cordova 6.5.0 Android

### ISSUE THREAD

**Issue by hsmith825** [intercom/intercom-cordova#160]
## Version info
  - Intercom for Cordova/PhoneGap version:
  - iOS/Android OS version:Android 2.3.0
  - iOS/Android Device: SamSong

## Expected behavior
It should build without errors

## Actual behavior
Error during the build if Intercom is included
Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

Without intercom, it builds without a problem
## Steps to reproduce
 1. Upgraded to Cordova 6.4
 2. Installed Cordova 6.4
 3. Build failed
4. Remove intercom plugin and it works.
5. Intercom worked on earlier version
6. Intercom works on earlier versions of this Cordova Android app.

## Logs
/Users/howardsmith/Documents/Android/FlickittAndroid/flickitt/platforms/android/build/intermediates/res/merged/debug/values-v24/values-v24.xml
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
Error:Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

I want to include Intercom in my Android version of the product to keep it compatible with the IOS version which 
Thanks!

**Comment by skylerwshaw** [comment]
@hsmith825 please see these comments:
https://github.com/tinycreative/react-native-intercom/pull/75#issuecomment-286451698
https://github.com/intercom/intercom-android/issues/316#issuecomment-286144749

You will want to update your compileSdkVersion to 25 in your Cordova project configuration.
