### ISSUE TITLE
Strange behavior in iOS ( Intercom.bundle hasn't been added to your app correctly...)

### ISSUE THREAD

**Issue by tiagobrait** [intercom/intercom-cordova#161]
## Version info
  - Intercom for Cordova version: 3.1.1
  - iOS version: 9.3.5
  - iOS Device: iPhone 4S (MD237LL/A) 

## Expected behavior
 When calling `intercom.displayMessenger()` the messenger should appear correctly.

## Actual behavior
 After `intercom.displayMessenger()` is called,  the messenger appears broken, missing some parts of the UI and with 'placeholder' text (like 'navbar.title.conversations'). It actually 'works' in the sense that you can still read/send messages, but once you open the messenger, the close icon does not appear, so you have to kill the app or it will get stuck in the conversations screen. There is a screenshot below so you can better understand what I'm talking about.

## Steps to reproduce
 1. Boot Intercom up (intercom.registerIdentifiedUser(), etc...);
 2. Display the messenger.

## Logs
The only relevant console message is as follows. It mentions images, but they appear fine (both in the chat and the profile pics, as you can see on the screenshot)

> ERROR - :boom::-1:  Intercom.bundle hasn't been added to your app correctly. This will result in images not appearing in the SDK's messaging UI. More information on how to correctly integrate Intercom is available here: https://developers.intercom.com/docs/ios-installation.

## Screenshots
Here's a screenshot from the problematic iPhone: 
![img_0002](https://cloud.githubusercontent.com/assets/2074014/24123398/1cf424c2-0d9e-11e7-914f-4e8a236088da.PNG)

## Additional Info
* The problem occurs only in iOS, the Android build works fine with the same plugin version. 
* I currently only have this 4S device with iOS 9 to test with. I will probably have access to a newer model some time this week, but that's still a maybe.
* The plugin and platform were removed and re-installed multiple times.
* I think maybe this can be some cocoaPods issue, but I'm not sure. The plugin installs ok, the project builds fine, the generated Podfile is correct and the Pod files seem to be all present. I will try to revert to a pre-cocoaPods version (3.0.26) later, but it would be really nice to have the latest version working in our deployed app.

Thank you.

**Comment by skylerwshaw** [comment]
@tiagobrait Can you ensure the following?:
* Your podfile contains `pod 'Intercom'` and does not specify a version
* Run `pod update` or `pod repo update`
* Ensure your `Podfile.lock` references version `3.1.2` (as of this writing)
* Ensure you are using a current Cocoapods installation which is `1.2.0` (as of this writing)

**Comment by BrainBacon** [comment]
Having a very similar issue when running `intercom.displayMessenger()`.
I'm getting this error:
```
💥 There was an error trying to access the Intercom.bundle but it is not present. It's possible that Xcode isn't seeing it correctly at build time.
```
`3.1.1` does not launch the messenger at all, but in `3.0.16` I get the following:
![simulator screen shot mar 21 2017 5 34 13 am](https://cloud.githubusercontent.com/assets/2396895/24143767/bfee876c-0df8-11e7-9501-6813ff7b1ccf.png)

**Comment by skylerwshaw** [comment]
@tiagobrait @BrainBacon 
In addition to `pod repo update`, can you please run this? Cordova recently implemented the use of CocoaPods and there may have been project migration issues.
```
cordova platform rm ios
cordova platform add ios
```

**Comment by BrainBacon** [comment]
@skylerwshaw Found out I was opening the `.xcodeproj` file instead of the `.xcworkspace` file. I'm not getting that error any more, but messenger is still not launching in `3.1.1`. The only log that I'm seeing when I try to launch the messenger with `intercom.displayMessenger()` is:
```
THREAD WARNING: ['Intercom'] took '16.142822' ms. Plugin should use a background thread.
```
but that looks like a red herring.

**Comment by tiagobrait** [comment]
@skylerwshaw 
Sorry for the delay. I checked all versions, and everything is up to date: 
* cordova: 6.5.0
* cocoapods: 1.2.0
* Podfile and Podfile.lock are ok

We also removed and re-added both the platform and the plugin and the problem still occurs. It's really weird. I will try to debug this further, but is there any other thing you can think of as the cause for this?

Thanks.

**Comment by bboyle18** [comment]
Hi @tiagobrait 👋 
Would you be able run the following cordova command and share your console logs with us?
`cordova build ios`

This will help us figure out if the correct build steps are being executed.

Thanks

Brian

**Comment by tiagobrait** [comment]
Here you go: [build_log.txt](https://gist.github.com/tiagobrait/dd2ce78708c6a76995428cda677b69f9)
I also forgot to mention we're using ionic, but I don't see how that could be the cause anyway.

Thanks.

**Comment by BrainBacon** [comment]
Looks like my issue was unrelated. Not completely sure how I got it running other than switching to the `.xcworkspace` project instead.

**Comment by bboyle18** [comment]
@brainbacon the reason switching to using .xcworkspace solves your problem is because Cordova now uses cocoapods and therefore creates a Pods project that exists in the workspace. Within this pods project is the build phase step to copy the Intercom.bundle file into your project. 

Brian

**Comment by tiagobrait** [comment]
OK, we did some cleanup in the platform folders, added everything back (platforms, plugins) and the messenger is coming up fine now.
Thanks everybody for the help. Closing the issue.

**Comment by jtreanor** [comment]
For future reference, these steps should resolve the issue:

1. Run `cordova platform version`. Ensure iOS is at least version 4.3.1.
2. From the `platforms/ios` directory, run `pod deintegrate` and then `pod install`. This will ensure that your Xcode project is correctly set up for CocoaPods.
