### ISSUE TITLE
onUnreadCountChange method

### ISSUE THREAD

**Issue by FabPey** [intercom/intercom-cordova#162]
Hi guys

We use your javascript API and it has this handy method onUnreadCountChange() - which means we can update our custom launcher in real time, whereas with the cordova plugin, we have to call intercom.unreadConversationCount everytime we want to check - is there any chance you could implement the onUnreadCountChange method in your cordova plugin?

Thanks

**Comment by bboyle18** [comment]
Hi @FabPey 

Thanks for the feedback. We'll take this as a feature request and look at adding it in a future release.

Brian

**Comment by FabPey** [comment]
HI @bboyle18 - Just wondering is there is any update on this onUnreadCountChange() function being made available in your cordova plugin - would be very useful as you can imagine. Thanks.

**Comment by bboyle18** [comment]
Hi @FabPey 
We haven't scheduled any time for this yet but I'll raise it with our team again today to see if we can include it in a future release.

Thanks

Brian
