### ISSUE TITLE
Can we use this plugin along with OneSignal and does this plugin work with Cordova 3.9.0?

### ISSUE THREAD

**Issue by menshinobi** [intercom/intercom-cordova#164]
My app is using OneSignal for push notification. Can I use this plugin along with it?

When I installed the plugin it requires Cordova 4.3.0. Can it work with lower Cordova version such as 3.9.0? It's because 4.3.0 breaks our app while 3.9.0 is stable enough.

Thanks!

**Comment by skylerwshaw** [comment]
@menshinobi The Intercom Cordova SDK wrapper does not support 3.9.0. Additionally, we have not tested compatibility of running both push providers at the same time, which may lead to conflicts.

**Comment by jtreanor** [comment]
@menshinobi A quick update here: Compatibility with our GCM providers has been fixed in [3.1.2](https://github.com/intercom/intercom-cordova/releases/tag/3.1.2). 4.3.0 is still required to use the plugin.
