### ISSUE TITLE
Crashing on initial load (iOS)

### ISSUE THREAD

**Issue by jonhainstock** [intercom/intercom-cordova#17]
```
<NSInvalidArgumentException> -[NSNull boolValue]: unrecognized selector sent to instance
```

This error happens every time I open up the app. It will run fine after I stop and rebuild, but it causes the app to crash initially. Any ideas on how I can fix this?

**Comment by jonhainstock** [comment]
This looks like it's a conflict with the ionic keyboard plugin.

**Comment by jtreanor** [comment]
Hi @jonhainstock 

Can you confirm that this issue wasn't caused by Intercom?

**Comment by jonhainstock** [comment]
It was happening because of a conflict with the ionic keyboard plugin. I made a pull request on the ionic keyboard plugin that resolved the issue.

**Comment by jtreanor** [comment]
Great. I'm glad you got it resolved.
