### ISSUE TITLE
Incompatibility with plugins that use cordova-plugin-cocoapods-support

### ISSUE THREAD

**Issue by chendo** [intercom/intercom-cordova#172]
We use a plugin that uses https://github.com/blakgeek/cordova-plugin-cocoapods-support and we discovered that when the other plugin does its Cocoapods install, the Intercom pod that was installed by the earlier step is removed, so the build step fails as it can't find `Intercom/Intercom.h`.

A potential solution is to have this plugin also use cocoapods-support, but we've worked around it for now by adding `<pod name="Intercom" version="3.1.3" />` to our `config.xml`.

## Version info
  - Intercom for Cordova/PhoneGap version: 3.1.3

## Expected behavior

App compiles correctly.

## Actual behavior

App build fails as it cannot find `Intercom/Intercom.h`.

## Steps to reproduce
 1. Add Intercom plugin
 2. Use a plugin that uses Cordova Cocoapods Support (i.e. https://github.com/chendo/cordova-plugin-bugsnag)
 3. `cordova build ios`

**Comment by bboyle18** [comment]
Hi @chendo 👋
Thanks for getting in touch. 

Unfortunately there is nothing we can do about another 3rd party plugin removing pods. I'd suggest you get in touch with the developer and request that the library is updated to be compatible with the latest version of Cordova. 
There's already an issue logged about it here https://github.com/blakgeek/cordova-plugin-cocoapods-support/issues/31
That might be a good starting point. 

Cheers 
Brian
