### ISSUE TITLE
Failed to install 'cordova-plugin-intercom':undefined

### ISSUE THREAD

**Issue by christoffer-Van** [intercom/intercom-cordova#173]
Was running Ionic 2.4.x

Have had intercom running in our app for a few months now, no major problems. Never with installing it.

Needed to build on a co-workers machine, and was getting this error ```Failed to install 'cordova-plugin-intercom':undefined```

Tried to repro on my machine, deleted the plugins folder, and now I get the same error. Updated to the latest Ionic, 3.0.1, same issue.

## Version info
  - Intercom for Cordova/PhoneGap version: 2.4.x and 3.0.1
  - iOS/Android OS version:
  - iOS/Android Device:

## Expected behavior
Should install plugin.

## Steps to reproduce
 1. Create new Ionic 2 project ```ionic start test --v2 --ts```
 2. ```npm install```
 3. ```ionic platform add ios```

## Logs

**Comment by bboyle18** [comment]
Hi @christoffer-Van 👋 
Have you got cocoapods installed?

Brian

**Comment by christoffer-Van** [comment]
@bboyle18 I totally didn't and am in the process now. Looks good so far. I'll probably close in a few assuming that fixes it :) 

Thanks for quick reply.

**Comment by bboyle18** [comment]
👍

**Comment by christoffer-Van** [comment]
So that worked. Got the emulator running again now.

However Intercom looks off. 

No close button top right. Odd naming in title

<img width="377" alt="screen shot 2017-04-24 at 10 41 12 am" src="https://cloud.githubusercontent.com/assets/8323722/25350637/9f84afcc-28da-11e7-8f03-f9469cac077f.png">

**Comment by christoffer-Van** [comment]
I'll close this issue for now. Looks like I had downgraded to 3.1.1 earlier to see if that was the culprit. I'll update and create a new issue if I still see a problem.

Thanks again @bboyle18

**Comment by bboyle18** [comment]
No problem, whats missing here is the `Intercom.bundle`. Cordova + Cocoapods seems to miss this step sometimes. In the past we've solved it by cleaning up the platforms directory. e.g.
```
cordova platform rm ios
cordova platform add ios
```

Feel free to open a new issue if you're still having problems.

Brian
