### ISSUE TITLE
Intercom missing close btn. Odd title naming

### ISSUE THREAD

**Issue by christoffer-Van** [intercom/intercom-cordova#174]
After updating to intercom 3.1.3. The native chat view I get is missing buttons, and has an odd title header.

<img width="377" alt="screen shot 2017-04-24 at 10 41 12 am" src="https://cloud.githubusercontent.com/assets/8323722/25351585/eec4fe18-28dd-11e7-8435-a6d0665c7de1.png">

## Version info
  - Intercom for Cordova/PhoneGap version: 3.1.3
  - iOS/Android OS version: 10.3
  - iOS/Android Device:

## Expected behavior
Should have a proper title and close button

## Actual behavior
See image

## Steps to reproduce
 1. Install plugin
 2. Run emulator
 3. Open intercom

## Logs

**Comment by christoffer-Van** [comment]
@bboyle18 I've tried removing and adding the iOS platform 4 times, and keep running into the issue. Also tried downgrading to 3.0.2 and 3.0.1, same.

**Comment by bboyle18** [comment]
Hi @christoffer-Van 
Whats missing here is `IntercomTranslations.bundle`. It should be added automatically, so theres no need for you to manually add it.
We'll try recreate the issue here and investigate. It will be tomorrow before we get back to you on this though as we are on GMT time.

Brian

**Comment by christoffer-Van** [comment]
Thanks. Appreciate it.

**Comment by DaleCantwell** [comment]
Could you try the steps from this comment https://github.com/intercom/intercom-cordova/issues/161#issuecomment-290089078
The issue looks very similar.

**Comment by christoffer-Van** [comment]
@DaleCantwell that does seem to fix it. Thank you! 

Also seem to open up a whole new can of worms, but not sure it's related yet.

**Comment by christoffer-Van** [comment]
So when I run the comnand as prescribed in the linked issue

```pod install``` inside the ```platform/ios```. It does work on the emulator. However when I try to run on a phone, I get ```Apple Mach-O Linker Error``` - this is a new error I wasn't getting before. If I remove and re add the platform, it works again, minus intercom looking off, ```install pods```, now I can't launch on a device

**Comment by christoffer-Van** [comment]
Ok

**Comment by HaspinderSingh** [comment]
Having the issue when install cocoapods in xcode through xcode.
Please Help me.
![simulator screen shot 16-jun-2017 11 12 45 pm](https://user-images.githubusercontent.com/29488837/27238123-54f52084-52e9-11e7-8f8b-59edadc1968a.png)

**Comment by jtreanor** [comment]
Hi @HaspinderSingh 

Have you tried the steps described in https://github.com/intercom/intercom-cordova/issues/161#issuecomment-290089078?

**Comment by HaspinderSingh** [comment]
Actually I'm using xcode (with swift language). I install intercom pods through terminal and follow this guide 
https://developers.intercom.com/docs/ios-installation
