### ISSUE TITLE
Set Bottom Padding for the Icon

### ISSUE THREAD

**Issue by heshamghandour** [intercom/intercom-cordova#176]
Hi!

In the older version (prior to v3) it was possible to set the position of the icon showing a new message. This function was removed in the new release for some reason. 

Is it possible to use the function setBottomPadding to slightly lift up the icon?

Thanks!

**Comment by bboyle18** [comment]
Hi @heshamghandour 👋 
Thanks for getting in touch.
You are correct that the ability to set the bottom padding was removed. We are currently planning our roadmap so we will take your feedback onboard and look at potentially adding it in a future release.

Thanks 👍 

Brian
