### ISSUE TITLE
ionic build fails

### ISSUE THREAD

**Issue by christoffer-Van** [intercom/intercom-cordova#179]
Tried updating the the latest minor version to fix a bug I was having (https://github.com/intercom/intercom-cordova/issues/178). Instead of fixing it, I am now no longer able to make builds using Ionic 2.

## Version info
  - Intercom for Cordova/PhoneGap version: 3.2.0
  - Ionic Version: 3.1.1
  - iOS/Android OS version: 
  - iOS/Android Device:

## Expected behavior
ionic build android should result with a successful package

## Actual behavior
Build failed.

## Steps to reproduce
 1.  Follow intercom install guidelines
 2. ionic platform add android
 3. ionic build

## Logs

```
:mergeArmv7DebugResources


:processArmv7DebugManifest
/Users/christofferjohansen/Documents/WealthBar/mobile-app-ionic/platforms/android/AndroidManifest.xml:27:9-31 Error:

	Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [com.android.support:design:25.3.1] AndroidManifest.xml:27:9-31
	is also present at [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38 value=(26.0.0-alpha1).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:34 to override.




See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.


:processArmv7DebugManifest
FAILED



FAILURE:
Build failed with an exception.


* What went wrong:

Execution failed for task ':processArmv7DebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [com.android.support:design:25.3.1] AndroidManifest.xml:27:9-31

  	is also present at [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38 value=(26.0.0-alpha1).

  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:34 to override.
```

**Comment by bboyle18** [comment]
Hi @christoffer-Van 

The error reported has nothing to do with Intercom. 
It looks like you are having an issue with your Android support libraries version.
http://stackoverflow.com/questions/42949974/android-support-repo-46-0-0-with-android-studio-2-3

Brian
