### ISSUE TITLE
Push notifications attribute not working on iOS

### ISSUE THREAD

**Issue by morellan** [intercom/intercom-cordova#183]
## Version info
  - Intercom for Cordova/PhoneGap version: intercom-cordova@3.2.1 - phonegap@6.5.0
  - iOS OS version: 10.3.1
  - iOS/Android Device: iPhone 6

## Expected behavior
Intercom user attribute `ENABLED PUSH MESSAGING` should be enabled once the user accepts to be notified

## Actual behavior
Intercom user attribute `ENABLED PUSH MESSAGING` is `unknown` after the user accepts to be notified

## Steps to reproduce
 1. cordova platform add ios
 2. cordova plugin add cordova-plugin-intercom@3.2.1
 3. cordova build ios
 4. When `intercom.registerForPush()` is called click on `Accept`
 5. On Intercom platform open the user profile and see the attribute
<img width="303" alt="screen shot 2017-05-15 at 4 31 36 pm" src="https://cloud.githubusercontent.com/assets/1439999/26077988/02552a16-398c-11e7-9ecb-a84ad63c9978.png">

## Logs

Everything works using cordova commands, but when I tried using XCode I found something that could be related
```
[Intercom] ERROR - 💥👎 Intercom.bundle hasn't been added to your app correctly. This will result in images not appearing in the SDK's messaging UI. More information on how to correctly integrate Intercom is available here: https://developers.intercom.com/docs/ios-installation.
```

Related issues 
- https://github.com/intercom/intercom-ios/issues/94
- https://github.com/intercom/intercom-cordova/issues/161

## Sidenote

Everything works as expected on Android

**Comment by skylerwshaw** [comment]
@morellan there are two situations here:

1. To resolve the `Intercom.bundle hasn't been added to your app correctly` error:
    * Run cordova platform version. Ensure iOS is at least version 4.3.1.
    * From the platforms/ios directory, run pod deintegrate and then pod install. This will ensure that your Xcode project is correctly set up for CocoaPods.

     This is due to Cordova not managing CocoaPods dependencies properly.

2. Your reproduction steps don't include the provisioning of your app for push. Have you done this through the Apple Developer site? You'll need to ensure you've followed steps 1-4 here: https://developers.intercom.com/docs/ios-push-notifications

***

As this is a customer support integration issue and not a bug, can you please open a conversation with us through the Intercom in-app messenger while logged into your Intercom dashboard? Thanks!

**Comment by morellan** [comment]
@skylerwshaw 

1. I did that but the problem was that I was using the `xcodeproj` instead of the `xcworkspace` (I didn't see that on the docs)

2. I did all the steps mentioned on that documentation, but I realized that my problem was that I have been using the Debug build instead of the Release build on iOS

Thanks!
