### ISSUE TITLE
Plugin conflicts with Firebase plugin

### ISSUE THREAD

**Issue by robinbonnes** [intercom/intercom-cordova#188]
Hello,

In my application I want to use both this plugin and the cordova Firebase plugin: https://github.com/arnesson/cordova-plugin-firebase

As typescript layer above this I use ionic-native:

- https://ionicframework.com/docs/native/firebase/
- https://ionicframework.com/docs/native/intercom/

## Version info
  - Intercom for Cordova/PhoneGap version: 3.2.2.
  - iOS/Android OS version: Android 6.0.1
  - iOS/Android Device: Xiaomi Redmi Note 3

## Expected behavior

App should build and run correctly on my device when running: 'ionic cordova run android --device' in the Ionic CLI.

## Actual behavior

Build process fails with the following error:

![image](https://cloud.githubusercontent.com/assets/5117166/26673638/e6a82a86-46bd-11e7-9862-89ec9b9f58c7.png)

When I remove these 4 last lines from /plugins/cordova-plugin-intercom/src/android/intercom.gradle:

```
if (pushType == 'fcm') {
    tasks.copyGoogleServices.execute()
    apply plugin: com.google.gms.googleservices.GoogleServicesPlugin
}
```

And re-add the Android platform, it gives the following error:

![image](https://cloud.githubusercontent.com/assets/5117166/26673898/cbf7121e-46be-11e7-8d7b-ef8da61a03a0.png)

## Steps to reproduce
 1. Install the Ionic/Cordova CLI.
 2. Add both plugins: 'cordova plugin add cordova-plugin-intercom' and 'cordova plugin add cordova-plugin-firebase'.
 3. Run 'cordova run android'.

## Logs

See screenshots above.

**Comment by jtreanor** [comment]
Thanks for the detailed report @robinbonnes.

There certainly seems to be a conflict between these two FCM implementations. We will look into it and update here as we know more.

James

**Comment by robinbonnes** [comment]
Thanks @jtreanor.

Nevermind the second part. I found out is a conflict between the 'cordova-plugin-firebase' and the 'phonegap-push-plugin'. So removing:

```
if (pushType == 'fcm') {
    tasks.copyGoogleServices.execute()
    apply plugin: com.google.gms.googleservices.GoogleServicesPlugin
}
```

And rebuilding the platform did fix the first issue for me. However now i'm stuck with this:

![image](https://cloud.githubusercontent.com/assets/5117166/26675431/39a39d32-46c4-11e7-83b7-642d544ebf5e.png)

This means some plugins use v26 of the support version and Intercom uses v25. I'm searching for a fix and keep you updated.

**Comment by ronocod** [comment]
That error looks very similar to https://github.com/intercom/intercom-cordova/issues/182, can you double check you're using version 3.2.2 of the Intercom plugin and do a clean build?

**Comment by robinbonnes** [comment]
Yes im really running version 3.2.2. I did (temporary) fix this by changing /plugins/cordova-plugin-fileopener2/plugin.xml line 34 from:

`<framework src="com.android.support:support-v4:+" />`

To:

`<framework src="com.android.support:support-v4:25.+" />`

And re-add the Android platform.

**Comment by jgkinnear** [comment]
I'm having the same issue. If anybody has a solution I would love to hear it :) Ill post any success I have

**Comment by brickolicious** [comment]
I went into my Podfile in /platforms/ios and added

platform :ios, '8.0'
target 'FitCycle' do
	pod 'Firebase/Core', '~> 4.0.0'
	pod 'Intercom', '~> 3.2.2'
end

than cd into that folder and run "pod install"

**Comment by skylerwshaw** [comment]
@robinbonnes are you still experiencing this issue? Going to close this out as a third party conflict unless there's something we can do to help and avoid a dependency issue here. Let me know! Thank you. -Skyler
