### ISSUE TITLE
When I close the app, and then open, the old conversation is gone.

### ISSUE THREAD

**Issue by IronPans** [intercom/intercom-cordova#189]
When I close the app, and then open, the old conversation is gone.(in ionic 3, @ionic-native/intercom)

## Version info
  - Intercom for Cordova/PhoneGap version:   3.12.1 (@ionic-native/intercom)

## Expected behavior

When I open the app, can see the old conversation

## Actual behavior

couldn't

**Comment by skylerwshaw** [comment]
Hi @IronPans, from your description it appears that you may be calling the `intercom.reset();` method on each app launch. Alternatively, but less likely, you may be affecting our session persistence in some manner. 

Can you please start a conversation with us by messaging us using the Intercom in-app messenger at Intercom.com or while logged into your Intercom dashboard? Feel free to ask for Skyler. We'd be happy to look at logs and review your code to see what might be occurring with your implementation.

**Comment by IronPans** [comment]
@skylerwshaw no, When  the problem can not be solved , I try the reset() method. I also tried to use only undefined user call， but the problem remain. The problem has been more than a week

**Comment by skylerwshaw** [comment]
@IronPans please message us through Intercom's in-app messenger at app.intercom.com or email team@intercom.io. We will need to look at your application logs and we need account information about your Intercom app and test account details. You probably do not want to share them here. Feel free to reference my name, Skyler, in your message to us.
