### ISSUE TITLE
Compatability with the new push plugin

### ISSUE THREAD

**Issue by elliotstokes** [intercom/intercom-cordova#19]
We now have successfully moved over to the official intercom cordova api and we are using the intercom push plugin branch.

As your probably aware push plugin has now been deprecated

https://github.com/phonegap-build/PushPlugin

and https://github.com/phonegap/phonegap-plugin-push phonegap-plugin-push has taken its place. Are you aware of any compatibility issues with this plugin as there are with the old plugin as we would like to move up to the new plugin if at all possible.

**Comment by harkin** [comment]
It seems to still be using `gcm.jar` from two years ago https://github.com/phonegap/phonegap-plugin-push/tree/master/src/android/libs which was the primary incompatibility with the now deprecated plugin. I don't see any reason to think that the new plugin will work with our cordova integration, unfortunately :(

@jtreanor made our fork of the plugin so he'll have the definitive answer here

**Comment by jtreanor** [comment]
@harkin is correct here. The new plugin has all the same problems as the old one. i.e. It uses `gcm.jar`, it bundles the support library etc.

However, we should be able to work around the issues in the same way. I'll try to get this done in the near future.

**Comment by elliotstokes** [comment]
Thanks.

**Comment by jtreanor** [comment]
I have made a fork for the new push plugin [here](https://github.com/intercom/phonegap-plugin-push). It is still very unfortunate that we have to do this but until we have a permanent solution I recommend you use this.

The issue is that the push plugin assumes all push received is for itself and so interferes with any other plugin which wants to handle push.

You can install it like this:

```
cordova plugin add https://github.com/intercom/phonegap-plugin-push.git
```

**Comment by elliotstokes** [comment]
Ah great. Were currently in the middle of another piece of work but Ill try it out when I get 5 minutes.

Thanks
