### ISSUE TITLE
Plugin Fails to Download Translations

### ISSUE THREAD

**Issue by PointmanDev** [intercom/intercom-cordova#191]
## Version info
  - Intercom for Cordova/PhoneGap version: >3.1.2
  - iOS/Android OS version: 10.3.1 (14F89)
  - iOS/Android Device: iOS only

## Expected behavior
Intercom should display X to close at top and should have translations of text instead of placeholders

## Actual behavior
Placeholder text is missing on versions higher than 3.1.2
## Steps to reproduce
 1. cordova plugin add cordova-plugin-intercom (this defaults to 3.2.0)
 2. cordova run ios --device 
 3. When doing the same actions but forcing version (cordova-plugin-intercom@3.1.2) intercom acts as expected.

## Logs

**Comment by PointmanDev** [comment]
Found a similar issue here: https://github.com/intercom/intercom-cordova/issues/161

After cordova platform add ios, the 'pod install' is never getting run. I wrote an after_platform_add hook to execute it and that seems to work.

**Comment by jtreanor** [comment]
Hi @PointmanDev,

Thanks for reporting this. `pod install` not being run is an issue with Cordova itself and not related to Intercom. I suggest opening an issue with the Cordova team.

Let me know if you have any questions.

Cheers,
James
