### ISSUE TITLE
Auto assigned names are not as good as the Web version

### ISSUE THREAD

**Issue by AshleyDeng** [intercom/intercom-cordova#193]
## Version info
  - Intercom for Cordova/PhoneGap version: 3.2.2
  - iOS/Android OS version: 10.3.2
  - iOS/Android Device: iOS

## Expected behavior
When user is not logged in (registerUnidentifiedUser), his auto assigned names should be something like: "Pink Cactus" or "Blue Flamingo", which is the default Intercom behaviour on Web.
## Actual behavior
When user is not logged in (registerUnidentifiedUser), his auto assigned names is "User p11v4j"
## Steps to reproduce
 1. Init Intercom with registerUnidentifiedUser method
 2. Start a conversation
 3. See conversation and user name on app.intercom.io

## Logs
Not applicable.

**Comment by bboyle18** [comment]
Hi @AshleyDeng 👋 

Thanks for getting in touch. 
The reason for this difference is down to some internal details in Intercom's User model about how we treat unidentified users from the web and mobile.
I agree that `User p11v4j` is not really great compared to the web equivalents. I'll raise this as a feature request to the team.

Thanks for the feedback, its really valuable.

Brian
