### ISSUE TITLE
Plugin does not update iOS entitlements file

### ISSUE THREAD

**Issue by DanBlakeman** [intercom/intercom-cordova#196]
## Version info
  - Intercom for Cordova/PhoneGap version: ~3.2.2
  - iOS/Android OS version: any iOS
  - iOS/Android Device: any iOS

## Issue

Upon following the guidance provided in the README for enabling push notification support. We are able to work with push notifications locally using our development build. When we try to push our app to production we receive emails from Apple explaining: 

```
We have discovered one or more issues with your recent delivery for "XXX". Your delivery was successful, but you may wish to correct the following issues in your next delivery:

Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. Xcode 8 does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.
```
This seems to be because intercom-cordova is not adding push notifications to the entitlements file.

## Potential solution

Other Cordova plugins enabling push notifications use ```config-file``` to add to the entitlements file. See example here: https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/8147f93d5cb4232082a4121732f7d4dba2167e17/plugin.xml#L83

Perhaps this can be added to intercom-cordova?

## Steps to reproduce
 1. Install intercom-cordova
 2. Follow README instructions to enable push notifications
 3. Attempt to deploy to Apple app store

**Comment by bboyle18** [comment]
Hi @DanBlakeman 👋 

Apologies for the delay in responding to you.
Thanks for this suggestion. Its not something we've thought about in the past but its a good suggestion. We'll consider adding this feature in a future release. 👍 

Thanks 

Brian

**Comment by krishnagopinath** [comment]
Has there been a fix for this yet? I'm on the latest version, and the [`plugin.xml`](https://github.com/intercom/intercom-cordova/blob/master/intercom-plugin/plugin.xml) does not seem to have it. 

Thank you for all the good work, this plugin is fantastic to use! :tada:
