### ISSUE TITLE
Add to phonegap build

### ISSUE THREAD

**Issue by elliotstokes** [intercom/intercom-cordova#2]
Is it possible to add this plugin to phonegap build?

**Comment by jtreanor** [comment]
Hi @elliotstokes,

As of now we haven't added the plugin to `build.phonegap.com/plugins`.

However, you can user the plugin with PhoneGap build by added this to your `config.xml`:

```
<gap:plugin name="io.intercom.cordova" version="1.0.0" source="plugins.cordova.io" >
    <param name="APP_ID" value="your_app_id" />
    <param name="IOS_API_KEY" value="ios_sdk-..." />
    <param name="ANDROID_API_KEY" value="android_sdk-..." />
</gap:plugin>
```

Does this solve your problem?

**Comment by elliotstokes** [comment]
Yeah. That should do nicely. Thsnks! Will hopefully try this out early next week.

**Comment by jtreanor** [comment]
Great :smile: 

Feel free to reach out here or through Intercom if you have any questions.
