### ISSUE TITLE
Error when registering for push.

### ISSUE THREAD

**Issue by elliotstokes** [intercom/intercom-cordova#20]
When I call intercom.setupAPN(deviceToken, callback, errCallback);

I get the error 

Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'
*** First throw call stack:
(0x2bf8d137 0x39ee9c77 0x2be9efc7 0x145f11 0x172e4b 0x17273f 0x2ccc0125 0x2bf5315f 0x2bf52ce1 0x2bf50f4b 0x2be9c9a1 0x2be9c7b3 0x3364e1a9 0x2f627695 0x6e593 0x3a491aaf)

It doesn't always occur - maybe 25-50% of the time. Should this be called before registerIdentifiedUser or does it not matter?

**Comment by elliotstokes** [comment]
commenting out the setupAPn line fixes the issues and the app loads every time.

**Comment by elliotstokes** [comment]
I had a look at the crash logs and it looks like it might be my issue. I think it might be sneding a null device token and then blowing in the plugin on the command

NSString *deviceToken = command.arguments[0];

as the arguments does not have any elements in it.

**Comment by elliotstokes** [comment]
Closing for now.

**Comment by jtreanor** [comment]
This is actually an issue with the plugin. I am releasing [1.0.9](https://github.com/intercom/intercom-cordova/releases/tag/1.0.9) now to fix it.

**Comment by elliotstokes** [comment]
ah brilliant. I thought I was going mad!

**Comment by jtreanor** [comment]
Happy to help :smile:
