### ISSUE TITLE
not able to create a build for android application after installing intercom plugin in hybriad application

### ISSUE THREAD

**Issue by iauro-pratik** [intercom/intercom-cordova#204]
For feature requests please contact us at team@intercom.io

## Steps to reproduce
1. install node
2. install ionic and cordova
3. create project ionic start myApp tabs
4. ionic cordova platform add android
5. ionic cordova plugin add cordova-plugin-intercom
6. npm install --save @ionic-native/intercom 
7. ionic cordova build android

## Logs
✖ Running command - failed!
[ERROR] An error occurred while running cordova build android (exit code 1):

    (truncated) ... ion for details.
    :CordovaLib:processReleaseJavaRes UP-TO-DATE
    :CordovaLib:transformResourcesWithMergeJavaResForRelease
    :CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
    :CordovaLib:mergeReleaseJniLibFolders
    :CordovaLib:transformNative_libsWithMergeJniLibsForRelease
    :CordovaLib:transformNative_libsWithSyncJniLibsForRelease
    :CordovaLib:bundleRelease
    :prepareComAndroidSupportAnimatedVectorDrawable2602Library
    :prepareComAndroidSupportAppcompatV72602Library
    :prepareComAndroidSupportCardviewV72531Library
    :prepareComAndroidSupportCustomtabs2531Library
    :prepareComAndroidSupportDesign2602Library
    :prepareComAndroidSupportRecyclerviewV72602Library
    :prepareComAndroidSupportSupportCompat2602Library
    :prepareComAndroidSupportSupportCoreUi2602Library
    :prepareComAndroidSupportSupportCoreUtils2602Library
    :prepareComAndroidSupportSupportFragment2602Library
    :prepareComAndroidSupportSupportMediaCompat2602Library
    :prepareComAndroidSupportSupportV42602Library
    :prepareComAndroidSupportSupportVectorDrawable2602Library
    :prepareComAndroidSupportTransition2602Library
    :prepareComFacebookAndroidFacebookAndroidSdk4260Library
    :prepareComGoogleAndroidGmsPlayServicesAuth1122Library
    :prepareComGoogleAndroidGmsPlayServicesAuthApiPhone1122Library
    :prepareComGoogleAndroidGmsPlayServicesAuthBase1122Library
    :prepareComGoogleAndroidGmsPlayServicesBase1122Library
    :prepareComGoogleAndroidGmsPlayServicesBasement1122Library
    :prepareComGoogleAndroidGmsPlayServicesIdentity1122Library
    :prepareComGoogleAndroidGmsPlayServicesTasks1122Library
    :prepareComIntercomAndroidComposer131Library
    :prepareComIntercomAndroidComposerGallery131Library
    :prepareIoIntercomAndroidIntercomSdkBase403Library
    :prepareOrgApacheCordovaCordovaLib623DebugLibrary
    :prepareDebugDependencies
    :compileDebugAidl
    :compileDebugRenderscript
    :generateDebugBuildConfig
    :generateDebugResValues
    :generateDebugResources
    :mergeDebugResources
    :processDebugManifest
    :processDebugResources/home/pratik/workspace/ionic-app/myApp/platforms/android/build/intermediates/res/merged/debug/values-v26/values-v26.xml:15:21-54: 
    AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
        
    /home/pratik/workspace/ionic-app/myApp/platforms/android/build/intermediates/res/merged/debug/values-v26/values-v26.xml:18:21-54: 
    AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
        
    /home/pratik/workspace/ionic-app/myApp/platforms/android/build/intermediates/res/merged/debug/values-v26/values-v26.xml:15: 
    error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
    
    /home/pratik/workspace/ionic-app/myApp/platforms/android/build/intermediates/res/merged/debug/values-v26/values-v26.xml:18: 
    error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
    
    
      FAILED
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':processDebugResources'.
    > com.android.ide.common.process.ProcessException: Failed to execute aapt
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    
    BUILD FAILED
    
    Total time: 16.722 secs
    Error: /home/pratik/workspace/ionic-app/myApp/platforms/android/gradlew: Command failed 
    with exit code 1 Error output:
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    /home/pratik/workspace/ionic-app/myApp/platforms/android/build/intermediates/res/merged/debug/values-v26/values-v26.xml:15:21-54: 
    AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
        
    /home/pratik/workspace/ionic-app/myApp/platforms/android/build/intermediates/res/merged/debug/values-v26/values-v26.xml:18:21-54: 
    AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
        
    /home/pratik/workspace/ionic-app/myApp/platforms/android/build/intermediates/res/merged/debug/values-v26/values-v26.xml:15: 
    error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
    
    /home/pratik/workspace/ionic-app/myApp/platforms/android/build/intermediates/res/merged/debug/values-v26/values-v26.xml:18: 
    error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
    
    
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':processDebugResources'.
    > com.android.ide.common.process.ProcessException: Failed to execute aapt
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

##Ionic info
cli packages: (/home/pratik/myApp/node_modules)

@ionic/cli-utils  : 1.10.1
ionic (Ionic CLI) : 3.10.1

global packages:

Cordova CLI : 7.0.1 

local packages:

@ionic/app-scripts : 2.1.4
Cordova Platforms  : android 6.2.3
Ionic Framework    : ionic-angular 3.6.1

System:

Android SDK Tools : 25.2.5
Node              : v6.11.1
npm               : 3.10.10 
OS                : Linux 4.10

**Comment by iauro-pratik** [comment]
Hello team, I have downgrade the version of intercom to 3.0.22 its working me
ionic cordova plugin add cordova-plugin-camera@3.0.22

**Comment by ronocod** [comment]
If you run these commands before building the app does it work?
```bash
export ORG_GRADLE_PROJECT_cdvCompileSdkVersion=android-26
export ORG_GRADLE_PROJECT_cdvBuildToolsVersion=26.0.1
```

**Comment by iauro-pratik** [comment]
I haven't try it.

**Comment by JanMesaric** [comment]
@ronocod works! Thank you

**Comment by ronocod** [comment]
Great! We recommend staying on the latest `compileSdkVersion` and `buildToolsVersion` on Android at all times for the best stability and compatibility. There's more information on how to set these in Cordova here: https://cordova.apache.org/docs/en/latest/guide/platforms/android/#configuring-gradle
