### ISSUE TITLE
Not able to build android project

### ISSUE THREAD

**Issue by AjitPrajapati** [intercom/intercom-cordova#207]
Hello I am getting below error while build adroid project
Severity	Code	Description	Project	File	Line	Suppression State
Error AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.	Intercom

**Comment by ronocod** [comment]
Can you try running the commands from this comment before build? https://github.com/intercom/intercom-cordova/issues/204#issuecomment-329178158

**Comment by ronocod** [comment]
Also, can you update to version 4.1.0 of the plugin, run `cordova build android` and see if there are any error messages from Intercom? We added diagnostic logging for common Android issues in this version.

**Comment by bboyle18** [comment]
Closing this issue. Should be resolved by updating to 4.1.0.
Please feel free to re-open if you are continuing to experience this issue after updating.
