### ISSUE TITLE
Conflits with cordova-plugin-fcm

### ISSUE THREAD

**Issue by JumBay** [intercom/intercom-cordova#208]
Hi,

I try to make intercom plugin works with cordova-plugin-fcm on android (not tested on iOS yet).

## Version info
  - Intercom for Cordova/PhoneGap version: 4.0.0
  - iOS/Android OS version: Android 7.1.2
  - iOS/Android Device: Nexus 5

## Expected behavior
Have both plugin working properly

## Actual behavior
When I build the project `<preference name="intercom-android-push-type" value="FCM" />` I get this error: 
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Cannot add task ':processDebugGoogleServices' as a task with that name already exists.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.956 secs
Error: /Users/JB/Documents/projects/wizi/wizi-mobile/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Cannot add task ':processDebugGoogleServices' as a task with that name already exists.
```

If I change the `intercom-android-push-type` to `GCM`, the app build but keeps crashing.

I tried to comment `apply plugin: com.google.gms.googleservices.GoogleServicesPlugin` into `plugins/cordova-plugin-intercom/src/android/intercom.gradle` or `plugins/cordova-plugin-fcm/src/android/FCMPlugin.gradle` but then all intercom's notifications are not received.

Do you have any idea how to have all notifications working?

Thanks

**Comment by bboyle18** [comment]
Hi @JumBay 👋 
Thanks for getting in touch.
This is a known issue for us and we are investigating a fix at the moment.
In the meantime, others have been able to solve the problem with this workaround
https://github.com/intercom/intercom-cordova/issues/203#issuecomment-328692973

Hope that helps,

Brian
