### ISSUE TITLE
Android Crashes when sending push notification while in background

### ISSUE THREAD

**Issue by heshamghandour** [intercom/intercom-cordova#209]
Hi!
Yesterday I sent a notification to our users, and we got thousands of crashes reported on our Android version due to an intercom error.

## Version info
  - Intercom for Cordova/PhoneGap version: 4.0.0
  - Android OS version: All android devices 4.4 upto 8
  - iOS/Android Device: Hundreds of devices

## Expected behavior

When a push notification is sent, and the app is in the background it should be fine.

## Actual behavior

App crashes with the following error being thrown:

`Fatal Exception: java.lang.NoSuchMethodError: No virtual method setChannelId(Ljava/lang/String;)Landroid/support/v4/app/NotificationCompat$Builder; in class Landroid/support/v4/app/NotificationCompat$Builder; or its super classes (declaration of 'android.support.v4.app.NotificationCompat$Builder' appears in /data/app/com.wadeeny.ondemand-2/base.apk)
       at io.intercom.android.sdk.push.SystemNotificationFactory.createSingleNotification(SystemNotificationFactory.java:60)
       at io.intercom.android.sdk.push.SystemNotificationManager.createNotification(SystemNotificationManager.java:99)
       at io.intercom.android.sdk.push.PushHandler.sendNotification(PushHandler.java:62)
       at io.intercom.android.sdk.push.PushHandler.handlePush(PushHandler.java:32)
       at io.intercom.android.sdk.push.IntercomPushClient.handlePush(IntercomPushClient.java:129)
       at io.intercom.android.sdk.IntercomIntentService.onHandleIntent(IntercomIntentService.java:22)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)`

## Steps to reproduce
 1. Open App
 2. Press Home button
 3. Send a notification to that app

## Logs

See Above

**Comment by heshamghandour** [comment]
Ah yes seems to be a similar issue!
Sure:

br.com.dtmtec.plugins.carrier 1.0.0 "Carrier"
com.chariotsolutions.cordova.plugin.keyboard_toolbar_remover 0.0.2 "Keyboard Toolbar Remover"
com.darktalker.cordova.screenshot 0.1.5 "Screenshot"
com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
com.lampa.startapp 0.1.4 "startApp"
com.telerik.plugins.nativepagetransitions 0.6.5 "Native Page Transitions"
cordova-background-geolocation 2.8.4 "BackgroundGeolocation"
cordova-fabric-plugin 1.1.9 "cordova-fabric-plugin"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-background-fetch 5.0.0 "CDVBackgroundFetch"
cordova-plugin-cocoalumberjack 0.0.1 "CocoaLumberjack"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-device 1.1.5 "Device"
cordova-plugin-device-orientation 1.0.6 "Device Orientation"
cordova-plugin-dialogs 1.3.2 "Notification"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-file 4.3.2 "File"
cordova-plugin-file-transfer 1.6.2 "File Transfer"
cordova-plugin-geolocation 2.4.2 "Geolocation"
cordova-plugin-globalization 1.0.6 "Globalization"
cordova-plugin-google-analytics 1.7.11 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.0.11 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.0 "InAppBrowser"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-intercom 4.0.0 "Intercom"
cordova-plugin-locationservices 2.1.0 "Google Location Services for Cordova - Android"
cordova-plugin-navigationbar 1.0.31 "Cordova NavigationBar plugin"
cordova-plugin-network-information 1.3.2 "Network Information"
cordova-plugin-request-location-accuracy 2.2.1 "Request Location Accuracy"
cordova-plugin-screensize 1.3.1 "screensize"
cordova-plugin-splashscreen 4.0.2 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-x-socialsharing 5.1.7 "SocialSharing"
cordova-sqlite-storage 2.0.3 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 3.6.7 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.2.0 "OneSignal Push Notifications"

**Comment by heshamghandour** [comment]
Are there any problems with the list of plugins?

**Comment by ronocod** [comment]
I can't tell yet. What's happening here is that one of the plugins is making your app use a version of the Android v4 Support Library lower than 26.0.0. We need version 26.0.0 or above to be present in your app as we call that `setChannelId` method which was added in that version.

If you look through the `platforms/android` folder and subfolders for `*.gradle` files, you might be able to find which plugin is bringing in the older version.

**Comment by heshamghandour** [comment]
Alright, thanks for the guidance, I'll try to dig deeper and update you if I find a solution.

**Comment by RoydenTJames** [comment]
Having the exact same issue. My plugin list:

cordova-android-support-gradle-release 1.1.2 "cordova-android-support-gradle-release"
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-badge 0.8.1 "Badges"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-intercom 4.0.0 "Intercom"
cordova-plugin-media 3.0.1 "Media"
cordova-plugin-screen-orientation 2.0.1 "Screen Orientation"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-vibration 2.1.5 "Vibration"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova.plugins.diagnostic 3.6.6 "Diagnostic"
de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"

**Comment by ronocod** [comment]
Can you open a terminal in your `platforms/android` directory and run this command?
`pcregrep -M 'dependencies {((\n|.)*?({(\n|.)*?})*(\n|.))(?R)?}' **/*.gradle`
It should work if you're on macOS or Linux.

**Comment by RoydenTJames** [comment]
Still learning here, but getting this: -bash: pcregrep: command not found

**Comment by RoydenTJames** [comment]
Never mind, found the issue. cordova.plugins.diagnostic was out of date. Updated to version 3.7.1 and everything worked

**Comment by ronocod** [comment]
Great, thanks for getting back with a fix.

@heshamghandour this should fix your issue too.
