### ISSUE TITLE
My app crash when i use intercom.displayMessenger()

### ISSUE THREAD

**Issue by ferdelcorro** [intercom/intercom-cordova#212]
## Version info
  - Intercom for Cordova/PhoneGap version: 4.0.0
  - iOS/Android OS version: 5.0.1
  - iOS/Android Device: LG Spirit H440AR

I have the same code that phonegap version 3.0.26, i just added intercom.setUserHash().
This code works fine on iOS but when i tried to open the messenger with intercom.displayMessenger() on Android my app crashes with the message "Desafortunadamente APPNAME se ha detenido".

**Comment by ronocod** [comment]
Can you check the logs on your Android device using logcat? When the error happens it should print out a stacktrace giving more information about the error.

**Comment by ferdelcorro** [comment]
I have this error on my Play Store, this error is only on Android

![captura de pantalla de 2017-10-31 09-33-57](https://user-images.githubusercontent.com/9002601/32225961-ee50deb0-be25-11e7-8b8a-1c8bb2b47119.png)

**Comment by ferdelcorro** [comment]
This is my adb logcat | grep Intercom

![captura de pantalla de 2017-10-31 16-38-27](https://user-images.githubusercontent.com/9002601/32245335-3723067a-be5a-11e7-9c0b-c9928ffc2d6e.png)

**Comment by ronocod** [comment]
Can you run that command without grepping it and send us the part that has the stacktrace?

**Comment by ronocod** [comment]
Can you update to version 4.1.0 of the plugin, run `cordova build android` and see if there are any error messages from Intercom? We added diagnostic logging for common Android issues in this version.

**Comment by ferdelcorro** [comment]
i will try it tomorrow, thanks

**Comment by asgeo1** [comment]
I'm having this same issue, and could see this in my build log:

```
Intercom: Overriding dependency com.android.support:support-v4 version [13.0.0,) --> 26.+
Intercom: Overriding dependency com.android.support:support-v4 version [13.0.0,) --> 26.+
Intercom: Overriding dependency com.android.support:support-v4 version [13.0.0,) --> 26.+
Intercom: Overriding dependency com.android.support:support-v4 version [13.0.0,) --> 26.+
Intercom: Overriding dependency com.android.support:support-v4 version [13.0.0,) --> 26.+
Intercom: Overriding dependency com.android.support:support-v4 version [13.0.0,) --> 26.+
Intercom: Overriding dependency com.android.support:support-v4 version [13.0.0,) --> 26.+
Intercom: Overriding dependency com.android.support:support-v4 version [13.0.0,) --> 26.+
Intercom Android Error:  Build config compile has dependency: com.android.support:support-v13:25.1.0
The Intercom SDK requires version 26.x or higher of this dependency.
```

I guess I need to update that library...

**Comment by asgeo1** [comment]
I've updated the android platform and some plugins, and the "Intercom Android Error" is gone now.

(now I'm on cordova-android 6.3.0)

But still getting the override messages:

```
Intercom: Overriding dependency com.android.support:support-v4 version [13.0.0,) --> 26.+
Intercom: Overriding dependency com.android.support:support-v4 version [13.0.0,) --> 26.+
Intercom: Overriding dependency com.android.support:support-v4 version [13.0.0,) --> 26.+
Intercom: Overriding dependency com.android.support:support-v4 version [13.0.0,) --> 26.+
Intercom: Overriding dependency com.android.support:support-v4 version [13.0.0,) --> 26.+
Intercom: Overriding dependency com.android.support:support-v4 version [13.0.0,) --> 26.+
Intercom: Overriding dependency com.android.support:support-v4 version [13.0.0,) --> 26.+
Intercom: Overriding dependency com.android.support:support-v4 version [13.0.0,) --> 26.+
Intercom: Overriding dependency com.android.support:support-v4 version [13.0.0,) --> 26.+
```

I have no idea where it's getting version 13 from... I've searched through all of my plugins and the platform code, and can't see any reference to support-v4 version 13.

But I'm not sure it matters.  It seems the issue for me, is with the `cordova-plugin-file-opener2` plugin, which has `<framework src="com.android.support:support-v4:+" />` defined, probably causing version of `support-v4` to be loaded which is incompatible with intercom-cordova.

If I remove the `cordova-plugin-file-opener2`, then this plugin works as normal.

**Comment by bboyle18** [comment]
Closing this as its an issue with another cordova lib version. 
Intercom requires version 26.x or higher.
