### ISSUE TITLE
App crashes on android when I tried to open intercom.displayConversationsList

### ISSUE THREAD

**Issue by mmoradeveloper** [intercom/intercom-cordova#214]
## Version info
  - Intercom for Cordova/PhoneGap version: 4.0.0
    name="cordova-plugin-intercom" spec="^4.0.0"
  - iOS/Android OS version:  6  and 7(simulator on android studio)
  - iOS/Android Device: One plus one android 6 over cyanogen and PIXEL 1 running android 7.1.1. over simulator

the app is build over ionic 
##########################
Cordova CLI: 7.0.1 
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
OS: Linux 4.10
Node Version: v6.11.5
##########################

Using cordova-fetch for cordova-android@~6.2.2
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: ************
	Name: ExpertTrades
	Activity: MainActivity
	Android target: android-25
###############################

I  actually have a version of my APP in the store running this version of intercom for Cordova/PhoneGap.
But today I remove the platform and added again and the intercom stop working. I can saw the push notifications and event the messages on the app if I send a message from the web (see pictures attached)
 but when I hit the conversation it or I try to open the conversations using:: 

     if(window.cordova){
	intercom.displayConversationsList();
   }

the app crash.

I attach the log of the simulator device::
## Logs
11-01 19:31:05.156: E/AndroidRuntime(20079): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ionicframework.mobexperttrades512889/io.intercom.android.sdk.activities.IntercomMessengerActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class io.intercom.android.sdk.views.IntercomToolbar
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.os.Looper.loop(Looper.java:154)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at java.lang.reflect.Method.invoke(Native Method)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
11-01 19:31:05.156: E/AndroidRuntime(20079): Caused by: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class io.intercom.android.sdk.views.IntercomToolbar
11-01 19:31:05.156: E/AndroidRuntime(20079): Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class io.intercom.android.sdk.views.IntercomToolbar
11-01 19:31:05.156: E/AndroidRuntime(20079): Caused by: java.lang.reflect.InvocationTargetException
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at io.intercom.android.sdk.inbox.InboxFragment.onCreateView(InboxFragment.java:129)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3231)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3181)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:572)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.app.Activity.performStart(Activity.java:6696)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2628)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.os.Looper.loop(Looper.java:154)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
11-01 19:31:05.156: E/AndroidRuntime(20079): 	at java.lang.reflect.Method.invoke(Native Method)
11-01 19:31:05.157: E/AndroidRuntime(20079): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
11-01 19:31:05.157: E/AndroidRuntime(20079): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
11-01 19:31:05.157: E/AndroidRuntime(20079): Caused by: java.lang.NoSuchMethodError: No static method getFont(Landroid/content/Context;ILandroid/util/TypedValue;ILandroid/widget/TextView;)Landroid/graphics/Typeface; in class Landroid/support/v4/content/res/ResourcesCompat; or its super classes (declaration of 'android.support.v4.content.res.ResourcesCompat' appears in /data/app/com.ionicframework.mobexperttrades512889-1/base.apk)
11-01 19:31:05.157: E/AndroidRuntime(20079): 	at android.support.v7.widget.TintTypedArray.getFont(TintTypedArray.java:119)
11-01 19:31:05.157: E/AndroidRuntime(20079): 	at android.support.v7.widget.AppCompatTextHelper.updateTypefaceAndStyle(AppCompatTextHelper.java:208)
11-01 19:31:05.157: E/AndroidRuntime(20079): 	at android.support.v7.widget.AppCompatTextHelper.loadFromAttributes(AppCompatTextHelper.java:110)
11-01 19:31:05.157: E/AndroidRuntime(20079): 	at android.support.v7.widget.AppCompatTextHelperV17.loadFromAttributes(AppCompatTextHelperV17.java:38)
11-01 19:31:05.157: E/AndroidRuntime(20079): 	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:81)
11-01 19:31:05.157: E/AndroidRuntime(20079): 	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:71)
11-01 19:31:05.157: E/AndroidRuntime(20079): 	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
11-01 19:31:05.157: E/AndroidRuntime(20079): 	at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1024)
11-01 19:31:05.157: E/AndroidRuntime(20079): 	at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1081)
11-01 19:31:05.157: E/AndroidRuntime(20079): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
11-01 19:31:05.157: E/AndroidRuntime(20079): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
11-01 19:31:05.157: E/AndroidRuntime(20079): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
11-01 19:31:05.157: E/AndroidRuntime(20079): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
11-01 19:31:05.157: E/AndroidRuntime(20079): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
11-01 19:31:05.157: E/AndroidRuntime(20079): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
11-01 19:31:05.157: E/AndroidRuntime(20079): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
11-01 19:31:05.157: E/AndroidRuntime(20079): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
11-01 19:31:05.157: E/AndroidRuntime(20079): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
11-01 19:31:05.157: E/AndroidRuntime(20079): 	at android.view.View.inflate(View.java:21010)
11-01 19:31:05.157: E/AndroidRuntime(20079): 	at io.intercom.android.sdk.views.IntercomToolbar.<init>(IntercomToolbar.java:47)
11-01 19:31:05.157: E/AndroidRuntime(20079): 	... 36 more

I attach 2 images ::
![image](https://user-images.githubusercontent.com/16003031/32294501-4928a818-bf3e-11e7-98b2-30fe30e65224.png)

![image](https://user-images.githubusercontent.com/16003031/32294326-b56aef28-bf3d-11e7-90d9-3fb7e3c25d8e.png)

**Comment by ronocod** [comment]
Can you update to version 4.1.0 of the plugin, run `cordova build android` and see if there are any error messages from Intercom? We added diagnostic logging for common Android issues in this version.

**Comment by mmoradeveloper** [comment]
I been working with intercom team this evening installing the version you are telling me and still having the same error.

**Comment by ronocod** [comment]
Your app seems to be using version 27.0.0 of the `support-compat` Support Library, and version 26.1.0 of some other Support Library dependencies. We'll look at updating our SDK to use version 27, in the meantime you can find which plugin is depending on this (probably by using a `+` version in their Gradle dependency which will fetch the latest available version) and force it to use 26.1.0.

**Comment by bboyle18** [comment]
Closing this issue as this can be resolved by forcing your app to use v26.1.0 of the compatibility libs.
As @ronocod said, we will endeavour to provide support for v27.0.0.
