### ISSUE TITLE
Android build failed due to build-extras-intercom.gradle: configuration androidTestCompile

### ISSUE THREAD

**Issue by TMMeijers** [intercom/intercom-cordova#219]
Our build process currently fails because of the build-extras script of the intercom plugin.

## Version info
  - Intercom for Cordova/PhoneGap version: 4.1.0
  - Android/gradle

## Description

Since friday (11-11) our android builds are failing with the following message: 

```FAILURE: Build failed with an exception.

* Where:
Script '**/platforms/android/cordova-plugin-intercom/triggi-build-extras-intercom.gradle' line: 76

* What went wrong:
A problem occurred configuring root project 'android'.
> Resolving configuration 'androidTestCompile' directly is not allowed
```

In the `projectId-build-extras-intercom.gradle (line 72)` file, changing the compileConfig regex to exclude `androidTestCompile` changes the error to `Resolving configuration 'androidTestDebugCompile' directly is not allowed`.
Also excluding that goes on to the next Compile config error. 

Only removing the lines that try to resolve all configurations results in a successful build.

**Comment by ronocod** [comment]
Thanks for reporting this, we'll look into it now.

**Comment by ronocod** [comment]
Can you try with version 4.1.1?

**Comment by TMMeijers** [comment]
I stated above that I exactly tried this solution and that gradle then went on to complain about other configs. To help I made an exhaustive list of the issues we encounter during the build process:
```
compileOnly
debugCompileOnly
debugUnitTestCompileClasspath
releaseCompileClasspath
releaseCompileOnly
releaseUnitTestCompileClasspath
testCompileOnly
testDebugCompile
testReleaseCompile
testReleaseCompileOnly
testDebugCompileOnly
debugCompile
debugCompileClasspath
androidTestCompileOnly
androidTestDebugCompileOnly
debugAndroidTestCompileClasspath
androidTestCompile
androidTestDebugCompile
releaseCompile
```

They are captured by the following regex: `/^(debug|release|(androidT|t)est|)?\w*[cC]ompile(Only|Classpath)?$/`

Using this regex in the `Matcher isCompileConfig` shuts gradle up about manually resolving configurations. I'd make a pull request but you might want to split up the regex for it to be more readable.

**Comment by ronocod** [comment]
This is really useful, thanks. I think based on that list we should only be checking the `compile` configuration, so we won't need a regex at all. I'll make a PR soon to only apply the checks to that configuration.

**Comment by thomaslindstrom** [comment]
Is there a temporary fix for this?

**Comment by ronocod** [comment]
I have a PR up to fix this now: https://github.com/intercom/intercom-cordova/pull/222

**Comment by TMMeijers** [comment]
It works! Many thanks, and sorry for the delay.
