### ISSUE TITLE
Intercom is not defined in JS

### ISSUE THREAD

**Issue by yazan-boshmaf-hs** [intercom/intercom-cordova#22]
I have a Cordova project set up. I'm using Intercom and have added the the plugin as describes in Github (https://github.com/intercom/intercom-cordova).

When I run the application, it comes to the foreground but gets stuck. Looking at the DevTools console output from the ADT plugin, JS throws "Uncaught ReferenceError: intercom is not defined". The source is the script where I call "intercom.registerUnidentifiedUser();".

Any ideas? Why is "intercom" not imported properly?

**Comment by jtreanor** [comment]
Hi @yazan-boshmaf-hs 

I am not sure how this could be happening. Can you tell me how you installed Intercom in your project?

**Comment by yazan-boshmaf-hs** [comment]
Hi @jtreanor. My project was misconfigured. It's all good now, thanks!
