### ISSUE TITLE
FCM Push notification is not being received

### ISSUE THREAD

**Issue by lucasfeandrade** [intercom/intercom-cordova#224]
## Version info
  - Intercom for Cordova/PhoneGap version: 4.1.2
  - iOS/Android OS version: 4.3.1/6.3.0
  - iOS/Android Device: Nexus 5 API 25
  - SDK Version: 26.0.1

## Plugin List 
  - com.megster.cordova.FileChooser 0.0.0 "File Chooser"
  - com.napolitano.cordova.plugin.intent 0.1.3 "IntentPlugin"
  - cordova-fabric-plugin 1.1.10 "cordova-fabric-plugin"
  - cordova-plugin-android-permissions 1.0.0 "Permissions"
  - cordova-plugin-camera 3.0.0 "Camera"
  - cordova-plugin-datepicker 0.9.3 "DatePicker"
  - cordova-plugin-file 5.0.0 "File"
  - cordova-plugin-file-transfer 1.7.0 "File Transfer"
  - cordova-plugin-firebase 0.1.19 "Google Firebase Plugin"
  - cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
  - cordova-plugin-image-picker 1.1.1 "ImagePicker"
  - cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
  - cordova-plugin-intercom 4.1.2 "Intercom"
  - cordova-plugin-network-information 1.3.4 "Network Information"
  - cordova-plugin-splashscreen 4.1.0 "Splashscreen"
  - cordova-plugin-statusbar 2.3.0 "StatusBar"
  - cordova-plugin-whitelist 1.3.3 "Whitelist"
  - cordova-sqlite-storage 2.1.2 "Cordova sqlite storage plugin"
  - ionic-plugin-keyboard 2.2.1 "Keyboard"

## project.properties

  - target=android-26
  - android.library.reference.1=CordovaLib
  - cordova.gradle.include.1=cordova-fabric-plugin/astreaapp-build-extras.gradle
  - cordova.system.library.1=com.android.support:support-v4:24.1.1+
  - cordova.gradle.include.2=cordova-plugin-firebase/astreaapp-build.gradle
  - cordova.system.library.2=com.google.firebase:firebase-core:+
  - cordova.system.library.3=com.google.firebase:firebase-messaging:+
  - cordova.system.library.4=com.google.firebase:firebase-crash:+
  - cordova.system.library.5=com.google.firebase:firebase-config:+
  - cordova.system.library.6=com.google.android.gms:play-services-analytics:+
  - cordova.gradle.include.3=cordova-plugin-intercom/astreaapp-intercom.gradle
  - cordova.gradle.include.4=cordova-plugin-intercom/astreaapp-build-extras-intercom.gradle

## Expected behavior
A notification should be received when someone sends a message with intercom (Using FCM).

## Actual behavior
The message is not displayed (even with app in background) and nothing is displayed in adb logcat. In order to run the app without errors I had to comment the following line inside cordova-plugin-intercom/src/android/intercom.gradle:

```
// apply plugin: com.google.gms.googleservices.GoogleServicesPlugin
``` 

Anyway the push notification does not work.

I have also tried to use GCM, it works correctly if I remove the following plugins:

  - cordova-plugin-firebase 0.1.19 "Google Firebase Plugin"
  - cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"

But, when I add it the app crashes. The log displayed at adb logcat is here: 

https://gist.github.com/lucasfeandrade/337b26b96484dbeb42c97adfed9c8316

**Comment by ronocod** [comment]
When you run `cordova build android` are there any log messages mentioning Intercom?

**Comment by lucasfeandrade** [comment]
Hello ronocod :) 
There are no messages mentioning intercom while running cordova build android.

**Comment by xfernandez** [comment]
I am having the same issue here.

Just to comment that I am forcing 3.1.1 as com.google.gms and 11.0.4 as com.google.firebase

**Comment by xfernandez** [comment]
BTW, since it's important for my project. Is it possibble to downgrade to 3.2.2 version of Intercom library?

**Comment by xfernandez** [comment]
I am doing some digging, I am under an Ionic 2 project. I am not really an expert but comparing with Android FCM config implementation (I am using cordova) on Intercom seems that it's not adding io.intercom.android:intercom-sdk-fcm into build.gradle.  Looking into intercom.gradle seems that code tries to do it. Maybe it's not working as expected?

**Comment by Ycfx** [comment]
Same problem here

**Comment by augustoverzbickas** [comment]
Same problem here!

**Comment by htsnet** [comment]
+1

**Comment by joaohencke** [comment]
Same problem here +1

**Comment by Upperfoot** [comment]
I'm having the same problem as well, it did work previously which is very strange. Was something changed recently in the library or the intercom API?

**Comment by bboyle18** [comment]
We are aware of this issue with sending FCM push notifications.
We're investigating the best way to fix this and will provide an update here.
Thanks for your patience while we resolve this.
Brian

**Comment by sebagon** [comment]
same problem here

**Comment by Upperfoot** [comment]
@bboyle18 Any update on this?

**Comment by jpike88** [comment]
@bboyle18 are you guys still on holiday or something? This plugin overall is getting really out of date here...

https://github.com/intercom/intercom-cordova/issues/231

**Comment by edyonil** [comment]
Any update on this?

**Comment by bboyle18** [comment]
Hi @edyonil 👋 

We're hoping to start working on a fix for this in the coming days.

Brian

**Comment by Upperfoot** [comment]
@bboyle18 Any news on this? We've been without Intercom push notifications for Android for about a month so far, we really need this fix.

**Comment by bboyle18** [comment]
Hi @Upperfoot 👋 
We're actively working on this at the moment.
Its not an insignificant change to support this, so its going to take a little more time.
We're provide updates here when we have something to ship.

Cheers

Brian

**Comment by Upperfoot** [comment]
Bit of an update, GCM works fine if you absolutely want push notifications; although Intercom's push notifications are doubled up if you are using FCM and GCM together.

The fix for the above is to change your plugins so that they utilise solely GCM rather than FCM for push notifications.

It's a bit of a workaround, but its better than the alternative (no push notifications).

**Comment by ronocod** [comment]
Can you try upgrading to 5.1.1 of our plugin and following the steps I outlined here please: https://github.com/intercom/intercom-cordova/issues/203#issuecomment-368511465

**Comment by ronocod** [comment]
We are moving all our issues support to our [Intercom Developer Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). If you bump into further problems or need updates on this issue, just start a conversation using Intercom there and it will be immediately routed to our Customer Support Engineers.
