### ISSUE TITLE
Upload to iTunes Connect: "Missing Push Notification Entitlement"

### ISSUE THREAD

**Issue by JorisDebonnet** [intercom/intercom-cordova#227]
## Version info
  - Intercom for Cordova/PhoneGap version: 4.5.2
  - iOS OS version: N/A
  - iOS Device: N/A
  - Xcode version: 9.1

## Expected behavior
The issue is when sending the app to iTunes Connect. The issue description matches 100% the following issue on intercom-ios: https://github.com/intercom/intercom-ios/issues/88. However that one looks solved, so this may be specific to this Cordova plugin. 

The expectated behavior is that since we have not used anything related to notifications, iTunes Connect should not complain about "Missing Push Notification Entitlement".

## Actual behavior
After uploading the binary, we do get a notice about "Missing Push Notification Entitlement". It is just a warning, so we can still publish.

## Steps to reproduce
 1. Install this plugin
 2. Use .register, .updateUser, .registerIdentifiedUser and .displayMessenger (but no other methods).
 3. Upload to iTunes Connect

## Logs
Dear developer,
We have discovered one or more issues with your recent delivery for "...". Your delivery was successful, but you may wish to correct the following issues in your next delivery: 
Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. Xcode 8 does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1. 
After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect. 
Regards,
The App Store team

**Comment by skylerwshaw** [comment]
@JorisDebonnet Are you still seeing this? Which Intercom version are you seeing in `platforms/ios/Podfile.lock`?

**Comment by bboyle18** [comment]
Hi @JorisDebonnet 👋 
I'm going to close this issue. Please feel free to reopen it if you are still experiencing this issue.
Please include your version of the intercom plugin.

Thanks

Brian
