### ISSUE TITLE
Open help portal functionality

### ISSUE THREAD

**Issue by jpike88** [intercom/intercom-cordova#229]
There should be a way to open the help portal in a browser window, and a way for the credentials of the user to be passed along with it.

**Comment by skylerwshaw** [comment]
Hi @jpike88,
1. Are you requesting the Educate feature to be available in the mobile SDK?
2. Can you please elaborate what you mean by passing user credentials?

**Comment by jpike88** [comment]
Essentially yeah I'm asking for the Educate feature. I'll message them direct
