### ISSUE TITLE
What is sender_id?

### ISSUE THREAD

**Issue by sisodiakaran** [intercom/intercom-cordova#23]
Hello,

In [this](https://github.com/intercom/intercom-cordova#push-notifications) document I am unable to determine what is "sender_id" and where to get this?

Is this something "SENDER_ID is the google api project ID"?

Thanks...

**Comment by DaleCantwell** [comment]
Hi @sisodiakaran 

The SENDER_ID is a unique key you get from on the Google Developers Console. It is used to identify which app may talk to the Google project you set up. 
Here is Googles definition: https://developers.google.com/cloud-messaging/gcm#senderid
We have a guide on setting up a native GCM implementation but you may find a lot of the steps very useful for cordova setup too. The step linked below shows an example Sender_id
http://docs.intercom.io/Install-on-your-mobile-product/using-google-cloud-messaging-gcm-with-intercom-for-android#-step-5-setup-application-to-receive-push-
