### ISSUE TITLE
Push Notifications are not received on iOS devices with app closed or in background

### ISSUE THREAD

**Issue by milions** [intercom/intercom-cordova#230]
## Version info
- Intercom for Cordova/PhoneGap version: 4.1.0
- Cordova version: 6.5.0
- Cordova platform: ios 4.3.1
- iOS devices: iphone 6 with iOS 11, iphone 5, 5s with iOS 9

## Plugin list
com.phonegap.plugins.ParsePushPlugin 0.3.0 "ParsePushPlugin"
com.soldo.plugin.keychain 0.0.1 "KeychainPlugin"
com.verso.cordova.clipboard 0.1.0 "Clipboard"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.6 "Console"
cordova-plugin-crop-mod 1.0.0 "CropPlugin"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.5 "Device"
cordova-plugin-file 4.3.2 "File"
cordova-plugin-file-transfer 1.6.2 "File Transfer"
cordova-plugin-globalization 1.0.6 "Globalization"
cordova-plugin-inappbrowser 1.7.0 "InAppBrowser"
cordova-plugin-intercom 4.1.0 "Intercom"
cordova-plugin-network-information 1.3.2 "Network Information"
cordova-plugin-screen-orientation 2.0.0 "Screen Orientation"
cordova-plugin-splashscreen 4.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.2 "Whitelist"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"

## Expected behavior
A notification should be received when someone sends a message with intercom.

## Actual behavior
Notification is not received if the app is closed or in background. When app is open, all notifications are shown properly.

**Comment by skylerwshaw** [comment]
@milions 
* Are you reproducing this on a physical device or simulator?
* Are you able to reproduce this on `intercom-cordova` 5.0.0 released today?: https://github.com/intercom/intercom-cordova/releases

If the answer to both questions is yes, can you please message into Intercom via the in-app messenger in your Intercom dashboard with a user example (user_id or email) so we can investigate on our end?

**Comment by bboyle18** [comment]
Hi @milions 
I'm going to close this issue as customer should be in contact with Intercom support as requested.
Please feel free to reopen if you are still experiencing this problem.

Thanks

Brian
