### ISSUE TITLE
Move plugin directory to root

### ISSUE THREAD

**Issue by jpike88** [intercom/intercom-cordova#232]
I use over 20 different plugins, this is the only one that has the plugin itself in a subdirectory. Makes a it a pain for forking or testing from the CLI.

Please move it to root as per convention

**Comment by skylerwshaw** [comment]
@jpike88 It's unclear what you're requesting. Can you please provide an example?

**Comment by jpike88** [comment]
Just move the contents of the intercom-plugin folder to the top directory level, so the package.json sits in the top level directory.

**Comment by skylerwshaw** [comment]
Adding a local version of any plugin repo should be quite easy:
`cordova plugin add ~/developer/intercom-cordova/intercom-plugin` ✨

We'll look at changing this if it's the convention but it's low priority and low impact. We acquired this plugin from a third party developer. Without looking into commit history, it may very well be a holdover from that time.

**Comment by bboyle18** [comment]
This is not something that is going to be part of the roadmap any time soon. As @skylerwshaw has said, its low impact.
