### ISSUE TITLE
I can't do intercom push notifications (GCM or FCM) work in my ionic 2 app

### ISSUE THREAD

**Issue by xfernandez** [intercom/intercom-cordova#234]
## Version info
  - Intercom for Cordova/PhoneGap version:
Ionic info:
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 1.3.6
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.1.1

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    Node              : v6.9.2
    npm               : 3.10.9
    OS                : macOS Sierra
    Xcode             : Xcode 9.2 Build version 9C40b
  - iOS/Android OS version: Android 8.00
  - iOS/Android Device: ONEPLUS A3003

## Expected behavior
Push notifications in FCM or GCM works
## Actual behavior
On FCM nothing fails but anything happens (in ios works) but any user with android device has the user variable  Enabled Push Messaging  as unknown
In GCM (no tried in ios) it doesn't work, the app doesn't start with the log included in the section

Note that I understand that app id and keys are ok because other intercom things like register user, events, chat are working perfectly. As well in Ios notifications works with FCM

## Steps to reproduce
 1. a part of my config.xml file:
<preference name="webviewbounce" value="false" />
    <preference name="UIWebViewBounce" value="false" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="android-minSdkVersion" value="16" />
    <preference name="android-targetSdkVersion" value="26" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreen" value="false" />
    <preference name="AutoHideSplashScreen" value="false" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="intercom-app-id" value="gnik7ff6" />
    <preference name="intercom-ios-api-key" value="ios_sdk-XXXXXXXXXXX" />
    <preference name="intercom-android-api-key" value="android_sdk-XXXXXXXXXXX" />
    <preference name="intercom-android-sender-id" value="XXXXXXXXXXXX" />
    <preference name="intercom-android-push-type" value="GCM" />
    <platform name="android">
        <preference name="SplashScreenDelay" value="3000" />
        <preference name="orientation" value="portrait" />
        <preference name="AndroidLaunchMode" value="singleTask" />
        <allow-intent href="market:*" />
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />

 2.  Just run the app ionic. (ionic cordova run android --livereload)
 3. fails on start

## Logs

01-12 14:37:18.436  3692  3692 E Intercom-Cordova: ERROR: Something went wrong when initializing Intercom. Have you set your APP_ID and ANDROID_API_KEY?
01-12 14:37:18.436  3692  3692 D AndroidRuntime: Shutting down VM
01-12 14:37:18.438  3692  3692 E AndroidRuntime: FATAL EXCEPTION: main
01-12 14:37:18.438  3692  3692 E AndroidRuntime: Process: com.skingdom.app, PID: 3692
01-12 14:37:18.438  3692  3692 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.skingdom.app/com.skingdom.app.MainActivity}: java.lang.IllegalStateException: Please call Intercom.initialize() before requesting the client.
01-12 14:37:18.438  3692  3692 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
01-12 14:37:18.438  3692  3692 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3046)
01-12 14:37:18.438  3692  3692 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(Unknown Source:0)
on01-12 14:37:18.438  3692  3692 E AndroidRuntime:      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
01-12 14:37:18.438  3692  3692 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:105)
01-12 14:37:18.438  3692  3692 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
01-12 14:37:18.438  3692  3692 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6809)
01-12 14:37:18.438  3692  3692 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-12 14:37:18.438  3692  3692 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
01-12 14:37:18.438  3692  3692 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
01-12 14:37:18.438  3692  3692 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Please call Intercom.initialize() before requesting the client.
01-12 14:37:18.438  3692  3692 E AndroidRuntime:        at io.intercom.android.sdk.Intercom.client(Intercom.java:115)
01-12 14:37:18.438  3692  3692 E AndroidRuntime:        at io.intercom.android.sdk.IntercomBridge$2.run(IntercomBridge.java:58)
01-12 14:37:18.438  3692  3692 E AndroidRuntime:        at android.app.Activity.runOnUiThread(Activity.java:6175)
01-12 14:37:18.438  3692  3692 E AndroidRuntime:        at io.intercom.android.sdk.IntercomBridge.onStart(IntercomBridge.java:53)
01-12 14:37:18.438  3692  3692 E AndroidRuntime:        at org.apache.cordova.PluginManager.onStart(PluginManager.java:275)
01-12 14:37:18.438  3692  3692 E AndroidRuntime:        at org.apache.cordova.CordovaWebViewImpl.handleStart(CordovaWebViewImpl.java:462)
01-12 14:37:18.438  3692  3692 E AndroidRuntime:        at org.apache.cordova.CordovaActivity.onStart(CordovaActivity.java:303)
01-12 14:37:18.438  3692  3692 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1412)
01-12 14:37:18.438  3692  3692 E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:7015)
01-12 14:37:18.438  3692  3692 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2909)

**Comment by skylerwshaw** [comment]
>01-12 14:37:18.436 3692 3692 E Intercom-Cordova: ERROR: Something went wrong when initializing Intercom. Have you set your APP_ID and ANDROID_API_KEY?
Have you specified these values in your config.xml?

Additionally, can you please update to 5.0.0 released today and try and reproduce? Note, this will require placing your google-services.json in your project root directory per our documentation and the release notes:
https://github.com/intercom/intercom-cordova/releases

**Comment by xfernandez** [comment]
Is it a must to use cordova-android 7.0.0

**Comment by skylerwshaw** [comment]
To upgrade to cordova-plugin-intercom 5.0.1, cordova-android 7.0.0 is required due to the file location changes explained here: https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html

Is there a reason you don't want to run the latest Cordova?

Additionally, based on the errors you posted above, it seems that you were affected by a change that was fixed today by 5.0.1 here:
https://github.com/intercom/intercom-cordova/releases/tag/5.0.1

**Comment by xfernandez** [comment]
I wanted to avoid just because I don't want now to review compatibility with other libraries

I will try with 5.0.1

**Comment by skylerwshaw** [comment]
That's a fair concern, we may release another 4.x version with the fix contained in 5.0.1 but are constrained on time at the moment.

**Comment by xfernandez** [comment]
Hi, I have tried 5.0.1 with cordova 7.1.0. Now all compiles but... now the user is not registered in intercom at all, then, not good :(

My question is... I am using an intercom ionic plugin on top of intercom cordova library... maybe is this generating problems with this new 5.0.1? Or maybe it's another thing? Of course, we are using in production and working with cordova-intercom version 4.2.1

Is there a compatibility requirement with this version? I production I use 6.2.3 and in this new approach it asks for 6.3.0

**Comment by xfernandez** [comment]
Installing "cordova-plugin-intercom" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 6.3.0, failed version requirement: >=7.0.0

Ok, I continue updating libraries...

**Comment by skylerwshaw** [comment]
@xfernandez please see the release notes for 5.0.0 and 5.0.1: https://github.com/intercom/intercom-cordova/releases

**Comment by xfernandez** [comment]
Yes! I did, thanks. I read "Supports cordova-android 7.0.0". I expected not as a must requirement. I am trying

**Comment by ronocod** [comment]
We are moving all our issues support to our [Intercom Developer Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). If you bump into further problems or need updates on this issue, just start a conversation using Intercom there and it will be immediately routed to our Customer Support Engineers.
