### ISSUE TITLE
ionic cordova build failed (fatal error: 'Intercom/Intercom.h' file not found)

### ISSUE THREAD

**Issue by jaclynjessup** [intercom/intercom-cordova#235]
When attempting to create an iOS build using `$ ionic cordova build ios --release` the Intercom.h file is not found. You can follow the manual installation steps [here](http://github.com/intercom/intercom-ios) and it will build successfully.

However if you ever run
```
ionic cordova platform rm ios
ionic cordova platform add ios
ionic cordova run ios
```
You have you go through the manual dragging of `Intercom.framework` to the "Embedded Binaries" again.

How do I get the build to succeed without having to follow the manual installation of Intercom? 

## Version info
  - Intercom for Cordova/PhoneGap version: 4.1.2
  - iOS OS version: 11.2
  - iOS Device: Universal
  - cordova-ios: ^4.4.0
```
$ionic info
cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:
    cordova (Cordova CLI) : 7.1.0

local packages:
    @ionic/app-scripts : 3.1.7
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:
    Node  : v8.9.2
    npm   : 3.10.0
    OS    : macOS High Sierra
    Xcode : Xcode 9.2 Build version 9C40b

Environment Variables:
    ANDROID_HOME : not set

Misc:
    backend : pro
```

## Expected behavior
Building an ionic app for iOS with intercom included when running `$ ionic cordova build ios --release`

## Actual behavior
Build fails with Log:
```
[projectpath]/Plugins/cordova-plugin-intercom/AppDelegate+IntercomPush.m:2:9: fatal error: 'Intercom/Intercom.h' file not found
 #import <Intercom/Intercom.h>
         ^
1 error generated.
 
** BUILD FAILED **
```

## Steps to reproduce
 1.  ionic cordova platfrom add ios
 2. ionic cordova build ios --prod --release

**Comment by Coolcat13** [comment]
I can confirm this issue with v 4.1.2 and v4.0.0 of the plugin - cannot build/run for ios (fatal error: 'Intercom/Intercom.h' file not found) Thanks for updating us asap. The strange thing is that I'm pretty sure 4.0.0 of intercom plugin worked before. I remember the build process doing some cocoapod "stuff" on the CLI, but I'm not seeing this happen anymore, I wonder if it's linked?

**Comment by Coolcat13** [comment]
Update: turns out cocoapods got uninstalled when I upgraded either macOS or Xcode - reinstalling cocoapods seems to have done the trick - for some reason the "cordova prepare" step doesn't complain if cocoapods isn't installed, but "cordova requirements" will show it as "not installed" - This is what I did to install: sudo gem install cocoapods

Re-ran my prepare and build, and it worked fine.

Hope this helps someone somewhere ;-)
