### ISSUE TITLE
Intercom Nav Bar covers conversation list on iPhone X

### ISSUE THREAD

**Issue by NickMele** [intercom/intercom-cordova#238]
## Version info
  - Intercom for Cordova/PhoneGap version: 4.1.2
  - iOS/Android OS version: iOS 11.2
  - iOS/Android Device: iPhone X

## Expected behavior
The conversation list should start below the navigation bar, and not be overlapped by it.

## Actual behavior
When viewing the conversation list in Intercom, the navigation bar is overlapping the list and the first conversation is always cut off

From the research I have done trying to figure this out. I think it may have something to do with the `cordova-plugin-ionic-webview` having the following code:
```
    #if __IPHONE_OS_VERSION_MAX_ALLOWED >= 110000
    if (@available(iOS 11.0, *)) {
      [wkWebView.scrollView setContentInsetAdjustmentBehavior:UIScrollViewContentInsetAdjustmentNever];
    }
    #endif
```

I am not positive about this, or sure what change i need to make this stop happening.

## Steps to reproduce
 1. Install intercom 4.1.2 and `cordova-plugin-ionic-webview`
 2. Run on iPhone X
 3. Open the intercom conversation list with a conversation in the list. Notice that the first conversation is cutoff

## Screenshot
![simulator screen shot - iphone x - 2018-01-22 at 13 51 23](https://user-images.githubusercontent.com/2179012/35238650-227305aa-ff7c-11e7-854d-20f0a848de17.png)

**Comment by cindyliu-yb** [comment]
Same here on ios 11

**Comment by bboyle18** [comment]
Hi @NickMele & @cindyliu-yb 👋 

Thanks for reporting this.
It definitely sounds like your app is interfering with Intercom in some way. I've tested this out on [our sample Cordova app](https://github.com/intercom/intercom-cordova/tree/5.0.0/Example) and have not seen this problem.
Generally with issues like this, its usually some global setting/configuration in your app that impacts on Intercom and causes UI issues.
@NickMele Your suggestion about `contentInset` could be correct. The best way to figure this out is if you disable any code that you think might be impacting on Intercom.

If you find the cause, please let us know and we can do our best to prevent Intercom from being affected by things like this in the future.

Thanks

Brian

**Comment by NickMele** [comment]
@bboyle18 - I don't want to disable code that is in another library we are using without knowing what disabling/changing it will do to other parts of the application.

Do you have any idea what the line i suggested above should be changed to in order to prevent it from interfering with the intercom plugin

**Comment by ronocod** [comment]
We are moving all our issues support to our [Intercom Developer Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). If you bump into further problems or need updates on this issue, just start a conversation using Intercom there and it will be immediately routed to our Customer Support Engineers.

We're currently working on solving this, so for future updates you should contact us through Intercom on that site.
