### ISSUE TITLE
When I add the Intercom plugin my cordova app crashes

### ISSUE THREAD

**Issue by JammiM** [intercom/intercom-cordova#239]
## Version info
  - Intercom for Cordova version: 8.0.0
  - iOS/Android OS version:
  - iOS/Android Device:
  - Node version: v8.1.4

## Plugins:
  - cordova-plugin-intercom
  - cordova-plugin-whitelist

## Expected behavior
  - App should work

## Actual behavior
  - Not compliling

## Steps to reproduce
 1.  cordova create basic app 
 2.  cordova platform add android and cordova platform add browser
 3.  cordova run android

I create a blank cordova app, I run it on android emulator and it's compiles fine.

I add the intercom plugin
**cordova plugin add cordova-plugin-intercom**
I add the api keys to the config.xml file

when I run the android emulator it crashes, I get this error
**"I get HelloCordova has stopped"**

but when I remove the plugin it works fine

**cordova plugin remove cordova-plugin-intercom**

I have subscribed to a free intercom trial.

When I test in the browser I get this error in the console
cordova run browser, this happens
**Error: exec proxy not found for :: Intercom :: registerUnidentifiedUser**           on line   **cordova.js:1003** 

\platforms\browser\platform_www\cordova.js
![1003](https://user-images.githubusercontent.com/5257234/35247912-0122dbb2-ffc4-11e7-93a9-656f056a5a13.png)

I have also compiled to a .apk file and installed and android phone and still I get the same bug
**"I get HelloCordova has stopped"**

## Config.xml file:

```
<?xml version='1.0' encoding='utf-8'?>
<widget id="io.cordova.hellocordova" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>HelloCordova</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <preference name="intercom-app-id" value="888888" />
    <preference name="intercom-ios-api-key" value="ios_sdk-888888888" />
    <preference name="intercom-android-api-key" value="android_sdk-88888888" />
    <plugin name="cordova-plugin-intercom" spec="^5.0.0" />
    <engine name="browser" spec="^5.0.3" />
    <engine name="android" spec="^6.4.0" />
</widget>

```

888888 is dummy numbers

**Comment by skylerwshaw** [comment]
@JammiM Can you please update to 5.0.1? This issue is addressed in this update.
https://github.com/intercom/intercom-cordova/releases/tag/5.0.1
