### ISSUE TITLE
Keys not getting set properly when installing w/ xcode 7

### ISSUE THREAD

**Issue by polomasta** [intercom/intercom-cordova#24]
After upgrading to xcode 7 and trying to install this plugin, it seems to no longer be properly updating the .plist with the `api_key` and `app_id` ... xcode also seems to not like it when I try to set this manually.

Has anyone else seen these or know how to fix it?

**Comment by jtreanor** [comment]
Hi @polomasta 

What version of the plugin are you using?

We changed how keys are set in 1.1.0. You will need something like this in your `config.xml`:

```
<preference name="intercom-app-id" value="your_app_id"/>
<preference name="intercom-ios-api-key" value="ios_sdk-..."/>
<preference name="intercom-android-api-key" value="android_sdk-..."/>
```

**Comment by polomasta** [comment]
@jtreanor ahhhh I had missed that change.. Thanks!

**Comment by jtreanor** [comment]
No problem :smile: Glad you got it working.
