### ISSUE TITLE
Ionic incompatible with cordova 7.0

### ISSUE THREAD

**Issue by rodrigoreal** [intercom/intercom-cordova#242]
I can't use the 5x version with ionic, atm ionic is incompatible with cordova 7.0 as you can see here https://ionic.zendesk.com/hc/en-us/articles/360000020508-Android-builds-with-cordova-android-7-0-0-failing
I'm trying to add an old version of the plugin to work with cordova 6.4 `ionic cordova plugin add cordova-plugin-intercom@4.1.2`
But i'm getting this error: `Plugin doesn't support this project's cordova-android version. cordova-android: 6.4.0, failed version requirement: >=7.0.0`
Is there any version of the plugin i can use with cordova < 7.0?

## Version info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.1
    ios-sim           : 5.0.8
    Node              : v6.9.5
    npm               : 5.3.0
    OS                : macOS Sierra
    Xcode             : Xcode 9.2 Build version 9C40b

**Comment by skylerwshaw** [comment]
`4.1.2` as shown in https://github.com/intercom/intercom-cordova/releases/ supports `cordova-android: 6.4.0`. I'm unsure how you `ionic cordova plugin add` command is resolving the specified version but you may want to check that your `config.xml` and `package.json` specify `4.1.2`.

**Comment by rodrigoreal** [comment]
Sorry about that, it was getting from and old version.
