### ISSUE TITLE
Ionic v1 : intercom plugin not displaying in Ionic lab

### ISSUE THREAD

**Issue by JammiM** [intercom/intercom-cordova#243]
The intercom plugin is not displaying when I use "Ionic Lab", and I get no errors in the console.

I don't know if this is a problem with Ionic lab or your plugin.

https://github.com/intercom/intercom-cordova

I'm using intercom 5.0.1 and the android sdk target is 19

**It works fine when I emulate the app on a android.**

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

## global packages:

    cordova (Cordova CLI) : 8.0.0
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

## local packages:

    Cordova Platforms : android 7.0.0
    Ionic Framework   : ionic1 1.3.4

## System:

    Node : v8.1.4
    npm  : 5.0.3
    OS   : Windows 7

## Environment Variables:

    ANDROID_HOME : not set

## Misc:

    backend : pro

**Comment by skylerwshaw** [comment]
Can you please open a support conversation with us through the Intercom messenger located in your Intercom dashboard? Reason being that we may need account details while troubleshooting. Please cite this issue issue URL. Thanks!

**Comment by bboyle18** [comment]
Closing this issue as support was redirected to Intercom
