### ISSUE TITLE
cordova run does not perform scripts/checkForUpdate.js hook

### ISSUE THREAD

**Issue by seanbriceland** [intercom/intercom-cordova#248]
## Version info
  - Intercom for Cordova/PhoneGap version: 5.0.2 (and likely others)
  - iOS/Android OS version: cordova-ios 4.5.4
  - iOS/Android Device: All ios

## Expected behavior

When executing:

```sh
cordova platform add ios
cordova run ios --device
```

XCode CLI (via the above cordova commands) should run:

```
PhaseScriptExecution [CP]\ Copy\ Pods\ Resources /Users/seanbriceland/Library/Developer/Xcode/DerivedData/Acquire_by_Pointman-hhcvmuztexdwzbbsronjjqutamfa/Build/Intermediates.noindex/ArchiveIntermediates/Acquire\ by\ Pointman/IntermediateBuildFilesPath/Acquire\ by\ Pointman.build/Debug-iphoneos/Acquire\ by\ Pointman.build/Script-2B3D684E3C30682C14398E4D.sh
```

This properly copies over the assets, specifically icons. When app runs, the plugin icons are displayed.

## Actual behavior

```
PhaseScriptExecution [CP]\ Copy\ Pods\ Resources /Users/seanbriceland/Library/Developer/Xcode/DerivedData/Acquire_by_Pointman-hhcvmuztexdwzbbsronjjqutamfa/Build/Intermediates.noindex/ArchiveIntermediates/Acquire\ by\ Pointman/IntermediateBuildFilesPath/Acquire\ by\ Pointman.build/Debug-iphoneos/Acquire\ by\ Pointman.build/Script-2B3D684E3C30682C14398E4D.sh
```

The above is not not run when executing `cordova run ios` after a fresh `cordova platform add`. This results in the the intercom messanger missing all icons from the plugin on `ios`. Android is working just fine 👍 .

Now, if we exectue:

```
cordova platform add ios
cordova build ios
cordova run ios --device
``` 

Everything works as expected. But this is because the `scripts/checkForUpdate.js` is assigned to `type=before_build`:

`<hook type="before_build" src="scripts/checkForUpdate.js" />`

changing this to:

~`<hook type="before_prepare" src="scripts/checkForUpdate.js" />`~

**EDIT** `after_prepare` might be better:
`<hook type="after_prepare" src="scripts/checkForUpdate.js" />`

will ensure it is executed with `cordova run` as well as `cordova build`.

Also, here is the location in the current `plugin.xml`:

https://github.com/intercom/intercom-cordova/blob/master/intercom-plugin/plugin.xml#L25

For quick reference, here is there hook documentation:

https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/

**Comment by ronocod** [comment]
The changes in your PR have been released as part of version 5.1.0, so this should be fixed now.
