### ISSUE TITLE
Problem to build IOS App: 'Intercom/Intercom.h' file not found

### ISSUE THREAD

**Issue by rodneicouto** [intercom/intercom-cordova#255]
I get the problem both in my application and in the example application

## Version info
  - Intercom for Cordova/PhoneGap version: 5.0.2
  - Cordova version: 8.0.0

## Actual behavior

Build problem: the application can`t be compiled.

## Steps to reproduce

 1. _Download the intercom-cordova example from GitHub_  
 2. npm install 
 3. cordova platform add ios
 4. cordova plugin add cordova-plugin-intercom
 5. _Change in xcode the "Signing Team"_
 7. cordova run ios

## Logs

CompileC /Users/rodneicouto/Library/Developer/Xcode/DerivedData/Intercom_Cordova-goaiddauftavsxfdmnxpvtybfzmm/Build/Intermediates.noindex/ArchiveIntermediates/Intercom\ Cordova/IntermediateBuildFilesPath/Intercom\ Cordova.build/Debug-iphoneos/Intercom\ Cordova.build/Objects-normal/armv7/IntercomBridge.o Intercom\ Cordova/Plugins/cordova-plugin-intercom/IntercomBridge.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/rodneicouto/lixo3/Example/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/rodneicouto/Dev/Tools/apache-ant-1.9.4/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin/:/Users/rodneicouto/Dev/Tools/apache-ant-1.9.4:/Users/rodneicouto/Dev/Tools/apache-maven-3.3.9/bin:/Users/rodneicouto/Dev/Tools/GO/go//bin:/Users/rodneicouto/Dev/Tools/gradle-3.3/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=204 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/rodneicouto/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/rodneicouto/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -iquote /Users/rodneicouto/Library/Developer/Xcode/DerivedData/Intercom_Cordova-goaiddauftavsxfdmnxpvtybfzmm/Build/Intermediates.noindex/ArchiveIntermediates/Intercom\ Cordova/IntermediateBuildFilesPath/Intercom\ Cordova.build/Debug-iphoneos/Intercom\ Cordova.build/Intercom\ Cordova-generated-files.hmap -I/Users/rodneicouto/Library/Developer/Xcode/DerivedData/Intercom_Cordova-goaiddauftavsxfdmnxpvtybfzmm/Build/Intermediates.noindex/ArchiveIntermediates/Intercom\ Cordova/IntermediateBuildFilesPath/Intercom\ Cordova.build/Debug-iphoneos/Intercom\ Cordova.build/Intercom\ Cordova-own-target-headers.hmap -I/Users/rodneicouto/Library/Developer/Xcode/DerivedData/Intercom_Cordova-goaiddauftavsxfdmnxpvtybfzmm/Build/Intermediates.noindex/ArchiveIntermediates/Intercom\ Cordova/IntermediateBuildFilesPath/Intercom\ Cordova.build/Debug-iphoneos/Intercom\ Cordova.build/Intercom\ Cordova-all-target-headers.hmap -iquote /Users/rodneicouto/Library/Developer/Xcode/DerivedData/Intercom_Cordova-goaiddauftavsxfdmnxpvtybfzmm/Build/Intermediates.noindex/ArchiveIntermediates/Intercom\ Cordova/IntermediateBuildFilesPath/Intercom\ Cordova.build/Debug-iphoneos/Intercom\ Cordova.build/Intercom\ Cordova-project-headers.hmap -I/Users/rodneicouto/lixo3/Example/platforms/ios/build/device/include -I/Users/rodneicouto/Library/Developer/Xcode/DerivedData/Intercom_Cordova-goaiddauftavsxfdmnxpvtybfzmm/Build/Intermediates.noindex/ArchiveIntermediates/Intercom\ Cordova/InstallationBuildProductsLocation/Applications/usr/local/lib/include -I/Users/rodneicouto/Library/Developer/Xcode/DerivedData/Intercom_Cordova-goaiddauftavsxfdmnxpvtybfzmm/Build/Intermediates.noindex/ArchiveIntermediates/Intercom\ Cordova/IntermediateBuildFilesPath/UninstalledProducts/include -I/Users/rodneicouto/Library/Developer/Xcode/DerivedData/Intercom_Cordova-goaiddauftavsxfdmnxpvtybfzmm/Build/Intermediates.noindex/ArchiveIntermediates/Intercom\ Cordova/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/include -I/Users/rodneicouto/lixo3/Example/platforms/ios/build/device -I/Users/rodneicouto/Library/Developer/Xcode/DerivedData/Intercom_Cordova-goaiddauftavsxfdmnxpvtybfzmm/Build/Intermediates.noindex/ArchiveIntermediates/Intercom\ Cordova/IntermediateBuildFilesPath/Intercom\ Cordova.build/Debug-iphoneos/Intercom\ Cordova.build/DerivedSources/armv7 -I/Users/rodneicouto/Library/Developer/Xcode/DerivedData/Intercom_Cordova-goaiddauftavsxfdmnxpvtybfzmm/Build/Intermediates.noindex/ArchiveIntermediates/Intercom\ Cordova/IntermediateBuildFilesPath/Intercom\ Cordova.build/Debug-iphoneos/Intercom\ Cordova.build/DerivedSources -F/Users/rodneicouto/lixo3/Example/platforms/ios/build/device -include /Users/rodneicouto/lixo3/Example/platforms/ios/build/sharedpch/Intercom\ Cordova-Prefix-gazcmkyjwmjuekbubfcxodayvyrq/Intercom\ Cordova-Prefix.pch -MMD -MT dependencies -MF /Users/rodneicouto/Library/Developer/Xcode/DerivedData/Intercom_Cordova-goaiddauftavsxfdmnxpvtybfzmm/Build/Intermediates.noindex/ArchiveIntermediates/Intercom\ Cordova/IntermediateBuildFilesPath/Intercom\ Cordova.build/Debug-iphoneos/Intercom\ Cordova.build/Objects-normal/armv7/IntercomBridge.d --serialize-diagnostics /Users/rodneicouto/Library/Developer/Xcode/DerivedData/Intercom_Cordova-goaiddauftavsxfdmnxpvtybfzmm/Build/Intermediates.noindex/ArchiveIntermediates/Intercom\ Cordova/IntermediateBuildFilesPath/Intercom\ Cordova.build/Debug-iphoneos/Intercom\ Cordova.build/Objects-normal/armv7/IntercomBridge.dia -c /Users/rodneicouto/lixo3/Example/platforms/ios/Intercom\ Cordova/Plugins/cordova-plugin-intercom/IntercomBridge.m -o /Users/rodneicouto/Library/Developer/Xcode/DerivedData/Intercom_Cordova-goaiddauftavsxfdmnxpvtybfzmm/Build/Intermediates.noindex/ArchiveIntermediates/Intercom\ Cordova/IntermediateBuildFilesPath/Intercom\ Cordova.build/Debug-iphoneos/Intercom\ Cordova.build/Objects-normal/armv7/IntercomBridge.o
/Users/rodneicouto/lixo3/Example/platforms/ios/Intercom Cordova/Plugins/cordova-plugin-intercom/IntercomBridge.m:3:9: fatal error: 'Intercom/Intercom.h' file not found
#import <Intercom/Intercom.h>
        ^~~~~~~~~~~~~~~~

If i try run in Xcode the error is the same: 

![screen shot 2018-02-24 at 12 56 13](https://user-images.githubusercontent.com/1113080/36632185-29a4f892-1962-11e8-8a95-a9d2fea6d291.png)

**Comment by ronocod** [comment]
We are moving all our issues support to our [Intercom Developer Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). If you bump into further problems or need updates on this issue, just start a conversation using Intercom there and it will be immediately routed to our Customer Support Engineers.

We're currently working on reproducing this, so for future updates you should contact us through Intercom on that site.
