### ISSUE TITLE
This version (2.3.11) of Intercom for iOS supports iOS 7.0 upwards

### ISSUE THREAD

**Issue by pixnlove** [intercom/intercom-cordova#26]
When I'm emulating my application on iOS with Ionic (`ionic run ios`), I have this error:
```
This version (2.3.11) of Intercom for iOS supports iOS 7.0 upwards.
```
How to configure it with Ionic / Cordova ?

Thanks for your help!

**Comment by jtreanor** [comment]
Hi @pixnlove 

To set your app version to a minimum of iOS 7, add this within `<platform name="ios"> ` in your `config.xml`:

```
<preference name="deployment-target" value="7.0" />
```

**Comment by pixnlove** [comment]
It works. Thanks :+1:
