### ISSUE TITLE
Message Preview icon position different on Android & iOS

### ISSUE THREAD

**Issue by lowjam** [intercom/intercom-cordova#27]
I have my own activator positioned on my app as a styled div. I want it to be in the exact same position as the message preview button so that they overlap when the user has a new message. I did that on iOS and am seeing the message preview appear in a different location on Android:

![intercom alignment](https://cloud.githubusercontent.com/assets/6331721/10771697/2fa51326-7cc0-11e5-83c4-3dd0eb977a7d.png)

Is there any way for me to get the effect I want? For example, can I control the position of the new message preview button more precisely than with the `intercom.setPreviewPosition(intercom.BOTTOM_RIGHT);` call?

I could detect Android in the app and move the activator button to the location that it appears in Android, but I really don't want it overlapping my menu bar on the bottom of the app.

**Comment by jtreanor** [comment]
Hi @lowjam,

Sorry for not responding to this sooner. Unfortunately, it is not possible to line these up exactly at this time.
