### ISSUE TITLE
keys and names 

### ISSUE THREAD

**Issue by Niler851** [intercom/intercom-cordova#28]
Could you add an example of how this may look ? should i change all 6 fields.
whats the difference between intercom-app-id, and your_app_id ?
to me it seems like i should not change the name, but then when i look att the next row it seems like i should. where do i fint this values ?

```
<preference name="intercom-app-id" value="your_app_id"/>
<preference name="intercom-ios-api-key" value="ios_sdk-..."/>
<preference name="intercom-android-api-key" value="android_sdk-..."/>
```

this is what i wrote
```
<preference name="intercom-app-id" value="foo-bar"/>
<preference name="intercom-android-api-key" value="android_sdk-22"/>
```

if this is right then nothing is happening. 
I had it working with the regular web api before, but i couldent send messages.

**Comment by jtreanor** [comment]
Hi @Niler851 

Sorry for not responding to this sooner. What you have done looks correct. Let me know if you are still experiencing any issues.
