### ISSUE TITLE
Client error 422 in v1.1.2

### ISSUE THREAD

**Issue by kristfal** [intercom/intercom-cordova#30]
Hey,

thanks for this great plugin. Got the plugin running on iOS and Android with chat interface and popups. However, I'm unable to log events with v1.1.2 (v1.1.3 is crashing on Android on startup, trying to debug) on both iOS and Android.

Using the example event on iOS:

```
intercom.logEvent("ordered_item", {
    order_date: 1392036272,
    stripe_invoice: "inv_3434343434",
    order_number: 123,
    value: "3434-3434",
    url: "https://example.org/orders/3434-3434"
});
```

or removing custom attributes:

```
intercom.logEvent("ordered_item");
```

Results in the native console log is throwing:

`[Intercom] ERROR - Tried to log an event but there was a network error - Request failed: client error (422)`

It should be noted that I have not enabled push notifications, however the chat (both ways) works just fine. Any idea how to further debug?

**Comment by jtreanor** [comment]
Hi @kristfal,

Thanks for reporting this. I'm investigating now. I haven't seen any issues here but I'll keep digging.

Can you give me more info about the crash on Android you are seeing on 1.1.3?

**Comment by kristfal** [comment]
@jtreanor Managed to narrow down the 1.1.3 crash to a conflicting plugin issue. Resolved it. 

Still seeing the same 422 error on 1.1.3

**Comment by jtreanor** [comment]
Thanks @kristfal, I'll keep you updated as I know more.

**Comment by kristfal** [comment]
Found the issue with LOGCAT on Android:

```
E/Intercom-Android(32509): ERROR: Api call failed:  Status: 422 Body: {"type":"error.list","request_id":"eecea62c-7fe0-4f5b-9f7e-010bdf9d20a4","errors":[{"code":"422","message":"Cannot have more than 120 active event names"}]}
```

Feel free to close this. If anything, could be useful to see this extended error message on iOS as well.

**Comment by jtreanor** [comment]
Thanks for tracking that down @kristfal. Let me know if you have any questions about why you received this error.

**Comment by alexvbush** [comment]
@jtreanor is there a way to lift that limitation or remove unused events?

**Comment by jtreanor** [comment]
@alexvbush This is not an issue with the Cordova plugin. I suggest emailing team@intercom.io to speak to one of my colleagues who know more about this.
