### ISSUE TITLE
Error loading conversation

### ISSUE THREAD

**Issue by hsmith825** [intercom/intercom-cordova#33]
I am having a getting started issue.  I am using the plain on iOS.  I installed it as instructed.  I added to the config: <preference name="intercom-app-id" value="*******"/>. I included intercom.registerIdentifiedUser({userId: currentuserid}); after the user is login.  I hooked the following to a button used to activate chat;
intercom.displayMessageComposer();
    intercom.displayConversationsList();
    intercom.setPreviewPosition(intercom.BOTTOM_RIGHT);

I get an "Error loading conversations"

What am I during wrong?

Thanks!
Howard

**Comment by hsmith825** [comment]
The actual error message is: "ERROR - Tried to get conversations, but there was a problem with the SDK's initialization."

**Comment by jtreanor** [comment]
Hi @hsmith825 

This usually means either that you have not registered a user or you api key or app id are incorrect.

**Comment by hsmith825** [comment]
Where do I find the api key and app id?  The only thing I have done is provide my email address to get started,  I don't know where to go on the Intercom site to find the key and id.

Thanks!

**Comment by hsmith825** [comment]
I don’t know where on your site to go to get the APIkey and ID.  I registered for a free trial with my email address.

Thanks!
Howard

**Comment by jtreanor** [comment]
After entering your email address you will need to go through the iOS or Android setup flow to get an app id and api key.
It's a little unintuitive to do it this way so let me know if I can help.

**Comment by hsmith825** [comment]
I found it.  I am up.  I did not have the key.  Thanks for your help!

**Comment by hsmith825** [comment]
And quick response!!!

**Comment by jtreanor** [comment]
No problem 😄
