### ISSUE TITLE
Indicates No conversations

### ISSUE THREAD

**Issue by hsmith825** [intercom/intercom-cordova#34]
When I use the plugin as indicated and I use a button to invoke the UI using the methods intercom.displayMessageComposer(),  intercom.displayConversationsList(), and intercom.setPreviewPosition(intercom.TOP_RIGHT), I get a white screen with the message " no conversations.  Available.  If I embed the javascript from the Intercom site it works. The problem with this is all users are anonymous and I can position their button nr link to mine.

Any ideas are appreciated!

Thanks!
Howard

**Comment by andyhite** [comment]
Were you able to get this resolved? I'm having the same problem.

**Comment by hsmith825** [comment]
Unfortunately,  I cannot remember how I solved the problem.  I know I did because I am successfully using Intercom now.

**Comment by andyhite** [comment]
I figured my problem out, actually – if anyone else comes across this, make sure you're using the Android or iOS API key. It's different than the regular API keys for Intercom, and can be found under the Intercom for Android/iOS section of the settings.
