### ISSUE TITLE
Permission conflicts for com.google.android.gms.measurement.google_measurement_service

### ISSUE THREAD

**Issue by alexanderwallin** [intercom/intercom-cordova#36]
With the last update, including Intercom, we get reports of Android users getting the -505 error (INSTALL_FAILED_CONFLICTING_PROVIDER).

I made a test case where I created an blank ionic starter app with only `cordova-plugin-device` and `cordova-plugin-intercom` added. After I installed it on the device, I could not install our app.

Our real app is built with cordova-android 4.1.1. The error occurs for test apps build with 4.1.1 as well as 5.0.0.

This is the logcat output:

```
PackageManager  W  Can't install because provider name com.google.android.gms.measurement.google_measurement_service (in package com.example.liveapp) is already used by com.example.testapp
```

Have you got any thoughts right away on this?

**Comment by alexanderwallin** [comment]
This seems to be an issue with cordova-android, looking at the bug report at https://issues.apache.org/jira/browse/CB-10014.

They committed a fix (https://github.com/apache/cordova-android/commit/fb9cf60c4100d5bc6f9320747611da1ca0ced289) a month ago, and when running the test app on cordova-android 5.1.0-dev (the master branch) the conflicts disappeared.

The AndroidManifest.xml file in the build apk contains:

```xml
<provider android:authorities="com.example.testapp.google_measurement_service"
          android:exported="false"
          android:name="com.google.android.gms.measurement.AppMeasurementContentProvider"/>
```

The question is, is there a way for this plugin to go around this issue while waiting for Cordova to release a new version?

**Comment by alexanderwallin** [comment]
Patches that resolves the issue where provided in the Jira ticket, so I implemented them and created a PR here: https://github.com/intercom/intercom-cordova/pull/37

**Comment by jtreanor** [comment]
Thanks for this!
