### ISSUE TITLE
Events "pause", "resume".

### ISSUE THREAD

**Issue by WilliamPanasiuk** [intercom/intercom-cordova#40]
Events listeners "pause" and "resume" doesn't work when plugin is on screen

`$ionicPlatform.ready(function () {`
`document.addEventListener("resume", function() {console.log("resume");}, false);
`
`document.addEventListener("pause", function() {console.log("pasue");}, false); `
`   });    `

Is any other way to do that?

**Comment by DaleCantwell** [comment]
@WilliamPanasiuk sorry for the delay, I have tested this in cordova doing the following:

```    JAVASCRIPT
bindEvents: function() {
        document.addEventListener("resume", this.onDeviceResume, false); 
        document.addEventListener("pause", this.onDevicePause, false);
    },
    onDeviceResume: function() {
        alert("RESUME!");
    },
    onDevicePause: function() {
        alert("PAUSE!");
    },
```

When we open Intercom it hits the pause and when it closed we hit resume. Could you upgrade to 3.0.10 of our cordova plugin and see if this is still happening for you?

**Comment by DaleCantwell** [comment]
@WilliamPanasiuk I'm going to close out this issue for now as I couldn't reproduce it on our newest Cordova release. Let me know if you are still seeing it and I will reopen this.
