### ISSUE TITLE
ReferenceError - intercom is not defined 

### ISSUE THREAD

**Issue by sdbarrington** [intercom/intercom-cordova#41]
Hi, I have the plugin install in my ionic/cordova project.

It works perfectly with iOS, however when I open it in an android emulator I get the following error:
ReferenceError - intercom is not defined 

Have I missed something android specific or something??

**Comment by jtreanor** [comment]
Hi @sdbarrington,

To confirm that Intercom is installed correctly in your Android app, can you confirm the following directory exists: `platforms/android/cordova-plugin-intercom`.

Its possible that for some reason it is installed for iOS but not Android.

**Comment by sdbarrington** [comment]
yes it is there.

S.

**Comment by sdbarrington** [comment]
@jtreanor any other ideas of things I could try?

**Comment by FranceJ** [comment]
This was happening for me due to trying `cordova run android --device` on a device with an old dev version installed. Manually uninstalling and then installing via cordova fixed it.
