### ISSUE TITLE
logEvent doesn't work (anymore)

### ISSUE THREAD

**Issue by rubenstolk** [intercom/intercom-cordova#42]
- [ ] Both for identifiedUsers and `unIdentifiedUsers`, `logEvent` doesn't result in any activity in Intercom
- [ ] `updateUser` doesn't work for `unIdentifiedUsers`

**Comment by jtreanor** [comment]
Hi @rubenstolk 

Thanks for this. Are you seeing these issue on iOS or Android?

**Comment by rubenstolk** [comment]
Both, it used to work fine but it seems since updating to the latest version that it doesn't work anymore. registerIdentifiedUser works fine, updateUser works fine but logEvent doesn't do anything on both iOS and Android.

**Comment by jtreanor** [comment]
I have tested logging an event on the latest version and it worked fine.

Can you tell me more about the event you are trying to log?

**Comment by rubenstolk** [comment]
Hmm... really funny, it's working for me now as well! I'll keep an eye on it and report it again if I have more issues, perhaps it was just the network...

**Comment by jtreanor** [comment]
Glad it's working now.
Let us know if you have any more issues
