### ISSUE TITLE
okhttp update

### ISSUE THREAD

**Issue by greggreenhaw** [intercom/intercom-cordova#45]
We received this from google and could only find it used in your plugin.

We've been rigorously testing popular applications on Google Play for a future Android release. We noticed that your app is crashing due to an older version of okHTTP library. We recommend you update your application's okHTTP library to V3.2.0.

**Comment by harkin** [comment]
This might be a silly question but is your app actually crashing?

**Comment by greggreenhaw** [comment]
I was told some  Galaxy devices are

**Comment by harkin** [comment]
We're currently using 2.7.4 of okhttp in the Android library, we're bumping that to 2.7.5 in the next release. This is the latest release in the 2.x branch. 

We will be moving to the 3.x version of the library at some point in the future but we don't have a timeline for it. 

@greggreenhaw Do you have any crash logs for those devices?

**Comment by greggreenhaw** [comment]
I'll have to get back to you with those

**Comment by harkin** [comment]
@greggreenhaw okay once you send those on we can look into it and see if it's something we're responsible for or something in okhttp itself

**Comment by jtreanor** [comment]
Closing this due to lack of info. If you see this issue again, please let us know.
