### ISSUE TITLE
Compatibility with Window OS

### ISSUE THREAD

**Issue by alzap** [intercom/intercom-cordova#5]
Getting the following error when installing the plugin on Windows 8.1 or Windows 7

Fetching plugin "io.intercom.cordova" via plugin registry
Error: ENOENT, open '...\AppData\Local\Temp\npm-8688-jOBoj60l\1434076174563-0.7459123267326504\package\src\io
s\Intercom.framework\Versions\A\Resources\Intercom.bundle\certs\*.intercom.io.icmcer'

There is a file for ios platform that start with *.

**Comment by Anu2g** [comment]
+1. We have this issue on our team because some of our devs are on windows and some on Macs. We only do the iOS builds on the macs, but merely doing a cordova plugin add yields this error, which means it's a bit of a hassle to use the same repo (and main branch) across different platforms. Any help would be greatly appreciated.

**Comment by steaks** [comment]
+1

**Comment by abhisekshukla** [comment]
+1

**Comment by jtreanor** [comment]
Thanks for reporting this. I can certainly fix this in our next iOS release.

@alzap could you try removing the file with `*` in the name to see if you can get it running?
It is not advisable to ship without this file as it could affect SSL pinning but it would be useful to know if this is the only issue.

**Comment by Anu2g** [comment]
@jtreanor Thanks for the quick follow-up! Tried removing the *, and it does build fine (for android). That's our work-around, for being able to use the intercom plugin while developing on a windows machine.

**Comment by jtreanor** [comment]
Thanks @Anu2g,

I will rename this file for our next release.

**Comment by jtreanor** [comment]
This is fixed in 2.3.0 of Intercom for iOS which is included in the latest release (1.0.2)
