### ISSUE TITLE
Intercom Messenger Always Showing

### ISSUE THREAD

**Issue by jonhainstock** [intercom/intercom-cordova#50]
## Version info
  - Intercom for Cordova/PhoneGap version: 6.1.1
  - iOS/Android OS version: 9.3.1
  - iOS/Android Device: iPhone 6

## Expected behavior
Intercom messenger to only show if there is a new conversation available. 

## Actual behavior
Intercom messenger is showing all the time now. It never did this before, but something changed when I reinstalled the plugin.

## Steps to reproduce
 1. Install Ionic
 2. Install intercom-cordova
 3. Identify user

![img_1862](https://cloud.githubusercontent.com/assets/1247220/14930263/3cd6d6a2-0e28-11e6-899a-bd234f273deb.PNG)

**Comment by jtreanor** [comment]
Hi @jonhainstock,

How did you install Intercom in your app? The latest version of Intercom for Cordova is 1.1.5.

**Comment by jtreanor** [comment]
@jonhainstock Just a quick follow up here.

This is not an issue with intercom-cordova, as it looks like the [JavaScript messenger](https://docs.intercom.io/install-on-your-product-or-site/quick-install/install-intercom-on-your-web-app) has been installed by mistake.

I am happy to help you resolve the issue for your app. Alternatively you can email team@intercom.io for more support 😄

**Comment by jonhainstock** [comment]
Thanks @jtreanor. Totally makes sense. We recently added Segment to our app which must have switched that on. Thanks for your help!

**Comment by jtreanor** [comment]
No problem, glad I could help 😄
