### ISSUE TITLE
Android Build Failure Due to Framework Conflict

### ISSUE THREAD

**Issue by bryanterrell** [intercom/intercom-cordova#54]
## Version info
  - Intercom for Cordova/PhoneGap version: 1.1.6
  - OS / Device: N/A
  - Android SDK Tools: 25.1.6
  - Android SDK Platform-tools: 23.1
  - Android SDK Build-tools: 23.0.3
  - Android SDK Platform: 23

## Expected behavior
Build succeeds after adding latest version of Intercom Cordova plugin to a Meteor project when another plugin using Google Play Services is in project.

## Actual behavior
Meteor build fails with exception.

## Steps to reproduce
 1. Create new Meteor project
   - `meteor create intercom-test`
 2. Add Intercom plugin (using 1.1.6 wasn't working so used commit hash)
   - `meteor add cordova:cordova-plugin-intercom@https://github.com/intercom/intercom-cordova.git#ece64b0e3836c507abbf0a7f01c3c9e9e1cdab65`
 3. Add another plugin that uses Google Play services - this is just a fork of the Cordova Google Maps plugin
   - `meteor add cordova:cordova-plugin-googlemaps@https://github.com/37d/cordova-plugin-googlemaps.git#3ad7826e4d74b6659201a42e4922492a5ddcf1fb`
 4 . Build the project 
   - `meteor build ./output --server=http://192.168.1.1:3000 --verbose`

## Steps to fix
 1. Remove current plugin
  - `meteor remove cordova:cordova-plugin-intercom`
 2. Add forked plugin that removes the version # from the framework reference
  - `meteor add cordova-plugin-intercom@https://github.com/37d/intercom-cordova.git#cccf24a00c80724ae9473f35bf4feff2a1ca4ace`

I'm thinking this may have something to do with the 9.0 release of the Google Play services so any project that asks for the latest results in having multiple versions of those services since this plugin requests version 8, but that's just a guess.

I can do a Pull Request of the fork if desired.

## Logs
>UNEXPECTED TOP-LEVEL EXCEPTION:
> com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/iid/MessengerCompat$1;

>What went wrong:
>Execution failed for task ':transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

**Comment by crazybaud** [comment]
This imply an incompatibility with `cordova-background-geolocation-lt` plugin which uses Google Play services: https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/136

If I use @bryanterrell fork, everything is working fine

**Comment by jtreanor** [comment]
Can you try this again with the latest version of the plugin ([3.0.0](https://github.com/intercom/intercom-cordova/releases/tag/3.0.0))

**Comment by crazybaud** [comment]
Push notifications on Android do not work anymore, but we had to integrate https://github.com/raix/push in parallel to add our notification system. I think we are facing this issue https://github.com/intercom/intercom-android/issues/246 

Can you update intercom-cordova to the last https://github.com/intercom/intercom-android version ? it should resolve it.

**Comment by crazybaud** [comment]
Important to notice, during our upgrade we encountered this issue `com.android.dex.DexIndexOverflowException` and we found a workaround here https://github.com/meteor/meteor/issues/7693#issuecomment-243196155

**Comment by DaleCantwell** [comment]
@crazybaud in [3.0.10](https://github.com/intercom/intercom-cordova/releases/tag/3.0.10) we have updated to the new Android SDK which has a new public class called the IntercomPushClient which enables third party push integrations to work.
We have a fork of the phonegap push plugin here: https://github.com/intercom/phonegap-plugin-push which is necessary to use to support non Intercom push. 
It may also be useful to check our push section in our cordova docs https://github.com/intercom/intercom-cordova#push-notifications
Let us know if you run into any issues supporting your own push and intercom at the same time.
