### ISSUE TITLE
Android crashing

### ISSUE THREAD

**Issue by nloui** [intercom/intercom-cordova#55]
Hi there,

My app is crashing for Android on startup because of the Intercom SDK (working in iOS)

## Version info
  - Intercom for Cordova/PhoneGap version: 1.1.6
  - iOS/Android OS version: 6.0
  - iOS/Android Device: Nexus 5

Also replicated on Samsung S6 Edge+

## Expected behavior

App opens and runs

## Actual behavior

App crashes on launch

## Steps to reproduce
 1.  Open app
 2.  App crashes
 
I did confirm that config.xml has the API key and App ID correctly set.

## Logs
E/Intercom-Android( 2754): Please check that you are using an Intercom Android SDK key and have not passed the appId into the apiKey field
D/AndroidRuntime( 2754): Shutting down VM
E/AndroidRuntime( 2754): FATAL EXCEPTION: main
E/AndroidRuntime( 2754): Process: com.nloui.XXX, PID: 2754
E/AndroidRuntime( 2754): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nloui.XXX/com.nloui.XXX.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'io.intercom.android.sdk.api.Api io.intercom.android.sdk.Bridge.api()' on a null object reference

**Comment by jtreanor** [comment]
Thanks for reporting this @nloui.

I have fixed the issue in #56 and released 1.1.7 of the plugin.
