### ISSUE TITLE
Conflict building with Firebase

### ISSUE THREAD

**Issue by grassick** [intercom/intercom-cordova#58]
## Version info
  - Intercom for Cordova/PhoneGap version: 1.1.7
  - iOS/Android OS version: 5.0.1
  - iOS/Android Device: Samsung S4

## Expected behavior

Expected to be able to compile with Firebase plugin (https://github.com/fechanique/cordova-plugin-fcm.git)

## Actual behavior

Get error of `Found com.google.android.gms:play-services-gcm:8.+, but version 9.0.0 is needed for the google-services plugin` caused by Firebase requiring: `classpath 'com.google.gms:google-services:3.0.0'`

## Steps to reproduce
 1. Add both intercom and firebase plugin
 2. Attempt to build android
 3. Failure!

## Logs
```
:processDebugGoogleServices
Found com.google.android.gms:play-services-gcm:8.+, but version 9.0.0 is needed for the google-services plugin.
:processDebugGoogleServices FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.0.0.
```

## TO FIX:

Replace       `<framework src="com.google.android.gms:play-services-gcm:8.+" /> `
with      ` <framework src="com.google.android.gms:play-services-gcm:9.0.0+" /> ` in plugin.xml

**Comment by jtreanor** [comment]
@grassick Can you try this again with the latest version of the plugin ([3.0.0](https://github.com/intercom/intercom-cordova/releases/tag/3.0.0))

**Comment by jtreanor** [comment]
Quick update here. We are now using 9.4 of Google Play Services so this will work fine now 😄
