### ISSUE TITLE
Customize Push Notification display icon on Android

### ISSUE THREAD

**Issue by Arania** [intercom/intercom-cordova#59]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io
## Version info
- Intercom for Cordova version: 1.1.7
- Android OS version: 6.0.1
- Android Device: Nexus 6X
## Expected behavior

The Cordova/PhoneGap SDK should have a method/configuration setting to choose a custom display icon for push notifications on Android sent through Intercom. It can be name of a drawable resource. In case Intercom's fork of PhoneGap Push plugin is used, it can simply use the one defined for android.icon while initializing the plugin (ref: https://github.com/intercom/phonegap-plugin-push/blob/master/docs/API.md#android)
## Actual behavior

Shows the default message bubble icon for Push Notifications sent through Intercom. Regular push notifications (sent by our API) show the app icon as configured while initializing PhoneGap Push Plugin.
## Steps to reproduce
1.  Create a new Cordova app and integrate it with Intercom
2. Send a notification through Intercom to an Android device
3. Notification shows Intercom's default icon with no option to set a custom icon in Intercom Cordova SDK.

**Comment by Qulinary** [comment]
+1

**Comment by ithav** [comment]
+1

**Comment by azrul** [comment]
+1

**Comment by pushpak** [comment]
+1

**Comment by paatrick** [comment]
+1

**Comment by DaleCantwell** [comment]
I have attached below how this works in the native SDK. This actually works here too. If you manually go to platforms/android/res and and to each dpi an intercom_push_icon.png 
This is not ideal for Cordova, having to edit the generated platform folder. We will continue to look into a better Cordova solution. 

**Android custom push icon**

https://docs.intercom.com/configure-intercom-for-your-product-or-site/configure-intercom-for-mobile/enable-push-notifications-with-intercom-for-android-gcm

Step 4. Setting your GCM icon

If you want to add a custom icon for your notifications, just add an image named intercom_push_icon.png  to each of your supported densities. For example:

/res/drawable-xxhdpi/intercom_push_icon.png 
/res/drawable-xhdpi/intercom_push_icon.png 
/res/drawable-hdpi/intercom_push_icon.png 
/res/drawable-mdpi/intercom_push_icon.png 
Note: We recommend following the material design guidelines for producing this icon.

**Comment by bboyle18** [comment]
Closing and tracking it internally https://github.com/intercom/intercom/issues/55312
