### ISSUE TITLE
Maven Google Play GCM not accessible anymore

### ISSUE THREAD

**Issue by dandyn** [intercom/intercom-cordova#6]
Hi,

The build for Android fails in the gradle file trying to fetch `com.google.android.gms:play-services-gcm:7.5.0`

Here's what it says:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find com.google.android.gms:play-services-gcm:7.5.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/7.5.0/play-services-gcm-7.5.0.pom
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/7.5.0/play-services-gcm-7.5.0.jar
```

**Comment by jtreanor** [comment]
Hi @dandyn,

This usually means that you need to install the "Google Repository" from your Android SDK Manager ([this](http://developer.android.com/sdk/installing/adding-packages.html) might help).

James

**Comment by dandyn** [comment]
That did the trick, thanks!

**Comment by slorber** [comment]
@jtreanor by chance is there anything you can do on your side to automate this process?

**Comment by slorber** [comment]
I think there are multiple things that should be installed. It only worked after I installed all these:

- Extra > Google Play Service 
- Extra > Google Repository 
- Extra > Android Support Library 
- Extra > Android Support Repository

**Comment by jtreanor** [comment]
@slorber Unfortunately not. Google do not seem to want to make Google Play services accessible on a public maven repo so this is the only way.

**Comment by slorber** [comment]
@jtreanor in the past google did not publish its GCM library but it was release under apache license so it is possible to host the lib for them.

I did so iin 2012 in this repository: https://github.com/slorber/gcm-server-repository

Maybe the same can be done for these jars too?
