### ISSUE TITLE
How can we use the new localisation feature?

### ISSUE THREAD

**Issue by Telemakhos** [intercom/intercom-cordova#60]
Intercom has been updated and now supports localisation also for the in-app messenger. This was a much needed feature and I want to thank the Intercom devs for the great work.

https://docs.intercom.io/configure-intercom-for-your-product-or-site/customize-the-intercom-messenger/localize-intercom-to-work-with-multiple-languages

How can we select the locale via ```language_override``` in this plugin? if not possible yet, is there an ETA?

**Comment by jtreanor** [comment]
Hi @Telemakhos,

We are currently in the process of updating the Cordova plugin for the new version of the Messenger. Once this is completed, you will be able to use localisation exactly as outlined in that doc. The locale will be automatically chosen based on the languages in your Intercom settings and the device's locale.

**Comment by Telemakhos** [comment]
James, thanks so much for the quick reply. We'll wait for the update then... 

Cheers!

**Comment by jtreanor** [comment]
[3.0.0](https://github.com/intercom/intercom-cordova/releases/tag/3.0.0) is now released with full support for the new localisation features.

**Comment by ferdelcorro** [comment]
Hi, i need set the user language without localization, how i can do this? In my code i have

    intercomService.registerUser = function() {
        if (checkIntercomExist()) {
            if (checkAuthentication()) {
                intercom.registerIdentifiedUser({
                    userId: intercomService.profileId
                });
                intercomService.updateUser();
            } else {
                intercom.registerUnidentifiedUser();
            }
        }
    }

    intercomService.updateUser = function() {
        if (checkIntercomExist()) {
            if (checkAuthentication()) {
                intercom.updateUser({
                    userId: intercomService.profileId,
                    name: intercomService.profileUsername,
                    language_override: "pt"
                });
            }
        }
    }

    intercomService.helpCenter = function() {
        if (checkIntercomExist()) {
            intercomService.registerUser();
            intercom.displayMessenger();
        } else {
            console.log("No existe intercom");
        }
    }

but when i open the messenger, then it display me a message in English and Spanish (i'm be in Argentina).
The messenger say me "No hay conversaciones" and next line say "No conversations with XXXXX yet".

**Comment by ronocod** [comment]
@ferdelcorro this should be fixed in the latest version, can you try that?

**Comment by ferdelcorro** [comment]
I updated the plugin from 3.0.17 to 3.0.19 and when i open the messenger for first time, the text be in English and when i re open it the text be in Spanish.
Anyway, my problem is because i need set the language without localization, i need use of "language_override" because if an user go to other country then he's going to open the messenger and the language is going to be different. I take the language from backend user settings.

**Comment by ronocod** [comment]
@ferdelcorro can you contact us through Intercom about this? It's easier to talk there than GitHub 😄
