### ISSUE TITLE
Null Pointer Exception when resuming from an Android deep sleep

### ISSUE THREAD

**Issue by dested** [intercom/intercom-cordova#61]
## Version info
  - Intercom for Cordova/PhoneGap version:  1.1.7
  - iOS/Android OS version: Android  6.0
  - iOS/Android Device:  Nexus  5x

## Expected behavior

The app would not crash after resuming the application after it has been backgrounded 

## Actual behavior

System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'io.intercom.android.sdk.api.Api io.intercom.android.sdk.Bridge.api()' on a null object reference
System.err:    at io.intercom.android.sdk.Bridge.getApi(Bridge.java:80)

## Steps to reproduce
1. Turn your android to developer mode
2. Go to developer options in settings
3. Change background process limit to "No background processes". This expedites the error.
4. Deploy the app the phone as normal
5. App runs without issue
6. Minimize the app
7. Open another app
8. Open another app
9. Open the running app list (the square button in the bottom right of your phone)
10. Open the app with intercom installed
11. It should crash with the above error

## Logs
I get this error  in @Override protected void pluginInitialize() 

System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'io.intercom.android.sdk.api.Api io.intercom.android.sdk.Bridge.api()' on a null object reference
System.err:    at io.intercom.android.sdk.Bridge.getApi(Bridge.java:80)

This one is a bit tricky to track down. I am not using a regular version of cordova, but rather a native project named Tabris.js (http://tabrisjs.com/). You can see a reference to this issue here https://github.com/eclipsesource/tabris-js/issues/902#issuecomment-234497765.

If you need any more details please let me know.

**Comment by jtreanor** [comment]
[3.0.0](https://github.com/intercom/intercom-cordova/releases/tag/3.0.0) is now released which includes the newest version of Intercom for Android. This should resolve your issue.
