### ISSUE TITLE
Trying to build ionic/cordova project (fatal error: 'Intercom/Intercom.h' file not found)

### ISSUE THREAD

**Issue by Alion** [intercom/intercom-cordova#64]
## Version info
  - Intercom for Cordova/PhoneGap version:3.0.2
  - iOS/Android OS version:9.3
  - iOS/Android Device:iphone 6 +

## Expected behavior
Building an ionic app with intercom included

## Actual behavior
[ios project path]/Plugins/cordova-plugin-intercom/AppDelegate+IntercomPush.m:2:9: 'Intercom/Intercom.h' file not found

## Steps to reproduce
 1. ionic plugins add cordova-plugin-intercom
 2. ionic prepare ios
 3. ionic build ios

## Logs
Running command: "/Users/x. xx xxxxx/Git/xxxxxxxxx-app/App/hooks/after_prepare/010_add_platform_class.js" "/Users/x. xx xxxxx/Git/xxxxxxxxx-app/App"x. xx xxxxx

add to body class: platform-ios

Alions-MacBook-Pro:App x. xx xxxxx$ ionic build ios

Running command: "/Users/x. xx xxxxx/Git/xxxxxxxxx-app/App/hooks/after_prepare/010_add_platform_class.js" "/Users/x. xx xxxxx/Git/xxxxxxxxx-app/App"x. xx xxxxx

add to body class: platform-ios

Building project: /Users/x. xx xxxxx/Git/xxxxxxxxx-app/App/platforms/ios/init.xcodeprojxxxxxxxxx-appxxxxxxxxx-app

Configuration: Debug

Platform: emulator

Build settings from command line:

    CONFIGURATION_BUILD_DIR = /Users/x. xx xxxxx/Git/xxxxxxxxx-app/App/platforms/ios/build/emulatorxxxxxxxxx-appxxxxxxxxx-app

    SDKROOT = iphonesimulator9.3

    SHARED_PRECOMPS_DIR = /Users/x. xx xxxxx/Git/xxxxxxxxx-app/App/platforms/ios/build/sharedpchxxxxxxxxx-appxxxxxxxxx-app

Build settings from configuration file '/Users/x. xx xxxxx/Git/xxxxxxxxx-app/App/platforms/ios/cordova/build-debug.xcconfig':xxxxxxxxx-appxxxxxxxxx-app

    CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES

    CODE_SIGN_IDENTITY = iPhone Developer

    ENABLE_BITCODE = NO

    GCC_PREPROCESSOR_DEFINITIONS = DEBUG=1

    HEADER_SEARCH_PATHS = "$(TARGET_BUILD_DIR)/usr/local/lib/include" "$(OBJROOT)/UninstalledProducts/include" "$(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include" "$(BUILT_PRODUCTS_DIR)"

    IPHONEOS_DEPLOYMENT_TARGET = 8.0

    OTHER_LDFLAGS = -ObjC

    SWIFT_OBJC_BRIDGING_HEADER = $(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h

    TARGETED_DEVICE_FAMILY = 1,2

=== BUILD TARGET CordovaLib OF PROJECT CordovaLib WITH CONFIGURATION Debug ===

Check dependencies

=== BUILD TARGET init OF PROJECT init WITH CONFIGURATION Debug ===

Check dependencies

PhaseScriptExecution Copy\ www\ directory build/init.build/Debug-iphonesimulator/init.build/Script-304B58A110DAC018002A0835.sh

    cd "/Users/x. xx xxxxx/Git/xxxxxxxxx-app/App/platforms/ios"xxxxxxxxx-appxxxxxxxxx-app

    /bin/sh -c \"/Users/xxxxxxxx/Git/xxxxxxxxx-app/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/Script-304B58A110DAC018002A0835.sh\"xxxxxxxxx-appxxxxxxxxx-app

ProcessInfoPlistFile build/emulator/init.app/Info.plist init/init-Info.plist

    cd "/Users/x. xx xxxxx/Git/xxxxxxxxx-app/App/platforms/ios"xxxxxxxxx-appxxxxxxxxx-app

    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/x. xx xxxxx/.gem/ruby/2.0.0/bin"

    builtin-infoPlistUtility /Users/xxxxxxxx/Git/xxxxxxxxx-app/App/platforms/ios/init/init-Info.plist -genpkginfo /Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/emulator/init.app/PkgInfo -expandbuildsettings -format binary -platform iphonesimulator -additionalcontentfile /Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/MainViewController-PartialInfo.plist -additionalcontentfile /Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/assetcatalog_generated_info.plist -o /Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/emulator/init.app/Info.plistxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-app

CompileC build/init.build/Debug-iphonesimulator/init.build/Objects-normal/i386/CDVDevice.o init/Plugins/cordova-plugin-device/CDVDevice.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler

    cd "/Users/x. xx xxxxx/Git/xxxxxxxxx-app/App/platforms/ios"xxxxxxxxx-appxxxxxxxxx-app

    export LANG=en_US.US-ASCII

    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/x. xx xxxxx/.gem/ruby/2.0.0/bin"

    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch i386 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/3m/1phdkyb10f5c_0jm2vkv3wr4fh6t1p/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/xxxxxxxx/Git/xxxxxxxxx-app/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/init-generated-files.hmap -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/init-own-target-headers.hmap -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/init-all-target-headers.hmap -iquote /Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/init-project-headers.hmap -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/emulator/include -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/emulator/usr/local/lib/include -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/UninstalledProducts/include -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/UninstalledProducts/iphonesimulator/include -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/emulator -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/DerivedSources/i386 -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/DerivedSources -F/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/emulator -Finit/Plugins/cordova-plugin-intercom -include /Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/sharedpch/init-Prefix-airkcxpuarungihjuyadlvjiwlbp/init-Prefix.pch -MMD -MT dependencies -MF /Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/Objects-normal/i386/CDVDevice.d --serialize-diagnostics /Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/Objects-normal/i386/CDVDevice.dia -c /Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/init/Plugins/cordova-plugin-device/CDVDevice.m -o /Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/Objects-normal/i386/CDVDevice.oxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-app

CompileC build/init.build/Debug-iphonesimulator/init.build/Objects-normal/i386/IntercomBridge.o init/Plugins/cordova-plugin-intercom/IntercomBridge.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler

    cd "/Users/x. xx xxxxx/Git/xxxxxxxxx-app/App/platforms/ios"xxxxxxxxx-appxxxxxxxxx-app

    export LANG=en_US.US-ASCII

    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/x. xx xxxxx/.gem/ruby/2.0.0/bin"

    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch i386 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/3m/1phdkyb10f5c_0jm2vkv3wr4fh6t1p/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/xxxxxxxx/Git/xxxxxxxxx-app/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/init-generated-files.hmap -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/init-own-target-headers.hmap -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/init-all-target-headers.hmap -iquote /Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/init-project-headers.hmap -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/emulator/include -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/emulator/usr/local/lib/include -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/UninstalledProducts/include -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/UninstalledProducts/iphonesimulator/include -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/emulator -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/DerivedSources/i386 -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/DerivedSources -F/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/emulator -Finit/Plugins/cordova-plugin-intercom -include /Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/sharedpch/init-Prefix-airkcxpuarungihjuyadlvjiwlbp/init-Prefix.pch -MMD -MT dependencies -MF /Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/Objects-normal/i386/IntercomBridge.d --serialize-diagnostics /Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/Objects-normal/i386/IntercomBridge.dia -c /Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/init/Plugins/cordova-plugin-intercom/IntercomBridge.m -o /Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/Objects-normal/i386/IntercomBridge.oxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-app

/Users/x. xx xxxxx/Git/xxxxxxxxx-app/App/platforms/ios/init/Plugins/cordova-plugin-intercom/IntercomBridge.m:3:9: fatal error: 'Intercom/Intercom.h' file not foundxxxxxxxxx-appxxxxxxxxx-app

#import <Intercom/Intercom.h>

        ^

CompileC build/init.build/Debug-iphonesimulator/init.build/Objects-normal/i386/AppDelegate+IntercomPush.o init/Plugins/cordova-plugin-intercom/AppDelegate+IntercomPush.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler

    cd "/Users/x. xx xxxxx/Git/xxxxxxxxx-app/App/platforms/ios"xxxxxxxxx-appxxxxxxxxx-app

    export LANG=en_US.US-ASCII

    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/x. xx xxxxx/.gem/ruby/2.0.0/bin"

    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch i386 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/3m/1phdkyb10f5c_0jm2vkv3wr4fh6t1p/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/xxxxxxxx/Git/xxxxxxxxx-app/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/init-generated-files.hmap -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/init-own-target-headers.hmap -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/init-all-target-headers.hmap -iquote /Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/init-project-headers.hmap -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/emulator/include -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/emulator/usr/local/lib/include -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/UninstalledProducts/include -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/UninstalledProducts/iphonesimulator/include -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/emulator -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/DerivedSources/i386 -I/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/DerivedSources -F/Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/emulator -Finit/Plugins/cordova-plugin-intercom -include /Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/sharedpch/init-Prefix-airkcxpuarungihjuyadlvjiwlbp/init-Prefix.pch -MMD -MT dependencies -MF /Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/Objects-normal/i386/AppDelegate+IntercomPush.d --serialize-diagnostics /Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/Objects-normal/i386/AppDelegate+IntercomPush.dia -c /Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/init/Plugins/cordova-plugin-intercom/AppDelegate+IntercomPush.m -o /Users/xxxxxxxx/Git/xxxxxxxx/App/platforms/ios/build/init.build/Debug-iphonesimulator/init.build/Objects-normal/i386/AppDelegate+IntercomPush.oxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-app

/Users/x. xx xxxxx/Git/xxxxxxxxx-app/App/platforms/ios/init/Plugins/cordova-plugin-intercom/AppDelegate+IntercomPush.m:2:9: fatal error: 'Intercom/Intercom.h' file not foundxxxxxxxxx-appxxxxxxxxx-app

#import <Intercom/Intercom.h>

        ^

1 error generated.

** BUILD FAILED **

The following build commands failed:

CompileC build/init.build/Debug-iphonesimulator/init.build/Objects-normal/i386/AppDelegate+IntercomPush.o init/Plugins/cordova-plugin-intercom/AppDelegate+IntercomPush.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler

(1 failure)

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/x. xx xxxxx/Git/xxxxxxxxx-app/App/platforms/ios/cordova/build-debug.xcconfig,-project,init.xcodeproj,-target,init,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,build,CONFIGURATION_BUILD_DIR=/Users/x. xx xxxxx/Git/xxxxxxxx/App/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/x. xx xxxxx/Git/xxxxxxxx/App/platforms/ios/build/sharedpchxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appxxxxxxxxx-appx. xx xxxxxx. xx xxxxx

**Comment by jtreanor** [comment]
@Alion Thanks for writing this up.

We have just released [3.0.3](https://github.com/intercom/intercom-cordova/releases/tag/3.0.3) which I believe should resolve this issue.

**Comment by jtreanor** [comment]
One more quick note; Note you will need to use cordova-ios version 4.0.0 or newer.

**Comment by shankarregmi** [comment]
Any solution to this yet? I can not build my ionic project after adding intercom plugin

**Comment by saro0h** [comment]
Hello, same for me, any news on this? The version of ionic I use is 3.7.0.

**Comment by jlf123** [comment]
any updates?
