### ISSUE TITLE
Upgrade intercom-sdk for Android

### ISSUE THREAD

**Issue by dandyn** [intercom/intercom-cordova#7]
Hi,

The SDK for Android has some NullPointerException issues in 1.0.3.
The 1.0.4 version fixes them as stated [here](https://github.com/intercom/intercom-android/issues/88).

Thanks

**Comment by jtreanor** [comment]
Thanks @dandyn.

I'll certainly do this for the next release in the coming days.

**Comment by jtreanor** [comment]
I have just released version 1.0.3 of the plugin. This updates Intercom for Android to 1.1.0 and Intercom for iOS to 2.3.0.
