### ISSUE TITLE
intercom.setInAppMessageVisibility is not working

### ISSUE THREAD

**Issue by hcentelles** [intercom/intercom-cordova#70]
intercom.setInAppMessageVisibility isn't working as stated on the readme file, I think is because of this:

https://github.com/intercom/intercom-cordova/blob/master/www/intercom.js#L50

the method is calling the native ```setLauncherVisibility``` instead of ```setInAppMessageVisibility```

## Version info
  - Intercom for Cordova/PhoneGap version: 3.0.6
  - iOS/Android OS version: iOS 9.3.2
  - iOS/Android Device: iPhone 5S

## Expected behavior
Not show in app messages after calling ```intercom.setInAppMessageVisibility(intercom.GONE)```

## Actual behavior
In app messages are shown

## Steps to reproduce
 1. call ```intercom.setInAppMessageVisibility(intercom.GONE)```
 2. send an in app message

**Comment by DaleCantwell** [comment]
Hi @hcentelles. Thanks for reporting the issue to us. We fixed it in [3.0.7 ](https://github.com/intercom/intercom-cordova/releases/tag/3.0.7)
