### ISSUE TITLE
Missing displayMessenger() for iOS

### ISSUE THREAD

**Issue by victordahlin** [intercom/intercom-cordova#73]
We are using Ionic and when building to iOS the method displayMessenger() seems to be missing from the iOS plugin https://github.com/intercom/intercom-cordova/blob/master/src/ios/IntercomBridge.m

## Version info
  - Intercom for Cordova/PhoneGap version: 3.0.7
  - iOS/Android OS version: iOS 9.1
  - iOS/Android Device: Iphone 4S

## Expected behavior
Should work

## Actual behavior
ERROR: Method 'displayMessenger:' not defined in Plugin 'Intercom'
-[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["INVALID","Intercom","displayMessenger",[]]

## Steps to reproduce
1. Install plugin `cordova plugin add cordova-plugin-intercom`
2. Call `intercom.displayMessenger()`

**Comment by jtreanor** [comment]
Thanks for reporting and fixing this @victordahlin
