### ISSUE TITLE
Document all methods

### ISSUE THREAD

**Issue by lorensr** [intercom/intercom-cordova#76]
From the README:

> intercom.displayMessenger(), intercom.displayMessageComposer();, intercom.displayConversationsList();

Could you go into a little more detail here, as to what pieces of the UI they control and whether they take arguments? 

Also, in iOS there are two ways of hiding:

![image](https://cloud.githubusercontent.com/assets/251288/18025736/d7e9155c-6c00-11e6-9613-622e640691a9.png)

`setInAppMessageVisibility` is the former? Is there an equivalent to the latter?

What about equivalents for iOS's `setLauncherVisible` and `unreadConversationCount`?

**Comment by lorensr** [comment]
![image](https://cloud.githubusercontent.com/assets/251288/18117083/665b1666-6f1a-11e6-9251-6273a0eedada.png)

**Comment by bboyle18** [comment]
Hi @lorensr 

Thanks for getting in touch about this and apologies for the delay in replying. 
All methods you mentioned above are available in the iOS Cordova Plugin.
`setLauncherVisible:` equivalent is `setLauncherVisibility:`

Cheers

Brian
