### ISSUE TITLE
Something went wrong 

### ISSUE THREAD

**Issue by paulocastellano** [intercom/intercom-cordova#79]
Hi,

I setup intercom-cordova on Ionic2 but always return this and i don't have error in console.log

**intercom-app-id and intercom-android-api-key i set OK from intercom data.**

in config.xml:
`<plugin name="cordova-plugin-intercom" spec="~3.0.9"/>
  <preference name="intercom-app-id" value=" **HERE I SET MY APP_ID** "/>
  <preference name="intercom-android-api-key" value=" **WHERE MY ANDROID API KEY FROM INTERCOM"/>`**

My function to open intercom:

intercom.updateUser({
    user_id: "1360",
    name: "Paulo Castellano",
    email: 'paulocastellano@doctorengage.com'
});   

intercom.displayMessenger();

Obs:

cordova version 6.3.1
node version 6.3.1

![doctorengage_android](https://cloud.githubusercontent.com/assets/265964/18290249/2ecdfe54-7459-11e6-8c26-b834912ac702.png)

**Comment by ronocod** [comment]
Are you calling `intercom.registerIdentifiedUser()` or `intercom.registerUnidentifiedUser()` before you display the Messenger?

**Comment by paulocastellano** [comment]
Sorry, it was one conflict from intercom and datepicker.

**Comment by giltotherescue** [comment]
Hi @paulocastellano, I seem to be running into a similar issue, and I am also using DatePicker. How did you resolve it? Thanks...
