### ISSUE TITLE
user_id is undefined when a user is registered for android

### ISSUE THREAD

**Issue by jzgit** [intercom/intercom-cordova#8]
When we register an identified user on android they get an undefined user_id and their actual id gets set to userid.  This does not seem to be an issue in our ios app.

**Comment by jtreanor** [comment]
Hi @jzgit,

On both platforms when you call `registerUnidentifiedUser`, Intercom creates an unidentified user with a randomly generated `user_id`. I don't understand what you mean by their actual id?

James

**Comment by jtreanor** [comment]
Closing this for now as I don't believe there is an issue here. Please feel free to reopen if you are still seeing problems with this.
