### ISSUE TITLE
The plugin conficts with OneSignal cordova plugin

### ISSUE THREAD

**Issue by IcyEagle** [intercom/intercom-cordova#83]
I have numerous amount of messages (5-7) "Your iOS app is now integrated with the Intercom platform" after I launch or resume my application. Then I have a few ones (1-3) when I get or send a message from messenger. Is it possible to disable this alerts at all?    

I use Meteor framework for my application (shouldn't be an issue).
In Javascript I call registerForPush and registerIdentifiedUser once the device is ready.

[Screen](https://drive.google.com/open?id=0B-v7cOJbeXRGekYzNHJXSG5uNkE).

Thanks! 

## Version info
  - Intercom for Cordova/PhoneGap 3.0.10:
  - iOS 9.3.5:
  - Iphone 6s:

**Comment by IcyEagle** [comment]
It seems like it conflicts with onesignal-cordova-plugin.

Is there a way to make them work together?

**Comment by DaleCantwell** [comment]
@IcyEagle 
I'm not sure if the onesignal-cordova-plugin could be responsible for that issue. 
I believe onesignal is for push notifications. I would expect that to conflict with making push notifications as on Cordova we only support using phonegap-plugin-push with Intercom. https://github.com/intercom/intercom-cordova#push-notifications

Is it possible to disable the onesignal-cordova-plugin and see if that has any effect on the alert that is popping up?

**Comment by IcyEagle** [comment]
@DaleCantwell Yep, OneSingal is made for notification management.

I've just updated the OneSignal plugin and the messages disappear! I'm not sure if a kind of compatibility fix was provided with the latest version or it's just a luck.

**Comment by DaleCantwell** [comment]
Oh thats good news, let us know if they pop back up. Thanks for contacting us @IcyEagle

**Comment by IcyEagle** [comment]
Actually other users has the same problem. Could you please check why it happens?

**Comment by DaleCantwell** [comment]
@IcyEagle you seem to have two apps in Intercom. Could you log into your Intercom dash [here](https://app.intercom.io/a/apps/_/users) and then start a conversation with us so we can discuss details of your apps setup?

**Comment by afilp** [comment]
@DaleCantwell Can you please provide us support for the *same* problem when using the "react-native-intercom" package? https://github.com/tinycreative/react-native-intercom/issues/39

We are stuck with this. Thanks!
