### ISSUE TITLE
Phonegap remote Android build failed

### ISSUE THREAD

**Issue by ithav** [intercom/intercom-cordova#85]
Hello

although it passed at the past (version 3.0.8), we are now experience build failure for Android.
we try to increment the version to any of .9/.10/.11 but to no avail. 

## Version info
  - Intercom for Cordova: 3.0.11/3.0.10/3.0.9/3.0.8
  - PhoneGap version: cli-6.3.0
  - iOS/Android OS version:
  - iOS/Android Device:

## Expected behavior
Phonegap remote Android build pass
## Actual behavior
Phonegap remote Android build failed
## Steps to reproduce
 1. https://build.phonegap.com/apps/<yourAppId>
 2. update source with config.xml refers to plugin version 3.0.11
 3. build for android

## Logs

> 
> BUILD FAILED
> 
> Total time: 17.045 secs
> Error: /project/gradlew: Command failed with exit code 1 Error output:
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project 'project'.
> > Could not resolve all dependencies for configuration ':_debugCompile'.
>    > Could not find com.android.support:design:24.2.1.
>      Searched in the following locations:
>          https://repo1.maven.org/maven2/com/android/support/design/24.2.1/design-24.2.1.pom
>          https://repo1.maven.org/maven2/com/android/support/design/24.2.1/design-24.2.1.jar
>          https://jcenter.bintray.com/com/android/support/design/24.2.1/design-24.2.1.pom
>          https://jcenter.bintray.com/com/android/support/design/24.2.1/design-24.2.1.jar
>          https://dl.bintray.com/intercom/intercom-maven/com/android/support/design/24.2.1/design-24.2.1.pom
>          https://dl.bintray.com/intercom/intercom-maven/com/android/support/design/24.2.1/design-24.2.1.jar
>          file:/android-sdk/extras/android/m2repository/com/android/support/design/24.2.1/design-24.2.1.pom
>          file:/android-sdk/extras/android/m2repository/com/android/support/design/24.2.1/design-24.2.1.jar
>          file:/android-sdk/extras/google/m2repository/com/android/support/design/24.2.1/design-24.2.1.pom
>          file:/android-sdk/extras/google/m2repository/com/android/support/design/24.2.1/design-24.2.1.jar
>      Required by:
>          :project:unspecified > io.intercom.android:intercom-sdk:3.0.9 > io.intercom.android:intercom-sdk-base:3.0.9
>    > Could not find com.android.support:appcompat-v7:24.2.1.
>      Searched in the following locations:
>          https://repo1.maven.org/maven2/com/android/support/appcompat-v7/24.2.1/appcompat-v7-24.2.1.pom
>          https://repo1.maven.org/maven2/com/android/support/appcompat-v7/24.2.1/appcompat-v7-24.2.1.jar
>          https://jcenter.bintray.com/com/android/support/appcompat-v7/24.2.1/appcompat-v7-24.2.1.pom
>          https://jcenter.bintray.com/com/android/support/appcompat-v7/24.2.1/appcompat-v7-24.2.1.jar
>          https://dl.bintray.com/intercom/intercom-maven/com/android/support/appcompat-v7/24.2.1/appcompat-v7-24.2.1.pom
>          https://dl.bintray.com/intercom/intercom-maven/com/android/support/appcompat-v7/24.2.1/appcompat-v7-24.2.1.jar
>          file:/android-sdk/extras/android/m2repository/com/android/support/appcompat-v7/24.2.1/appcompat-v7-24.2.1.pom
>          file:/android-sdk/extras/android/m2repository/com/android/support/appcompat-v7/24.2.1/appcompat-v7-24.2.1.jar
>          file:/android-sdk/extras/google/m2repository/com/android/support/appcompat-v7/24.2.1/appcompat-v7-24.2.1.pom
>          file:/android-sdk/extras/google/m2repository/com/android/support/appcompat-v7/24.2.1/appcompat-v7-24.2.1.jar
>      Required by:
>          :project:unspecified > io.intercom.android:intercom-sdk:3.0.9 > io.intercom.android:intercom-sdk-base:3.0.9
>    > Could not find com.android.support:animated-vector-drawable:24.2.1.
>      Searched in the following locations:
>          https://repo1.maven.org/maven2/com/android/support/animated-vector-drawable/24.2.1/animated-vector-drawable-24.2.1.pom
>          https://repo1.maven.org/maven2/com/android/support/animated-vector-drawable/24.2.1/animated-vector-drawable-24.2.1.jar
>          https://jcenter.bintray.com/com/android/support/animated-vector-drawable/24.2.1/animated-vector-drawable-24.2.1.pom
>          https://jcenter.bintray.com/com/android/support/animated-vector-drawable/24.2.1/animated-vector-drawable-24.2.1.jar
>          https://dl.bintray.com/intercom/intercom-maven/com/android/support/animated-vector-drawable/24.2.1/animated-vector-drawable-24.2.1.pom
>          https://dl.bintray.com/intercom/intercom-maven/com/android/support/animated-vector-drawable/24.2.1/animated-vector-drawable-24.2.1.jar
>          file:/android-sdk/extras/android/m2repository/com/android/support/animated-vector-drawable/24.2.1/animated-vector-drawable-24.2.1.pom
>          file:/android-sdk/extras/android/m2repository/com/android/support/animated-vector-drawable/24.2.1/animated-vector-drawable-24.2.1.jar
>          file:/android-sdk/extras/google/m2repository/com/android/support/animated-vector-drawable/24.2.1/animated-vector-drawable-24.2.1.pom
>          file:/android-sdk/extras/google/m2repository/com/android/support/animated-vector-drawable/24.2.1/animated-vector-drawable-24.2.1.jar
>      Required by:
>          :project:unspecified > io.intercom.android:intercom-sdk:3.0.9 > io.intercom.android:intercom-sdk-base:3.0.9
>    > Could not find com.android.support:support-vector-drawable:24.2.1.
>      Searched in the following locations:
>          https://repo1.maven.org/maven2/com/android/support/support-vector-drawable/24.2.1/support-vector-drawable-24.2.1.pom
>          https://repo1.maven.org/maven2/com/android/support/support-vector-drawable/24.2.1/support-vector-drawable-24.2.1.jar
>          https://jcenter.bintray.com/com/android/support/support-vector-drawable/24.2.1/support-vector-drawable-24.2.1.pom
>          https://jcenter.bintray.com/com/android/support/support-vector-drawable/24.2.1/support-vector-drawable-24.2.1.jar
>          https://dl.bintray.com/intercom/intercom-maven/com/android/support/support-vector-drawable/24.2.1/support-vector-drawable-24.2.1.pom
>          https://dl.bintray.com/intercom/intercom-maven/com/android/support/support-vector-drawable/24.2.1/support-vector-drawable-24.2.1.jar
>          file:/android-sdk/extras/android/m2repository/com/android/support/support-vector-drawable/24.2.1/support-vector-drawable-24.2.1.pom
>          file:/android-sdk/extras/android/m2repository/com/android/support/support-vector-drawable/24.2.1/support-vector-drawable-24.2.1.jar
>          file:/android-sdk/extras/google/m2repository/com/android/support/support-vector-drawable/24.2.1/support-vector-drawable-24.2.1.pom
>          file:/android-sdk/extras/google/m2repository/com/android/support/support-vector-drawable/24.2.1/support-vector-drawable-24.2.1.jar
>      Required by:
>          :project:unspecified > io.intercom.android:intercom-sdk:3.0.9 > io.intercom.android:intercom-sdk-base:3.0.9
>    > Could not find com.android.support:support-v4:24.2.1.
>      Searched in the following locations:
>          https://repo1.maven.org/maven2/com/android/support/support-v4/24.2.1/support-v4-24.2.1.pom
>          https://repo1.maven.org/maven2/com/android/support/support-v4/24.2.1/support-v4-24.2.1.jar
>          https://jcenter.bintray.com/com/android/support/support-v4/24.2.1/support-v4-24.2.1.pom
>          https://jcenter.bintray.com/com/android/support/support-v4/24.2.1/support-v4-24.2.1.jar
>          https://dl.bintray.com/intercom/intercom-maven/com/android/support/support-v4/24.2.1/support-v4-24.2.1.pom
>          https://dl.bintray.com/intercom/intercom-maven/com/android/support/support-v4/24.2.1/support-v4-24.2.1.jar
>          file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/24.2.1/support-v4-24.2.1.pom
>          file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/24.2.1/support-v4-24.2.1.jar
>          file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/24.2.1/support-v4-24.2.1.pom
>          file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/24.2.1/support-v4-24.2.1.jar
>      Required by:
>          :project:unspecified > io.intercom.android:intercom-sdk:3.0.9 > io.intercom.android:intercom-sdk-base:3.0.9
>    > Could not find com.android.support:support-annotations:24.2.1.
>      Searched in the following locations:
>          https://repo1.maven.org/maven2/com/android/support/support-annotations/24.2.1/support-annotations-24.2.1.pom
>          https://repo1.maven.org/maven2/com/android/support/support-annotations/24.2.1/support-annotations-24.2.1.jar
>          https://jcenter.bintray.com/com/android/support/support-annotations/24.2.1/support-annotations-24.2.1.pom
>          https://jcenter.bintray.com/com/android/support/support-annotations/24.2.1/support-annotations-24.2.1.jar
>          https://dl.bintray.com/intercom/intercom-maven/com/android/support/support-annotations/24.2.1/support-annotations-24.2.1.pom
>          https://dl.bintray.com/intercom/intercom-maven/com/android/support/support-annotations/24.2.1/support-annotations-24.2.1.jar
>          file:/android-sdk/extras/android/m2repository/com/android/support/support-annotations/24.2.1/support-annotations-24.2.1.pom
>          file:/android-sdk/extras/android/m2repository/com/android/support/support-annotations/24.2.1/support-annotations-24.2.1.jar
>          file:/android-sdk/extras/google/m2repository/com/android/support/support-annotations/24.2.1/support-annotations-24.2.1.pom
>          file:/android-sdk/extras/google/m2repository/com/android/support/support-annotations/24.2.1/support-annotations-24.2.1.jar
>      Required by:
>          :project:unspecified > io.intercom.android:intercom-sdk:3.0.9 > io.intercom.android:intercom-sdk-base:3.0.9
>    > Could not find com.android.support:recyclerview-v7:24.2.1.
>      Searched in the following locations:
>          https://repo1.maven.org/maven2/com/android/support/recyclerview-v7/24.2.1/recyclerview-v7-24.2.1.pom
>          https://repo1.maven.org/maven2/com/android/support/recyclerview-v7/24.2.1/recyclerview-v7-24.2.1.jar
>          https://jcenter.bintray.com/com/android/support/recyclerview-v7/24.2.1/recyclerview-v7-24.2.1.pom
>          https://jcenter.bintray.com/com/android/support/recyclerview-v7/24.2.1/recyclerview-v7-24.2.1.jar
>          https://dl.bintray.com/intercom/intercom-maven/com/android/support/recyclerview-v7/24.2.1/recyclerview-v7-24.2.1.pom
>          https://dl.bintray.com/intercom/intercom-maven/com/android/support/recyclerview-v7/24.2.1/recyclerview-v7-24.2.1.jar
>          file:/android-sdk/extras/android/m2repository/com/android/support/recyclerview-v7/24.2.1/recyclerview-v7-24.2.1.pom
>          file:/android-sdk/extras/android/m2repository/com/android/support/recyclerview-v7/24.2.1/recyclerview-v7-24.2.1.jar
>          file:/android-sdk/extras/google/m2repository/com/android/support/recyclerview-v7/24.2.1/recyclerview-v7-24.2.1.pom
>          file:/android-sdk/extras/google/m2repository/com/android/support/recyclerview-v7/24.2.1/recyclerview-v7-24.2.1.jar
>      Required by:
>          :project:unspecified > io.intercom.android:intercom-sdk:3.0.9 > io.intercom.android:intercom-sdk-base:3.0.9
>    > Could not find com.android.support:support-v4:24.2.1.
>      Searched in the following locations:
>          https://repo1.maven.org/maven2/com/android/support/support-v4/24.2.1/support-v4-24.2.1.pom
>          https://repo1.maven.org/maven2/com/android/support/support-v4/24.2.1/support-v4-24.2.1.jar
>          https://jcenter.bintray.com/com/android/support/support-v4/24.2.1/support-v4-24.2.1.pom
>          https://jcenter.bintray.com/com/android/support/support-v4/24.2.1/support-v4-24.2.1.jar
>          https://dl.bintray.com/intercom/intercom-maven/com/android/support/support-v4/24.2.1/support-v4-24.2.1.pom
>          https://dl.bintray.com/intercom/intercom-maven/com/android/support/support-v4/24.2.1/support-v4-24.2.1.jar
>          file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/24.2.1/support-v4-24.2.1.pom
>          file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/24.2.1/support-v4-24.2.1.jar
>          file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/24.2.1/support-v4-24.2.1.pom
>          file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/24.2.1/support-v4-24.2.1.jar
>      Required by:
>          :project:unspecified > io.intercom.android:intercom-sdk:3.0.9 > io.intercom.android:intercom-sdk-gcm:3.0.9 > com.google.android.gms:play-services-gcm:9.4.0 > com.google.android.gms:play-services-basement:9.4.0

**Comment by harkin** [comment]
hi @ithav.

The android version was updated to build against version 24.2.1 of some support libraries recently. Previously we were building against 24.2.0. You'll need to update your version of the support library locally. 

I'm not wholly knowledgeable about how you manage dependencies like this in Cordova. For 3.0.8 to work you'd need to have had v24.2.0 of the support libraries on your build path. If it was as a jar you'll need to replace it with the newer jar. It might be as simple as downloading the latest version through the android SDK manager.

**Comment by ithav** [comment]
Hi harkin

Thanks for your reply.
since I'm using phonegap remote build, I have no control of either the support libs version or the dependencies in general.

Thanks
Ithav

**Comment by harkin** [comment]
In that case you'll need to wait until the remote tools get updated. In the meantime you can continue using 3.0.8.

I don't think there's anything we can do to help you in this situation.
