### ISSUE TITLE
Problem with build android

### ISSUE THREAD

**Issue by brunoksato** [intercom/intercom-cordova#9]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find com.google.android.gms:play-services-gcm:7.5.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/7.5.0/play-services-gcm-7.5.0.pom
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/7.5.0/play-services-gcm-7.5.0.jar
         https://dl.bintray.com/intercom/intercom-maven/com/google/android/gms/play-services-gcm/7.5.0/play-services-gcm-7.5.0.pom
         https://dl.bintray.com/intercom/intercom-maven/com/google/android/gms/play-services-gcm/7.5.0/play-services-gcm-7.5.0.jar
         file:/Users/brunosato/Library/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/7.5.0/play-services-gcm-7.5.0.pom
         file:/Users/brunosato/Library/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/7.5.0/play-services-gcm-7.5.0.jar
         file:/Users/brunosato/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-gcm/7.5.0/play-services-gcm-7.5.0.pom
         file:/Users/brunosato/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-gcm/7.5.0/play-services-gcm-7.5.0.jar
     Required by:
         :android:unspecified > io.intercom.android:intercom-sdk:1.1.1
         :android:unspecified > io.intercom.android:intercom-sdk:1.1.1 > io.intercom.android:intercom-sdk-gcm:1.1.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.276 secs

/Users/brunosato/Desktop/Sato Corporation/PriceNinja/price-ninja-compara-preco/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /Users/brunosato/Desktop/Sato Corporation/PriceNinja/price-ninja-compara-preco/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/brunosato/Desktop/Sato Corporation/PriceNinja/price-ninja-compara-preco/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /Users/brunosato/Desktop/Sato Corporation/PriceNinja/price-ninja-compara-preco/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: /Users/brunosato/Desktop/Sato Corporation/PriceNinja/price-ninja-compara-preco/platforms/android/cordova/build: Command failed with exit code 1
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

**Comment by jtreanor** [comment]
Hi @brunoksato,

This means you haven't got the "Google Repository" installed on your machine. You can install it from the Android SDK Manager. [This](https://developer.android.com/sdk/installing/adding-packages.html) might help.

Let me know if you have any questions.

**Comment by brunoksato** [comment]
Ok Thanks
