### ISSUE TITLE
App crashes on Android version < 5 when displaying conversation list

### ISSUE THREAD

**Issue by lafactoriafr** [intercom/intercom-cordova#90]
## Version info
- Intercom for Cordova/PhoneGap version: 3.0.11
- iOS/Android OS version: Android 4.4.4 and below
- iOS/Android Device: tested on Samsung S3 and Genymotion emulator
## Expected behavior

When calling intercom.displayConversationsList();, should open conversation list.
## Actual behavior

The app crashes.
## Steps to reproduce
1. Install intercom-cordova on our app
2. Run app : cordova run android
3. Call intercom.displayConversationsList() and intercom.displayMessenger()
## Logs

> E/VdcInflateDelegate( 3803): Exception while inflating <vector>
> E/VdcInflateDelegate( 3803): org.xmlpull.v1.XmlPullParserException: Binary XML file line #17<vector> tag requires viewportWidth > 0
> E/VdcInflateDelegate( 3803):  at android.support.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:541)
> E/VdcInflateDelegate( 3803):  at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:478)
> E/VdcInflateDelegate( 3803):  at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:441)
> E/VdcInflateDelegate( 3803):  at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:742)
> E/VdcInflateDelegate( 3803):  at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:362)
> E/VdcInflateDelegate( 3803):  at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:192)
> E/VdcInflateDelegate( 3803):  at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:185)
> E/VdcInflateDelegate( 3803):  at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:720)
> E/VdcInflateDelegate( 3803):  at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
> E/VdcInflateDelegate( 3803):  at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
> E/VdcInflateDelegate( 3803):  at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127)
> E/VdcInflateDelegate( 3803):  at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147)
> E/VdcInflateDelegate( 3803):  at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27)
> E/VdcInflateDelegate( 3803):  at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:50)
> E/VdcInflateDelegate( 3803):  at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:201)
> E/VdcInflateDelegate( 3803):  at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:181)
> E/VdcInflateDelegate( 3803):  at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:521)
> E/VdcInflateDelegate( 3803):  at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
> E/VdcInflateDelegate( 3803):  at io.intercom.android.sdk.activities.IntercomBaseActivity.onCreate(IntercomBaseActivity.java:19)
> E/VdcInflateDelegate( 3803):  at io.intercom.android.sdk.activities.IntercomMessengerActivity.onCreate(IntercomMessengerActivity.java:64)
> E/VdcInflateDelegate( 3803):  at android.app.Activity.performCreate(Activity.java:5104)
> E/VdcInflateDelegate( 3803):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
> E/VdcInflateDelegate( 3803):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
> E/VdcInflateDelegate( 3803):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
> E/VdcInflateDelegate( 3803):  at android.app.ActivityThread.access$600(ActivityThread.java:141)
> E/VdcInflateDelegate( 3803):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
> E/VdcInflateDelegate( 3803):  at android.os.Handler.dispatchMessage(Handler.java:99)
> E/VdcInflateDelegate( 3803):  at android.os.Looper.loop(Looper.java:137)
> E/VdcInflateDelegate( 3803):  at android.app.ActivityThread.main(ActivityThread.java:5041)
> E/VdcInflateDelegate( 3803):  at java.lang.reflect.Method.invokeNative(Native Method)
> E/VdcInflateDelegate( 3803):  at java.lang.reflect.Method.invoke(Method.java:511)
> E/VdcInflateDelegate( 3803):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
> E/VdcInflateDelegate( 3803):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
> E/VdcInflateDelegate( 3803):  at dalvik.system.NativeStart.main(Native Method)
> D/AndroidRuntime( 3803): Shutting down VM
> W/dalvikvm( 3803): threadid=1: thread exiting with uncaught exception (group=0xa61b8908)
> E/AndroidRuntime( 3803): FATAL EXCEPTION: main
> E/AndroidRuntime( 3803): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pinotbleu.www/io.intercom.android.sdk.activities.IntercomMessengerActivity}: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052
> E/AndroidRuntime( 3803):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
> E/AndroidRuntime( 3803):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
> E/AndroidRuntime( 3803):  at android.app.ActivityThread.access$600(ActivityThread.java:141)
> E/AndroidRuntime( 3803):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
> E/AndroidRuntime( 3803):  at android.os.Handler.dispatchMessage(Handler.java:99)
> E/AndroidRuntime( 3803):  at android.os.Looper.loop(Looper.java:137)
> E/AndroidRuntime( 3803):  at android.app.ActivityThread.main(ActivityThread.java:5041)
> E/AndroidRuntime( 3803):  at java.lang.reflect.Method.invokeNative(Native Method)
> E/AndroidRuntime( 3803):  at java.lang.reflect.Method.invoke(Method.java:511)
> E/AndroidRuntime( 3803):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
> E/AndroidRuntime( 3803):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
> E/AndroidRuntime( 3803):  at dalvik.system.NativeStart.main(Native Method)
> E/AndroidRuntime( 3803): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052
> E/AndroidRuntime( 3803):  at android.content.res.Resources.loadDrawable(Resources.java:1953)
> E/AndroidRuntime( 3803):  at android.content.res.Resources.getDrawable(Resources.java:660)
> E/AndroidRuntime( 3803):  at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:346)
> E/AndroidRuntime( 3803):  at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197)
> E/AndroidRuntime( 3803):  at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:185)
> E/AndroidRuntime( 3803):  at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:720)
> E/AndroidRuntime( 3803):  at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
> E/AndroidRuntime( 3803):  at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
> E/AndroidRuntime( 3803):  at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127)
> E/AndroidRuntime( 3803):  at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147)
> E/AndroidRuntime( 3803):  at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27)
> E/AndroidRuntime( 3803):  at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:50)
> E/AndroidRuntime( 3803):  at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:201)
> E/AndroidRuntime( 3803):  at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:181)
> E/AndroidRuntime( 3803):  at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:521)
> E/AndroidRuntime( 3803):  at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
> E/AndroidRuntime( 3803):  at io.intercom.android.sdk.activities.IntercomBaseActivity.onCreate(IntercomBaseActivity.java:19)
> E/AndroidRuntime( 3803):  at io.intercom.android.sdk.activities.IntercomMessengerActivity.onCreate(IntercomMessengerActivity.java:64)
> E/AndroidRuntime( 3803):  at android.app.Activity.performCreate(Activity.java:5104)
> E/AndroidRuntime( 3803):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
> E/AndroidRuntime( 3803):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
> E/AndroidRuntime( 3803):  ... 11 more
> E/AndroidRuntime( 3803): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
> E/AndroidRuntime( 3803):  at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:881)
> E/AndroidRuntime( 3803):  at android.graphics.drawable.Drawable.createFromXml(Drawable.java:822)
> E/AndroidRuntime( 3803):  at android.content.res.Resources.loadDrawable(Resources.java:1950)
> E/AndroidRuntime( 3803):  ... 31 more
> W/ActivityManager(  393):   Force finishing activity com.pinotbleu.www/io.intercom.android.sdk.activities.IntercomMessengerActivity
> W/ActivityManager(  393):   Force finishing activity com.pinotbleu.www/.MainActivity

**Comment by corysmc** [comment]
I'm having this same issue

**Comment by ronocod** [comment]
What version of Cordova are you using?

**Comment by corysmc** [comment]
cordova CLI 6.2.0
cordova android: 5.1.1

**Comment by ronocod** [comment]
Can you try updating Cordova Android to the latest version? I think this is an Android build tools issue so updating may fix it.

**Comment by pascalmerme** [comment]
Hello, updated cordova and cordova-android to latest version, but there is still the bug.

**Comment by pascalmerme** [comment]
My mistake, it's working! Thanks :)

**Comment by ronocod** [comment]
Great! If everyone else can confirm that this is fixed in a clean build with the latest `cordova` and `cordova-android` versions then I'll close this off.
