### ISSUE TITLE
Not registering User in Intercom Dashboard

### ISSUE THREAD

**Issue by brandecho** [intercom/intercom-cordova#92]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
	Package: io.intercom.cordova.sample
  - Intercom for Cordova/PhoneGap version: cordova-android@5.2.2
	Android target: android-23
  - iOS/Android OS version: 6.01
  - iOS/Android Device: SAmsung Galaxy Edge 7 SM-G935V

## Expected behavior
1. Should register new user in Intercom Dashboard
2. Opens previous conversations
3. Intercom Icon on Lower Right of screen should appear

## Actual behavior
1. New email address / users are not registering in Intercom Dashboard
2. when clicking "Open Intercom" get "Something went wrong couldn't load your conversations"
3. No Icon on lower right

## Steps to reproduce
 1. Inspect android device on Android using Chrome Dev tool inspector
 2. Once the app opens the error is visible in the console
3. Enter email that is currently registered in Intercom Dashboard
 4. Also, when clicking "Open Intercom" get "Something went wrong couldn't load your conversations"
5. New email address / users are not registering in Intercom Dashboard

## Logs
index.js:62 Uncaught TypeError: intercom.setPreviewPosition is not a function

Uncaught TypeError: intercom.setPreviewPosition is not a function
index.js:43

**Comment by brandecho** [comment]
So good news thanks to @froasiooneloop. I was able to get Intercom icon to display in the Intercom Sample app by installing the crosswalk plugin. Bad news is that when I click on the icon or click on "Open Intercom" after I log in I still get the "Something went wrong" message.

**Comment by jtreanor** [comment]
Thanks for the detailed report @brandecho.

The "Something went wrong" error usually means there is a problem with the configuration.

Have you set your iOS/Android API key and app id in config.xml?
Have you registered a user using one of the registration methods?

**Comment by brandecho** [comment]
Hi @jtreanor We definitely did add the android_sdk-XXXXX that is located at https://app.intercom.io/a/apps/XXXXXXXX/settings/android within the Intercom Dashboard. 

We are using the Cordova Intercom plugin so our config.xml file has the following: (Key#'s removed for security purposes but they are in fact included in the config.xml file)
    <preference name="intercom-app-id" value="yXXXXXX" />
    <preference name="intercom-ios-api-key" value="ios_sdk-XXXXXX..." />
    <preference name="intercom-android-api-key" value="android_sdk-XXXXXX..." />
    <preference name="intercom-android-sender-id" value="XXXXXXXXXXX" /> 

Here are some screenshot of what is happening:
1. Login using the admin account log in info: https://dl.dropboxusercontent.com/u/29427193/intercom/Screenshot_20160929-153447.png
2. Click on "Open Intercom" https://dl.dropboxusercontent.com/u/29427193/intercom/Screenshot_20160929-153411.png
3. Try to send a message to see if we can see in Intercom Dashboard as well as the Intercom Android app: https://dl.dropboxusercontent.com/u/29427193/intercom/Screenshot_20160929-153322.png
4. Then we get the message again that something went wrong. https://dl.dropboxusercontent.com/u/29427193/intercom/Screenshot_20160929-153435.png

So in response to your previous comment, it doesnt seem to be the configuration at this point. 

Could it be that the used 2 different emails to login and maybe it is being saved in the device storage?

**Comment by jtreanor** [comment]
@brandecho There may be an issue with the user you are using here.

Is it possible that there are two users with the same email address in your Intercom account? This could be an issue if you are registering the user with an email address only.

**Comment by brandecho** [comment]
@jtreanor I made sure to delete any duplicate users prior to starting the app. Plus when registering a new user it is not showing up in the Intercom Dashboard. After I enter a new email that is not registered in the dashboard, I instantly get the "Something Went Wrong" screen. Just FYI.. I did not make any changes to the "Example" phonegap project you include with the plugin.

**Comment by jtreanor** [comment]
@brandecho even deleted duplicates can cause issues unfortunately.

Its sounds like adding a user id could definitely clear it up.

**Comment by jtreanor** [comment]
I'm closing this now because as far as I am aware there isn't an issue with Intercom here.

Feel free to reopen if you are still seeing any issues with this.
