### ISSUE TITLE
Link in automessage

### ISSUE THREAD

**Issue by kylepierce** [intercom/intercom-cordova#93]
What structure should I include in a link for automessages. 

I tried adding a basic /settings to a link in automessage and it doesnt do anything. 

Does the cordova plugin support linking? Will deep linking work?

**Comment by DaleCantwell** [comment]
Hi @kylepierce 
I have a few questions: 
- Are you testing on iOS or Android? 
- Do you have an example of the link you are sending? 
- How do you have deep linking set up currently in your cordova app? Are you using a plugin for it?

**Comment by kylepierce** [comment]
- iOS
- /settings 
- Using branch.io for deep linking

**Comment by skylerwshaw** [comment]
Hi Kyle, apologies for the delay here. Since this is a product question, I've reached out to you through your Intercom dashboard. Closing this issue as it is not a bug/issue with our Cordova plugin. Best, Skyler
