### ISSUE TITLE
Windows UWP support

### ISSUE THREAD

**Issue by slorber** [intercom/intercom-cordova#95]
Hi,

As far as I know, this plugin only supports iOS and Android.
It would be helpful if this plugin could also support universal windows platform applications, that run on mobile, desktop, xbox etc...

Even if it's not native UI, at least providing a similar web-based experience would be a nice fallback. Any idea on what can UWP developers to?

**Comment by bboyle18** [comment]
Hi @slorber 👋 
Thanks for getting in touch. Right now we are only supporting iOS and Android for the plugin. We don't have any plans at the moment to extend this to other platforms.

Cheers

Brian

**Comment by slorber** [comment]
thanks for quick reply.

So I'll fallback to an email to support in case user wants help :)

**Comment by bboyle18** [comment]
You could use our JS messenger on mobile web, if that would help?

**Comment by slorber** [comment]
for the mobile website we can do that, but can we on a cordova app?

is it safe to load a remote JS file, or can we package your intercom JS script with Webpack/Browserify bundle?

**Comment by bboyle18** [comment]
If you have Cordova for iOS or Android, you should use our plugin.
If you're using Cordova on another platform (e.g. Windows) you could use Intercom JS. You'd just need to add the JS snippet that Intercom provides you during your install process. https://docs.intercom.com/install-on-your-product-or-site/quick-install/install-intercom-on-your-web-app

From a security perspective, you'd need to make sure that you don't embed any API keys or secrets within the app. 
One other thing to note with the mobile web integration, is that you won't have access to push notifications like you would on iOS/Android.

Cheers,

Brian

**Comment by slorber** [comment]
@bboyle18 the problem is that the web version of Intercom is based on a js snippet that loads a remote script

```javascript
<script>
  window.intercomSettings = {
    app_id: 'APP_ID',
    name: "Jane Doe", // Full name
    email: "customer@example.com", // Email address
    created_at: 1312182000 // Signup date as a Unix timestamp
  };
</script>
<script>(function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://widget.intercom.io/widget/APP_ID';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);}if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})()</script>
```

This works fine in most cases but I'm not sure it's recommended for Cordova apps, where all JS assets should rather be available locally, without remote loading, for security reasons and app store policies. I'm not sure of the behavior for Windows app so I'll have to check, but this seems to me a problem.

I would be fine using the web intercom version on my UWP app, but I would like to embed all intercom web javascript directly inside by app package. So it would be better if I could simply do `import Intercom from 'intercom'` and build my app with a tool like Webpack
