### ISSUE TITLE
3.0.12 Not available from npm

### ISSUE THREAD

**Issue by coffeeexistence** [intercom/intercom-cordova#97]
Hello, I was looking to install this plugin, but was not able to due to a 404 error.
cordova plugin add cordova-plugin-intercom
`Fetching plugin "cordova-plugin-intercom" via npm
npm ERR! fetch failed https://registry.npmjs.org/cordova-plugin-intercom/-/cordova-plugin-intercom-3.0.12.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/cordova-plugin-intercom/-/cordova-plugin-intercom-3.0.12.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/cordova-plugin-intercom/-/cordova-plugin-intercom-3.0.12.tgz
Error: Failed to fetch plugin cordova-plugin-intercom via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: fetch failed with status code 404`

**Comment by jtreanor** [comment]
Hi @coffeeexistence,

Thanks for reporting this. Unfortunately, this seems to be an issue with npm itself. I have reported it [here](https://github.com/npm/registry/issues/63).

We will release (3.0.13)[https://github.com/intercom/intercom-cordova/pull/98] to hopefully work around the issue.

I'll keep you updated.

**Comment by jtreanor** [comment]
3.0.13 is now released to work around the npm issue.
