### ISSUE TITLE
Plugin installation fetch failed

### ISSUE THREAD

**Issue by mikyaj** [intercom/intercom-cordova#99]
I am trying to install plugin, but getting failed with 504 status code.

## Version info
  - npm version: 3.10.3
  - node version: 6.4.0
  - cordova version: 6.0.0

## Steps to reproduce
```sh  
$ cordova plugin add cordova-plugin-intercom
```
## Logs
```sh
npm ERR! fetch failed https://registry.npmjs.org/cordova-plugin-intercom/-/cordova-plugin-intercom-3.0.12.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 504
```

**Comment by coffeeexistence** [comment]
Until this gets resolved, we can access the plugin by running `cordova plugin add https://github.com/intercom/intercom-cordova.git --save`

**Comment by jtreanor** [comment]
Also tracked in https://github.com/intercom/intercom-cordova/issues/97
The issue is with npm and the fix is imminent.

**Comment by jtreanor** [comment]
3.0.13 is now released successfully to npm.
